// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/arith.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

func addFloat32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addFloat32VSX(dst[:n:n], a, b)
}

func subFloat32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subFloat32VSX(dst[:n:n], a, b)
}

func mulFloat32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulFloat32VSX(dst[:n:n], a, b)
}

func minimumFloat32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumFloat(dst, a, b)
		return
	}
	minimumFloat32VSX(dst[:n:n], a, b)
}

func maximumFloat32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumFloat(dst, a, b)
		return
	}
	maximumFloat32VSX(dst[:n:n], a, b)
}

func absFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsFloat(dst, a)
		return
	}
	absFloat32VSX(dst[:n:n], a)
}

func negFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegFloat(dst, a)
		return
	}
	negFloat32VSX(dst[:n:n], a)
}

func scaleFloat32VSXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleFloat32VSX(dst[:n:n], a, s)
}

func addScalarFloat32VSXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarFloat32VSX(dst[:n:n], a, s)
}

func subScalarFloat32VSXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarFloat32VSX(dst[:n:n], a, s)
}

func clampFloat32VSXGuarded(dst []float32, a []float32, lo float32, hi float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampFloat(dst, a, lo, hi)
		return
	}
	clampFloat32VSX(dst[:n:n], a, lo, hi)
}

func fillFloat32VSXGuarded(dst []float32, v float32) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillFloat32VSX(dst, v)
}

func lerpFloat32VSXGuarded(dst []float32, a []float32, b []float32, t float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpFloat32VSX(dst[:n:n], a, b, t)
}

func addScaledFloat32VSXGuarded(dst []float32, a []float32, b []float32, s float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledFloat32VSX(dst[:n:n], a, b, s)
}

func rampFloat32VSXGuarded(dst []float32, start float32, step float32) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampFloat32VSX(dst, start, step)
}

func addFloat64VSXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addFloat64VSX(dst[:n:n], a, b)
}

func subFloat64VSXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subFloat64VSX(dst[:n:n], a, b)
}

func mulFloat64VSXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulFloat64VSX(dst[:n:n], a, b)
}

func minimumFloat64VSXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumFloat(dst, a, b)
		return
	}
	minimumFloat64VSX(dst[:n:n], a, b)
}

func maximumFloat64VSXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumFloat(dst, a, b)
		return
	}
	maximumFloat64VSX(dst[:n:n], a, b)
}

func absFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsFloat(dst, a)
		return
	}
	absFloat64VSX(dst[:n:n], a)
}

func negFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegFloat(dst, a)
		return
	}
	negFloat64VSX(dst[:n:n], a)
}

func scaleFloat64VSXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleFloat64VSX(dst[:n:n], a, s)
}

func addScalarFloat64VSXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarFloat64VSX(dst[:n:n], a, s)
}

func subScalarFloat64VSXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarFloat64VSX(dst[:n:n], a, s)
}

func clampFloat64VSXGuarded(dst []float64, a []float64, lo float64, hi float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampFloat(dst, a, lo, hi)
		return
	}
	clampFloat64VSX(dst[:n:n], a, lo, hi)
}

func fillFloat64VSXGuarded(dst []float64, v float64) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillFloat64VSX(dst, v)
}

func lerpFloat64VSXGuarded(dst []float64, a []float64, b []float64, t float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpFloat64VSX(dst[:n:n], a, b, t)
}

func addScaledFloat64VSXGuarded(dst []float64, a []float64, b []float64, s float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledFloat64VSX(dst[:n:n], a, b, s)
}

func rampFloat64VSXGuarded(dst []float64, start float64, step float64) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampFloat64VSX(dst, start, step)
}

func addInt32VSXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt32VSX(dst[:n:n], a, b)
}

func subInt32VSXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt32VSX(dst[:n:n], a, b)
}

func mulInt32VSXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulInt32VSX(dst[:n:n], a, b)
}

func minimumInt32VSXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt32VSX(dst[:n:n], a, b)
}

func maximumInt32VSXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt32VSX(dst[:n:n], a, b)
}

func absInt32VSXGuarded(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt32VSX(dst[:n:n], a)
}

func negInt32VSXGuarded(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt32VSX(dst[:n:n], a)
}

func scaleInt32VSXGuarded(dst []int32, a []int32, s int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleInt32VSX(dst[:n:n], a, s)
}

func addScalarInt32VSXGuarded(dst []int32, a []int32, s int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt32VSX(dst[:n:n], a, s)
}

func subScalarInt32VSXGuarded(dst []int32, a []int32, s int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt32VSX(dst[:n:n], a, s)
}

func clampInt32VSXGuarded(dst []int32, a []int32, lo int32, hi int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt32VSX(dst[:n:n], a, lo, hi)
}

func fillInt32VSXGuarded(dst []int32, v int32) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt32VSX(dst, v)
}

func lerpInt32VSXGuarded(dst []int32, a []int32, b []int32, t int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpInt32VSX(dst[:n:n], a, b, t)
}

func addScaledInt32VSXGuarded(dst []int32, a []int32, b []int32, s int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledInt32VSX(dst[:n:n], a, b, s)
}

func rampInt32VSXGuarded(dst []int32, start int32, step int32) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampInt32VSX(dst, start, step)
}

func addInt64VSXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt64VSX(dst[:n:n], a, b)
}

func subInt64VSXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt64VSX(dst[:n:n], a, b)
}

func minimumInt64VSXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt64VSX(dst[:n:n], a, b)
}

func maximumInt64VSXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt64VSX(dst[:n:n], a, b)
}

func absInt64VSXGuarded(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt64VSX(dst[:n:n], a)
}

func negInt64VSXGuarded(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt64VSX(dst[:n:n], a)
}

func addScalarInt64VSXGuarded(dst []int64, a []int64, s int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt64VSX(dst[:n:n], a, s)
}

func subScalarInt64VSXGuarded(dst []int64, a []int64, s int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt64VSX(dst[:n:n], a, s)
}

func clampInt64VSXGuarded(dst []int64, a []int64, lo int64, hi int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt64VSX(dst[:n:n], a, lo, hi)
}

func fillInt64VSXGuarded(dst []int64, v int64) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt64VSX(dst, v)
}

func addInt8VSXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt8VSX(dst[:n:n], a, b)
}

func subInt8VSXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt8VSX(dst[:n:n], a, b)
}

func mulInt8VSXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulInt8VSX(dst[:n:n], a, b)
}

func minimumInt8VSXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt8VSX(dst[:n:n], a, b)
}

func maximumInt8VSXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt8VSX(dst[:n:n], a, b)
}

func absInt8VSXGuarded(dst []int8, a []int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt8VSX(dst[:n:n], a)
}

func negInt8VSXGuarded(dst []int8, a []int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt8VSX(dst[:n:n], a)
}

func scaleInt8VSXGuarded(dst []int8, a []int8, s int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleInt8VSX(dst[:n:n], a, s)
}

func addScalarInt8VSXGuarded(dst []int8, a []int8, s int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt8VSX(dst[:n:n], a, s)
}

func subScalarInt8VSXGuarded(dst []int8, a []int8, s int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt8VSX(dst[:n:n], a, s)
}

func clampInt8VSXGuarded(dst []int8, a []int8, lo int8, hi int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt8VSX(dst[:n:n], a, lo, hi)
}

func fillInt8VSXGuarded(dst []int8, v int8) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt8VSX(dst, v)
}

func lerpInt8VSXGuarded(dst []int8, a []int8, b []int8, t int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpInt8VSX(dst[:n:n], a, b, t)
}

func addScaledInt8VSXGuarded(dst []int8, a []int8, b []int8, s int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledInt8VSX(dst[:n:n], a, b, s)
}

func rampInt8VSXGuarded(dst []int8, start int8, step int8) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampInt8VSX(dst, start, step)
}

func addInt16VSXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt16VSX(dst[:n:n], a, b)
}

func subInt16VSXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt16VSX(dst[:n:n], a, b)
}

func mulInt16VSXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulInt16VSX(dst[:n:n], a, b)
}

func minimumInt16VSXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt16VSX(dst[:n:n], a, b)
}

func maximumInt16VSXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt16VSX(dst[:n:n], a, b)
}

func absInt16VSXGuarded(dst []int16, a []int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt16VSX(dst[:n:n], a)
}

func negInt16VSXGuarded(dst []int16, a []int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt16VSX(dst[:n:n], a)
}

func scaleInt16VSXGuarded(dst []int16, a []int16, s int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleInt16VSX(dst[:n:n], a, s)
}

func addScalarInt16VSXGuarded(dst []int16, a []int16, s int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt16VSX(dst[:n:n], a, s)
}

func subScalarInt16VSXGuarded(dst []int16, a []int16, s int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt16VSX(dst[:n:n], a, s)
}

func clampInt16VSXGuarded(dst []int16, a []int16, lo int16, hi int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt16VSX(dst[:n:n], a, lo, hi)
}

func fillInt16VSXGuarded(dst []int16, v int16) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt16VSX(dst, v)
}

func lerpInt16VSXGuarded(dst []int16, a []int16, b []int16, t int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpInt16VSX(dst[:n:n], a, b, t)
}

func addScaledInt16VSXGuarded(dst []int16, a []int16, b []int16, s int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledInt16VSX(dst[:n:n], a, b, s)
}

func rampInt16VSXGuarded(dst []int16, start int16, step int16) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampInt16VSX(dst, start, step)
}

func addUint8VSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint8VSX(dst[:n:n], a, b)
}

func subUint8VSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint8VSX(dst[:n:n], a, b)
}

func mulUint8VSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulUint8VSX(dst[:n:n], a, b)
}

func minimumUint8VSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint8VSX(dst[:n:n], a, b)
}

func maximumUint8VSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint8VSX(dst[:n:n], a, b)
}

func absUint8VSXGuarded(dst []byte, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint8VSX(dst[:n:n], a)
}

func negUint8VSXGuarded(dst []byte, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint8VSX(dst[:n:n], a)
}

func scaleUint8VSXGuarded(dst []byte, a []byte, s byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleUint8VSX(dst[:n:n], a, s)
}

func addScalarUint8VSXGuarded(dst []byte, a []byte, s byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint8VSX(dst[:n:n], a, s)
}

func subScalarUint8VSXGuarded(dst []byte, a []byte, s byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint8VSX(dst[:n:n], a, s)
}

func clampUint8VSXGuarded(dst []byte, a []byte, lo byte, hi byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint8VSX(dst[:n:n], a, lo, hi)
}

func fillUint8VSXGuarded(dst []byte, v byte) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint8VSX(dst, v)
}

func lerpUint8VSXGuarded(dst []byte, a []byte, b []byte, t byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpUint8VSX(dst[:n:n], a, b, t)
}

func addScaledUint8VSXGuarded(dst []byte, a []byte, b []byte, s byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledUint8VSX(dst[:n:n], a, b, s)
}

func rampUint8VSXGuarded(dst []byte, start byte, step byte) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampUint8VSX(dst, start, step)
}

func addUint16VSXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint16VSX(dst[:n:n], a, b)
}

func subUint16VSXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint16VSX(dst[:n:n], a, b)
}

func mulUint16VSXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulUint16VSX(dst[:n:n], a, b)
}

func minimumUint16VSXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint16VSX(dst[:n:n], a, b)
}

func maximumUint16VSXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint16VSX(dst[:n:n], a, b)
}

func absUint16VSXGuarded(dst []uint16, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint16VSX(dst[:n:n], a)
}

func negUint16VSXGuarded(dst []uint16, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint16VSX(dst[:n:n], a)
}

func scaleUint16VSXGuarded(dst []uint16, a []uint16, s uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleUint16VSX(dst[:n:n], a, s)
}

func addScalarUint16VSXGuarded(dst []uint16, a []uint16, s uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint16VSX(dst[:n:n], a, s)
}

func subScalarUint16VSXGuarded(dst []uint16, a []uint16, s uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint16VSX(dst[:n:n], a, s)
}

func clampUint16VSXGuarded(dst []uint16, a []uint16, lo uint16, hi uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint16VSX(dst[:n:n], a, lo, hi)
}

func fillUint16VSXGuarded(dst []uint16, v uint16) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint16VSX(dst, v)
}

func lerpUint16VSXGuarded(dst []uint16, a []uint16, b []uint16, t uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpUint16VSX(dst[:n:n], a, b, t)
}

func addScaledUint16VSXGuarded(dst []uint16, a []uint16, b []uint16, s uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledUint16VSX(dst[:n:n], a, b, s)
}

func rampUint16VSXGuarded(dst []uint16, start uint16, step uint16) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampUint16VSX(dst, start, step)
}

func addUint32VSXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint32VSX(dst[:n:n], a, b)
}

func subUint32VSXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint32VSX(dst[:n:n], a, b)
}

func mulUint32VSXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulUint32VSX(dst[:n:n], a, b)
}

func minimumUint32VSXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint32VSX(dst[:n:n], a, b)
}

func maximumUint32VSXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint32VSX(dst[:n:n], a, b)
}

func absUint32VSXGuarded(dst []uint32, a []uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint32VSX(dst[:n:n], a)
}

func negUint32VSXGuarded(dst []uint32, a []uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint32VSX(dst[:n:n], a)
}

func scaleUint32VSXGuarded(dst []uint32, a []uint32, s uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleUint32VSX(dst[:n:n], a, s)
}

func addScalarUint32VSXGuarded(dst []uint32, a []uint32, s uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint32VSX(dst[:n:n], a, s)
}

func subScalarUint32VSXGuarded(dst []uint32, a []uint32, s uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint32VSX(dst[:n:n], a, s)
}

func clampUint32VSXGuarded(dst []uint32, a []uint32, lo uint32, hi uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint32VSX(dst[:n:n], a, lo, hi)
}

func fillUint32VSXGuarded(dst []uint32, v uint32) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint32VSX(dst, v)
}

func lerpUint32VSXGuarded(dst []uint32, a []uint32, b []uint32, t uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpUint32VSX(dst[:n:n], a, b, t)
}

func addScaledUint32VSXGuarded(dst []uint32, a []uint32, b []uint32, s uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledUint32VSX(dst[:n:n], a, b, s)
}

func rampUint32VSXGuarded(dst []uint32, start uint32, step uint32) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampUint32VSX(dst, start, step)
}

func addUint64VSXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint64VSX(dst[:n:n], a, b)
}

func subUint64VSXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint64VSX(dst[:n:n], a, b)
}

func minimumUint64VSXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint64VSX(dst[:n:n], a, b)
}

func maximumUint64VSXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint64VSX(dst[:n:n], a, b)
}

func absUint64VSXGuarded(dst []uint64, a []uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint64VSX(dst[:n:n], a)
}

func negUint64VSXGuarded(dst []uint64, a []uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint64VSX(dst[:n:n], a)
}

func addScalarUint64VSXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint64VSX(dst[:n:n], a, s)
}

func subScalarUint64VSXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint64VSX(dst[:n:n], a, s)
}

func clampUint64VSXGuarded(dst []uint64, a []uint64, lo uint64, hi uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint64VSX(dst[:n:n], a, lo, hi)
}

func fillUint64VSXGuarded(dst []uint64, v uint64) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint64VSX(dst, v)
}

func shlInt32VSXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlInt32VSX(dst[:n:n], a, s)
}

func shrInt32VSXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt32VSX(dst[:n:n], a, s)
}

func rotlInt32VSXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlInt32VSX(dst[:n:n], a, s)
}

func rotrInt32VSXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrInt32VSX(dst[:n:n], a, s)
}

func shlInt64VSXGuarded(dst []int64, a []int64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlInt64VSX(dst[:n:n], a, s)
}

func shrInt64VSXGuarded(dst []int64, a []int64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt64VSX(dst[:n:n], a, s)
}

func rotlInt64VSXGuarded(dst []int64, a []int64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlInt64VSX(dst[:n:n], a, s)
}

func rotrInt64VSXGuarded(dst []int64, a []int64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrInt64VSX(dst[:n:n], a, s)
}

func shlInt8VSXGuarded(dst []int8, a []int8, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlInt8VSX(dst[:n:n], a, s)
}

func shrInt8VSXGuarded(dst []int8, a []int8, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt8VSX(dst[:n:n], a, s)
}

func rotlInt8VSXGuarded(dst []int8, a []int8, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlInt8VSX(dst[:n:n], a, s)
}

func rotrInt8VSXGuarded(dst []int8, a []int8, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrInt8VSX(dst[:n:n], a, s)
}

func shlInt16VSXGuarded(dst []int16, a []int16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlInt16VSX(dst[:n:n], a, s)
}

func shrInt16VSXGuarded(dst []int16, a []int16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt16VSX(dst[:n:n], a, s)
}

func rotlInt16VSXGuarded(dst []int16, a []int16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlInt16VSX(dst[:n:n], a, s)
}

func rotrInt16VSXGuarded(dst []int16, a []int16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrInt16VSX(dst[:n:n], a, s)
}

func shlUint8VSXGuarded(dst []byte, a []byte, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlUint8VSX(dst[:n:n], a, s)
}

func shrUint8VSXGuarded(dst []byte, a []byte, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint8VSX(dst[:n:n], a, s)
}

func rotlUint8VSXGuarded(dst []byte, a []byte, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlUint8VSX(dst[:n:n], a, s)
}

func rotrUint8VSXGuarded(dst []byte, a []byte, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrUint8VSX(dst[:n:n], a, s)
}

func shlUint16VSXGuarded(dst []uint16, a []uint16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlUint16VSX(dst[:n:n], a, s)
}

func shrUint16VSXGuarded(dst []uint16, a []uint16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint16VSX(dst[:n:n], a, s)
}

func rotlUint16VSXGuarded(dst []uint16, a []uint16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlUint16VSX(dst[:n:n], a, s)
}

func rotrUint16VSXGuarded(dst []uint16, a []uint16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrUint16VSX(dst[:n:n], a, s)
}

func shlUint32VSXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlUint32VSX(dst[:n:n], a, s)
}

func shrUint32VSXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint32VSX(dst[:n:n], a, s)
}

func rotlUint32VSXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlUint32VSX(dst[:n:n], a, s)
}

func rotrUint32VSXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrUint32VSX(dst[:n:n], a, s)
}

func shlUint64VSXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlUint64VSX(dst[:n:n], a, s)
}

func shrUint64VSXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint64VSX(dst[:n:n], a, s)
}

func rotlUint64VSXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlUint64VSX(dst[:n:n], a, s)
}

func rotrUint64VSXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrUint64VSX(dst[:n:n], a, s)
}

func divFloat32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Div(dst, a, b)
		return
	}
	divFloat32VSX(dst[:n:n], a, b)
}

func divScalarFloat32VSXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DivScalar(dst, a, s)
		return
	}
	divScalarFloat32VSX(dst[:n:n], a, s)
}

func sqrtFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Sqrt(dst, a)
		return
	}
	sqrtFloat32VSX(dst[:n:n], a)
}

func reciprocalFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Reciprocal(dst, a)
		return
	}
	reciprocalFloat32VSX(dst[:n:n], a)
}

func floorFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Floor(dst, a)
		return
	}
	floorFloat32VSX(dst[:n:n], a)
}

func ceilFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Ceil(dst, a)
		return
	}
	ceilFloat32VSX(dst[:n:n], a)
}

func truncFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Trunc(dst, a)
		return
	}
	truncFloat32VSX(dst[:n:n], a)
}

func roundFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Round(dst, a)
		return
	}
	roundFloat32VSX(dst[:n:n], a)
}

func divFloat64VSXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Div(dst, a, b)
		return
	}
	divFloat64VSX(dst[:n:n], a, b)
}

func divScalarFloat64VSXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DivScalar(dst, a, s)
		return
	}
	divScalarFloat64VSX(dst[:n:n], a, s)
}

func sqrtFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Sqrt(dst, a)
		return
	}
	sqrtFloat64VSX(dst[:n:n], a)
}

func reciprocalFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Reciprocal(dst, a)
		return
	}
	reciprocalFloat64VSX(dst[:n:n], a)
}

func floorFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Floor(dst, a)
		return
	}
	floorFloat64VSX(dst[:n:n], a)
}

func ceilFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Ceil(dst, a)
		return
	}
	ceilFloat64VSX(dst[:n:n], a)
}

func truncFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Trunc(dst, a)
		return
	}
	truncFloat64VSX(dst[:n:n], a)
}

func roundFloat64VSXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Round(dst, a)
		return
	}
	roundFloat64VSX(dst[:n:n], a)
}

func satAddInt32VSXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddInt32VSX(dst[:n:n], a, b)
}

func satSubInt32VSXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubInt32VSX(dst[:n:n], a, b)
}

func satAddInt8VSXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddInt8VSX(dst[:n:n], a, b)
}

func satSubInt8VSXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubInt8VSX(dst[:n:n], a, b)
}

func satAddInt16VSXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddInt16VSX(dst[:n:n], a, b)
}

func satSubInt16VSXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubInt16VSX(dst[:n:n], a, b)
}

func satAddUint8VSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddUint8VSX(dst[:n:n], a, b)
}

func satSubUint8VSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubUint8VSX(dst[:n:n], a, b)
}

func satAddUint16VSXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddUint16VSX(dst[:n:n], a, b)
}

func satSubUint16VSXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubUint16VSX(dst[:n:n], a, b)
}

func satAddUint32VSXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddUint32VSX(dst[:n:n], a, b)
}

func satSubUint32VSXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubUint32VSX(dst[:n:n], a, b)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("vsx")
	s.F32.Add = addFloat32VSXGuarded
	s.F32.Sub = subFloat32VSXGuarded
	s.F32.Mul = mulFloat32VSXGuarded
	s.F32.Minimum = minimumFloat32VSXGuarded
	s.F32.Maximum = maximumFloat32VSXGuarded
	s.F32.Abs = absFloat32VSXGuarded
	s.F32.Neg = negFloat32VSXGuarded
	s.F32.Scale = scaleFloat32VSXGuarded
	s.F32.AddScalar = addScalarFloat32VSXGuarded
	s.F32.SubScalar = subScalarFloat32VSXGuarded
	s.F32.Clamp = clampFloat32VSXGuarded
	s.F32.Fill = fillFloat32VSXGuarded
	s.F32.Lerp = lerpFloat32VSXGuarded
	s.F32.AddScaled = addScaledFloat32VSXGuarded
	s.F32.Ramp = rampFloat32VSXGuarded
	s.F64.Add = addFloat64VSXGuarded
	s.F64.Sub = subFloat64VSXGuarded
	s.F64.Mul = mulFloat64VSXGuarded
	s.F64.Minimum = minimumFloat64VSXGuarded
	s.F64.Maximum = maximumFloat64VSXGuarded
	s.F64.Abs = absFloat64VSXGuarded
	s.F64.Neg = negFloat64VSXGuarded
	s.F64.Scale = scaleFloat64VSXGuarded
	s.F64.AddScalar = addScalarFloat64VSXGuarded
	s.F64.SubScalar = subScalarFloat64VSXGuarded
	s.F64.Clamp = clampFloat64VSXGuarded
	s.F64.Fill = fillFloat64VSXGuarded
	s.F64.Lerp = lerpFloat64VSXGuarded
	s.F64.AddScaled = addScaledFloat64VSXGuarded
	s.F64.Ramp = rampFloat64VSXGuarded
	s.I32.Add = addInt32VSXGuarded
	s.I32.Sub = subInt32VSXGuarded
	s.I32.Mul = mulInt32VSXGuarded
	s.I32.Minimum = minimumInt32VSXGuarded
	s.I32.Maximum = maximumInt32VSXGuarded
	s.I32.Abs = absInt32VSXGuarded
	s.I32.Neg = negInt32VSXGuarded
	s.I32.Scale = scaleInt32VSXGuarded
	s.I32.AddScalar = addScalarInt32VSXGuarded
	s.I32.SubScalar = subScalarInt32VSXGuarded
	s.I32.Clamp = clampInt32VSXGuarded
	s.I32.Fill = fillInt32VSXGuarded
	s.I32.Lerp = lerpInt32VSXGuarded
	s.I32.AddScaled = addScaledInt32VSXGuarded
	s.I32.Ramp = rampInt32VSXGuarded
	s.I64.Add = addInt64VSXGuarded
	s.I64.Sub = subInt64VSXGuarded
	s.I64.Minimum = minimumInt64VSXGuarded
	s.I64.Maximum = maximumInt64VSXGuarded
	s.I64.Abs = absInt64VSXGuarded
	s.I64.Neg = negInt64VSXGuarded
	s.I64.AddScalar = addScalarInt64VSXGuarded
	s.I64.SubScalar = subScalarInt64VSXGuarded
	s.I64.Clamp = clampInt64VSXGuarded
	s.I64.Fill = fillInt64VSXGuarded
	s.I8.Add = addInt8VSXGuarded
	s.I8.Sub = subInt8VSXGuarded
	s.I8.Mul = mulInt8VSXGuarded
	s.I8.Minimum = minimumInt8VSXGuarded
	s.I8.Maximum = maximumInt8VSXGuarded
	s.I8.Abs = absInt8VSXGuarded
	s.I8.Neg = negInt8VSXGuarded
	s.I8.Scale = scaleInt8VSXGuarded
	s.I8.AddScalar = addScalarInt8VSXGuarded
	s.I8.SubScalar = subScalarInt8VSXGuarded
	s.I8.Clamp = clampInt8VSXGuarded
	s.I8.Fill = fillInt8VSXGuarded
	s.I8.Lerp = lerpInt8VSXGuarded
	s.I8.AddScaled = addScaledInt8VSXGuarded
	s.I8.Ramp = rampInt8VSXGuarded
	s.I16.Add = addInt16VSXGuarded
	s.I16.Sub = subInt16VSXGuarded
	s.I16.Mul = mulInt16VSXGuarded
	s.I16.Minimum = minimumInt16VSXGuarded
	s.I16.Maximum = maximumInt16VSXGuarded
	s.I16.Abs = absInt16VSXGuarded
	s.I16.Neg = negInt16VSXGuarded
	s.I16.Scale = scaleInt16VSXGuarded
	s.I16.AddScalar = addScalarInt16VSXGuarded
	s.I16.SubScalar = subScalarInt16VSXGuarded
	s.I16.Clamp = clampInt16VSXGuarded
	s.I16.Fill = fillInt16VSXGuarded
	s.I16.Lerp = lerpInt16VSXGuarded
	s.I16.AddScaled = addScaledInt16VSXGuarded
	s.I16.Ramp = rampInt16VSXGuarded
	s.U8.Add = addUint8VSXGuarded
	s.U8.Sub = subUint8VSXGuarded
	s.U8.Mul = mulUint8VSXGuarded
	s.U8.Minimum = minimumUint8VSXGuarded
	s.U8.Maximum = maximumUint8VSXGuarded
	s.U8.Abs = absUint8VSXGuarded
	s.U8.Neg = negUint8VSXGuarded
	s.U8.Scale = scaleUint8VSXGuarded
	s.U8.AddScalar = addScalarUint8VSXGuarded
	s.U8.SubScalar = subScalarUint8VSXGuarded
	s.U8.Clamp = clampUint8VSXGuarded
	s.U8.Fill = fillUint8VSXGuarded
	s.U8.Lerp = lerpUint8VSXGuarded
	s.U8.AddScaled = addScaledUint8VSXGuarded
	s.U8.Ramp = rampUint8VSXGuarded
	s.U16.Add = addUint16VSXGuarded
	s.U16.Sub = subUint16VSXGuarded
	s.U16.Mul = mulUint16VSXGuarded
	s.U16.Minimum = minimumUint16VSXGuarded
	s.U16.Maximum = maximumUint16VSXGuarded
	s.U16.Abs = absUint16VSXGuarded
	s.U16.Neg = negUint16VSXGuarded
	s.U16.Scale = scaleUint16VSXGuarded
	s.U16.AddScalar = addScalarUint16VSXGuarded
	s.U16.SubScalar = subScalarUint16VSXGuarded
	s.U16.Clamp = clampUint16VSXGuarded
	s.U16.Fill = fillUint16VSXGuarded
	s.U16.Lerp = lerpUint16VSXGuarded
	s.U16.AddScaled = addScaledUint16VSXGuarded
	s.U16.Ramp = rampUint16VSXGuarded
	s.U32.Add = addUint32VSXGuarded
	s.U32.Sub = subUint32VSXGuarded
	s.U32.Mul = mulUint32VSXGuarded
	s.U32.Minimum = minimumUint32VSXGuarded
	s.U32.Maximum = maximumUint32VSXGuarded
	s.U32.Abs = absUint32VSXGuarded
	s.U32.Neg = negUint32VSXGuarded
	s.U32.Scale = scaleUint32VSXGuarded
	s.U32.AddScalar = addScalarUint32VSXGuarded
	s.U32.SubScalar = subScalarUint32VSXGuarded
	s.U32.Clamp = clampUint32VSXGuarded
	s.U32.Fill = fillUint32VSXGuarded
	s.U32.Lerp = lerpUint32VSXGuarded
	s.U32.AddScaled = addScaledUint32VSXGuarded
	s.U32.Ramp = rampUint32VSXGuarded
	s.U64.Add = addUint64VSXGuarded
	s.U64.Sub = subUint64VSXGuarded
	s.U64.Minimum = minimumUint64VSXGuarded
	s.U64.Maximum = maximumUint64VSXGuarded
	s.U64.Abs = absUint64VSXGuarded
	s.U64.Neg = negUint64VSXGuarded
	s.U64.AddScalar = addScalarUint64VSXGuarded
	s.U64.SubScalar = subScalarUint64VSXGuarded
	s.U64.Clamp = clampUint64VSXGuarded
	s.U64.Fill = fillUint64VSXGuarded
	s.I32.Shl = shlInt32VSXGuarded
	s.I32.Shr = shrInt32VSXGuarded
	s.I32.Rotl = rotlInt32VSXGuarded
	s.I32.Rotr = rotrInt32VSXGuarded
	s.I64.Shl = shlInt64VSXGuarded
	s.I64.Shr = shrInt64VSXGuarded
	s.I64.Rotl = rotlInt64VSXGuarded
	s.I64.Rotr = rotrInt64VSXGuarded
	s.I8.Shl = shlInt8VSXGuarded
	s.I8.Shr = shrInt8VSXGuarded
	s.I8.Rotl = rotlInt8VSXGuarded
	s.I8.Rotr = rotrInt8VSXGuarded
	s.I16.Shl = shlInt16VSXGuarded
	s.I16.Shr = shrInt16VSXGuarded
	s.I16.Rotl = rotlInt16VSXGuarded
	s.I16.Rotr = rotrInt16VSXGuarded
	s.U8.Shl = shlUint8VSXGuarded
	s.U8.Shr = shrUint8VSXGuarded
	s.U8.Rotl = rotlUint8VSXGuarded
	s.U8.Rotr = rotrUint8VSXGuarded
	s.U16.Shl = shlUint16VSXGuarded
	s.U16.Shr = shrUint16VSXGuarded
	s.U16.Rotl = rotlUint16VSXGuarded
	s.U16.Rotr = rotrUint16VSXGuarded
	s.U32.Shl = shlUint32VSXGuarded
	s.U32.Shr = shrUint32VSXGuarded
	s.U32.Rotl = rotlUint32VSXGuarded
	s.U32.Rotr = rotrUint32VSXGuarded
	s.U64.Shl = shlUint64VSXGuarded
	s.U64.Shr = shrUint64VSXGuarded
	s.U64.Rotl = rotlUint64VSXGuarded
	s.U64.Rotr = rotrUint64VSXGuarded
	s.F32.Div = divFloat32VSXGuarded
	s.F32.DivScalar = divScalarFloat32VSXGuarded
	s.F32.Sqrt = sqrtFloat32VSXGuarded
	s.F32.Reciprocal = reciprocalFloat32VSXGuarded
	s.F32.Floor = floorFloat32VSXGuarded
	s.F32.Ceil = ceilFloat32VSXGuarded
	s.F32.Trunc = truncFloat32VSXGuarded
	s.F32.Round = roundFloat32VSXGuarded
	s.F64.Div = divFloat64VSXGuarded
	s.F64.DivScalar = divScalarFloat64VSXGuarded
	s.F64.Sqrt = sqrtFloat64VSXGuarded
	s.F64.Reciprocal = reciprocalFloat64VSXGuarded
	s.F64.Floor = floorFloat64VSXGuarded
	s.F64.Ceil = ceilFloat64VSXGuarded
	s.F64.Trunc = truncFloat64VSXGuarded
	s.F64.Round = roundFloat64VSXGuarded
	s.I32.SatAdd = satAddInt32VSXGuarded
	s.I32.SatSub = satSubInt32VSXGuarded
	s.I8.SatAdd = satAddInt8VSXGuarded
	s.I8.SatSub = satSubInt8VSXGuarded
	s.I16.SatAdd = satAddInt16VSXGuarded
	s.I16.SatSub = satSubInt16VSXGuarded
	s.U8.SatAdd = satAddUint8VSXGuarded
	s.U8.SatSub = satSubUint8VSXGuarded
	s.U16.SatAdd = satAddUint16VSXGuarded
	s.U16.SatSub = satSubUint16VSXGuarded
	s.U32.SatAdd = satAddUint32VSXGuarded
	s.U32.SatSub = satSubUint32VSXGuarded
}
