// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/blas.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

func RotFloat32VSX(x []float32, y []float32, c float32, s float32) {
	n := min(len(x), len(y))
	if n < 16 {
		ref.RotateFloat(x, y, c, s)
		return
	}
	rotFloat32VSX(x[:n:n], y, c, s)
}

func SwapFloat32VSX(x []float32, y []float32) {
	n := min(len(x), len(y))
	if n < 16 {
		ref.SwapFloat(x, y)
		return
	}
	swapFloat32VSX(x[:n:n], y)
}

func RotFloat64VSX(x []float64, y []float64, c float64, s float64) {
	n := min(len(x), len(y))
	if n < 16 {
		ref.RotateFloat(x, y, c, s)
		return
	}
	rotFloat64VSX(x[:n:n], y, c, s)
}

func SwapFloat64VSX(x []float64, y []float64) {
	n := min(len(x), len(y))
	if n < 16 {
		ref.SwapFloat(x, y)
		return
	}
	swapFloat64VSX(x[:n:n], y)
}

func SwapInt32VSX(x []int32, y []int32) {
	n := min(len(x), len(y))
	if n < 16 {
		ref.SwapInt(x, y)
		return
	}
	swapInt32VSX(x[:n:n], y)
}

func SwapInt64VSX(x []int64, y []int64) {
	n := min(len(x), len(y))
	if n < 16 {
		ref.SwapInt(x, y)
		return
	}
	swapInt64VSX(x[:n:n], y)
}

func registerBlasVSX(s *kernel.Set) {
	s.F32.Rotate = RotFloat32VSX
	s.F32.Swap = SwapFloat32VSX
	s.F64.Rotate = RotFloat64VSX
	s.F64.Swap = SwapFloat64VSX
	s.I32.Swap = SwapInt32VSX
	s.I64.Swap = SwapInt64VSX
}
