// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/bytes.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

func isASCIIVSXGuarded(b []byte) bool {
	if len(b) < 64 {
		return ref.IsASCII(b)
	}
	return isASCIIVSX(b)
}

func indexNonASCII16VSXGuarded(b []uint16) int {
	if len(b) < 64 {
		return ref.IndexNonASCII16(b)
	}
	return indexNonASCII16VSX(b)
}

func widenU8U16VSXGuarded(dst []uint16, s []byte) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.WidenU8U16(dst, s)
		return
	}
	widenU8U16VSX(dst[:n:n], s)
}

func narrowU16U8VSXGuarded(dst []byte, s []uint16) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.NarrowU16U8(dst, s)
		return
	}
	narrowU16U8VSX(dst[:n:n], s)
}

func bitAndVSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAnd(dst, a, b)
		return
	}
	bitAndVSX(dst[:n:n], a, b)
}

func bitOrVSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitOr(dst, a, b)
		return
	}
	bitOrVSX(dst[:n:n], a, b)
}

func bitXorVSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitXor(dst, a, b)
		return
	}
	bitXorVSX(dst[:n:n], a, b)
}

func bitAndNotVSXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAndNot(dst, a, b)
		return
	}
	bitAndNotVSX(dst[:n:n], a, b)
}

func bitNotVSXGuarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.BitNot(dst, b)
		return
	}
	bitNotVSX(dst[:n:n], b)
}

func fillBytesVSXGuarded(dst []byte, v byte) {
	if len(dst) < 32 {
		ref.FillBytes(dst, v)
		return
	}
	fillBytesVSX(dst, v)
}

func hexEncodeVSXGuarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.HexEncode(dst, b)
	}
	return hexEncodeVSX(dst, b)
}

func toUpperASCIIVSXGuarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToUpperASCII(dst, b)
		return
	}
	toUpperASCIIVSX(dst[:n:n], b)
}

func toLowerASCIIVSXGuarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToLowerASCII(dst, b)
		return
	}
	toLowerASCIIVSX(dst[:n:n], b)
}

func replaceByteVSXGuarded(dst []byte, b []byte, old byte, with byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ReplaceByte(dst, b, old, with)
		return
	}
	replaceByteVSX(dst[:n:n], b, old, with)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("vsx")
	s.Bytes.IsASCII = isASCIIVSXGuarded
	s.Bytes.IndexNonASCII16 = indexNonASCII16VSXGuarded
	s.Bytes.WidenU8U16 = widenU8U16VSXGuarded
	s.Bytes.NarrowU16U8 = narrowU16U8VSXGuarded
	s.Bytes.And = bitAndVSXGuarded
	s.Bytes.Or = bitOrVSXGuarded
	s.Bytes.Xor = bitXorVSXGuarded
	s.Bytes.AndNot = bitAndNotVSXGuarded
	s.Bytes.Not = bitNotVSXGuarded
	s.Bytes.Fill = fillBytesVSXGuarded
	s.Bytes.HexEncode = hexEncodeVSXGuarded
	s.Bytes.ToUpperASCII = toUpperASCIIVSXGuarded
	s.Bytes.ToLowerASCII = toLowerASCIIVSXGuarded
	s.Bytes.ReplaceByte = replaceByteVSXGuarded
}
