// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/compare.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

func maskAndVSXGuarded(dst []bool, a []bool, b []bool) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.MaskAnd(dst, a, b)
		return
	}
	maskAndVSX(dst[:n:n], a, b)
}

func maskOrVSXGuarded(dst []bool, a []bool, b []bool) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.MaskOr(dst, a, b)
		return
	}
	maskOrVSX(dst[:n:n], a, b)
}

func maskXorVSXGuarded(dst []bool, a []bool, b []bool) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.MaskXor(dst, a, b)
		return
	}
	maskXorVSX(dst[:n:n], a, b)
}

func maskNotVSXGuarded(dst []bool, a []bool) {
	n := min(len(dst), len(a))
	if n < 32 {
		ref.MaskNot(dst, a)
		return
	}
	maskNotVSX(dst[:n:n], a)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("vsx")
	s.Mask.And = maskAndVSXGuarded
	s.Mask.Or = maskOrVSXGuarded
	s.Mask.Xor = maskXorVSXGuarded
	s.Mask.Not = maskNotVSXGuarded
}
