// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/convert.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

func bf16ToF32VSXGuarded(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.BF16ToF32(dst, a)
		return
	}
	bf16ToF32VSX(dst[:n:n], a)
}

func f32ToBF16VSXGuarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToBF16(dst, a)
		return
	}
	f32ToBF16VSX(dst[:n:n], a)
}

func f16ToF32VSXGuarded(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F16ToF32(dst, a)
		return
	}
	f16ToF32VSX(dst[:n:n], a)
}

func f32ToF16VSXGuarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToF16(dst, a)
		return
	}
	f32ToF16VSX(dst[:n:n], a)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("vsx")
	s.Convert.BF16ToF32 = bf16ToF32VSXGuarded
	s.Convert.F32ToBF16 = f32ToBF16VSXGuarded
	s.Convert.F16ToF32 = f16ToF32VSXGuarded
	s.Convert.F32ToF16 = f32ToF16VSXGuarded
}
