// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/fastmath.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

func fastExpFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Exp(dst, a)
		return
	}
	fastExpFloat32VSX(dst[:n:n], a)
}

func fastExp2Float32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Exp2(dst, a)
		return
	}
	fastExp2Float32VSX(dst[:n:n], a)
}

func fastExpm1Float32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Expm1(dst, a)
		return
	}
	fastExpm1Float32VSX(dst[:n:n], a)
}

func fastLogFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log(dst, a)
		return
	}
	fastLogFloat32VSX(dst[:n:n], a)
}

func fastLog2Float32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log2(dst, a)
		return
	}
	fastLog2Float32VSX(dst[:n:n], a)
}

func fastLog10Float32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log10(dst, a)
		return
	}
	fastLog10Float32VSX(dst[:n:n], a)
}

func fastLog1pFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log1p(dst, a)
		return
	}
	fastLog1pFloat32VSX(dst[:n:n], a)
}

func fastCbrtFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cbrt(dst, a)
		return
	}
	fastCbrtFloat32VSX(dst[:n:n], a)
}

func fastSigmoidFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sigmoid(dst, a)
		return
	}
	fastSigmoidFloat32VSX(dst[:n:n], a)
}

func fastSinFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sin(dst, a)
		return
	}
	fastSinFloat32VSX(dst[:n:n], a)
}

func fastCosFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cos(dst, a)
		return
	}
	fastCosFloat32VSX(dst[:n:n], a)
}

func fastTanFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Tan(dst, a)
		return
	}
	fastTanFloat32VSX(dst[:n:n], a)
}

func fastAsinFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Asin(dst, a)
		return
	}
	fastAsinFloat32VSX(dst[:n:n], a)
}

func fastAcosFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Acos(dst, a)
		return
	}
	fastAcosFloat32VSX(dst[:n:n], a)
}

func fastAtanFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Atan(dst, a)
		return
	}
	fastAtanFloat32VSX(dst[:n:n], a)
}

func fastSinhFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sinh(dst, a)
		return
	}
	fastSinhFloat32VSX(dst[:n:n], a)
}

func fastCoshFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cosh(dst, a)
		return
	}
	fastCoshFloat32VSX(dst[:n:n], a)
}

func fastTanhFloat32VSXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Tanh(dst, a)
		return
	}
	fastTanhFloat32VSX(dst[:n:n], a)
}

func fastAtan2Float32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Atan2(dst, a, b)
		return
	}
	fastAtan2Float32VSX(dst[:n:n], a, b)
}

func fastHypotFloat32VSXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Hypot(dst, a, b)
		return
	}
	fastHypotFloat32VSX(dst[:n:n], a, b)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("vsx")
	s.F32.FastExp = fastExpFloat32VSXGuarded
	s.F32.FastExp2 = fastExp2Float32VSXGuarded
	s.F32.FastExpm1 = fastExpm1Float32VSXGuarded
	s.F32.FastLog = fastLogFloat32VSXGuarded
	s.F32.FastLog2 = fastLog2Float32VSXGuarded
	s.F32.FastLog10 = fastLog10Float32VSXGuarded
	s.F32.FastLog1p = fastLog1pFloat32VSXGuarded
	s.F32.FastCbrt = fastCbrtFloat32VSXGuarded
	s.F32.FastSigmoid = fastSigmoidFloat32VSXGuarded
	s.F32.FastSin = fastSinFloat32VSXGuarded
	s.F32.FastCos = fastCosFloat32VSXGuarded
	s.F32.FastTan = fastTanFloat32VSXGuarded
	s.F32.FastAsin = fastAsinFloat32VSXGuarded
	s.F32.FastAcos = fastAcosFloat32VSXGuarded
	s.F32.FastAtan = fastAtanFloat32VSXGuarded
	s.F32.FastSinh = fastSinhFloat32VSXGuarded
	s.F32.FastCosh = fastCoshFloat32VSXGuarded
	s.F32.FastTanh = fastTanhFloat32VSXGuarded
	s.F32.FastAtan2 = fastAtan2Float32VSXGuarded
	s.F32.FastHypot = fastHypotFloat32VSXGuarded
}
