// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/nary.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

func Add4Float32VSX(dst []float32, a []float32, b []float32, c []float32, d []float32) {
	n := min(len(dst), len(a), len(b), len(c), len(d))
	if n < 256 {
		ref.Add4(dst, a, b, c, d)
		return
	}
	add4Float32VSX(dst[:n:n], a, b, c, d)
}

func Mul4Float32VSX(dst []float32, a []float32, b []float32, c []float32, d []float32) {
	n := min(len(dst), len(a), len(b), len(c), len(d))
	if n < 256 {
		ref.Mul4(dst, a, b, c, d)
		return
	}
	mul4Float32VSX(dst[:n:n], a, b, c, d)
}

func Add4Float64VSX(dst []float64, a []float64, b []float64, c []float64, d []float64) {
	n := min(len(dst), len(a), len(b), len(c), len(d))
	if n < 256 {
		ref.Add4(dst, a, b, c, d)
		return
	}
	add4Float64VSX(dst[:n:n], a, b, c, d)
}

func Mul4Float64VSX(dst []float64, a []float64, b []float64, c []float64, d []float64) {
	n := min(len(dst), len(a), len(b), len(c), len(d))
	if n < 256 {
		ref.Mul4(dst, a, b, c, d)
		return
	}
	mul4Float64VSX(dst[:n:n], a, b, c, d)
}

func Mul4Int8VSX(dst []int8, a []int8, b []int8, c []int8, d []int8) {
	n := min(len(dst), len(a), len(b), len(c), len(d))
	if n < 256 {
		ref.Mul4(dst, a, b, c, d)
		return
	}
	mul4Int8VSX(dst[:n:n], a, b, c, d)
}

func Mul4Uint8VSX(dst []byte, a []byte, b []byte, c []byte, d []byte) {
	n := min(len(dst), len(a), len(b), len(c), len(d))
	if n < 256 {
		ref.Mul4(dst, a, b, c, d)
		return
	}
	mul4Uint8VSX(dst[:n:n], a, b, c, d)
}

func registerNaryVSX(s *kernel.Set) {
	s.F32.Add4 = Add4Float32VSX
	s.F32.Mul4 = Mul4Float32VSX
	s.F64.Add4 = Add4Float64VSX
	s.F64.Mul4 = Mul4Float64VSX
	s.I8.Mul4 = Mul4Int8VSX
	s.U8.Mul4 = Mul4Uint8VSX
}
