// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/nary.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import "runtime"

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

//go:noescape
func add4Float32VSX(dst []float32, a []float32, b []float32, c []float32, d []float32)

//go:noescape
func mul4Float32VSX(dst []float32, a []float32, b []float32, c []float32, d []float32)

//go:noescape
func add4Float64VSX(dst []float64, a []float64, b []float64, c []float64, d []float64)

//go:noescape
func mul4Float64VSX(dst []float64, a []float64, b []float64, c []float64, d []float64)

//go:noescape
func mul3Int8VSX(dst []int8, a []int8, b []int8, c []int8)

//go:noescape
func mul4Int8VSX(dst []int8, a []int8, b []int8, c []int8, d []int8)

//go:noescape
func mul3Uint8VSX(dst []byte, a []byte, b []byte, c []byte)

//go:noescape
func mul4Uint8VSX(dst []byte, a []byte, b []byte, c []byte, d []byte)
