// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/reduce.c
// Target: ppc64le/vsx

//go:build ppc64le && !purego

package ppc64le

import "runtime"

// Compile-time check that this file is only ever built for ppc64le. The build
// constraint above and the _ppc64le filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "ppc64le": {}}

//go:noescape
func sumFloat32VSX(a []float32) float32

//go:noescape
func dotFloat32VSX(a []float32, b []float32) float32

//go:noescape
func sumFloat64VSX(a []float64) float64

//go:noescape
func dotFloat64VSX(a []float64, b []float64) float64
