// Code generated by simdgen. DO NOT EDIT.
//
// Per-operation dispatch tables for ppc64le: static composite literals of
// exported guards and reference functions, one table per flat-group
// operation and one partial Ops struct per (type, tier). Static is the
// contract: an init function here would defeat the linker's dead-code
// elimination for every consumer at once.

//go:build ppc64le && !purego

package simd

import (
	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ppc64le"
	"github.com/sebishogun/simd/internal/ref"
)

// dispatchTiers is the tier order the runtime indexes into; slot 0 is
// the portable reference.
var dispatchTiers = [...]string{"scalar", "vsx"}

var tblBytesIndexAll = [...]func([]int32, []byte, byte) int{
	ref.IndexAll,
	ref.IndexAll,
}

var tblBytesIndexAllAny = [...]func([]int32, []byte, uint64) int{
	ref.IndexAllAny,
	ref.IndexAllAny,
}

var tblBytesRunStartsI32 = [...]func([]bool, []int32){
	ref.RunStartsI32,
	ref.RunStartsI32,
}

var tblBytesRunStartsI64 = [...]func([]bool, []int64){
	ref.RunStartsI64,
	ref.RunStartsI64,
}

var tblBytesRunStartsU8 = [...]func([]bool, []byte){
	ref.RunStartsU8,
	ref.RunStartsU8,
}

var tblBytesAdler32 = [...]func([]byte, uint32) uint32{
	ref.Adler32,
	ref.Adler32,
}

var tblBytesCRC32C = [...]func([]byte, uint32) uint32{
	ref.CRC32C,
	ref.CRC32C,
}

var tblBytesDtoaF64 = [...]func([]byte, float64) int{
	ref.DtoaF64,
	ref.DtoaF64,
}

var tblBytesLZ4BlockDecode = [...]func([]byte, []byte) int{
	ref.LZ4BlockDecode,
	ref.LZ4BlockDecode,
}

var tblBytesHashU64 = [...]func([]uint64, []uint64, uint64){
	ref.HashU64,
	ref.HashU64,
}

var tblBytesRandFillU64 = [...]func([]uint64, uint64){
	ref.RandFillU64,
	ref.RandFillU64,
}

var tblBytesMergeSortedU32 = [...]func([]uint32, []uint32, []uint32) int{
	ref.MergeSortedU32,
	ref.MergeSortedU32,
}

var tblBytesInterleave2U8 = [...]func([]byte, []byte, []byte){
	ref.Interleave2U8,
	ref.Interleave2U8,
}

var tblBytesDeinterleave2U8 = [...]func([]byte, []byte, []byte){
	ref.Deinterleave2U8,
	ref.Deinterleave2U8,
}

var tblBytesBitshuffleU8 = [...]func([]byte, []byte, byte){
	ref.BitshuffleU8,
	ref.BitshuffleU8,
}

var tblBytesTranspose8x8U8 = [...]func([]byte, []byte){
	ref.Transpose8x8U8,
	ref.Transpose8x8U8,
}

var tblBytesBitUnpackFastU32 = [...]func([]uint32, []uint32, int, uint32){
	ref.BitUnpackFastU32,
	ref.BitUnpackFastU32,
}

var tblConvertQMatMulI8 = [...]func([]int32, []int8, []int8, int, int, int){
	ref.QMatMulI8,
	ref.QMatMulI8,
}

var tblConvertRequantizeI8 = [...]func([]int8, []int32, float32, int32){
	ref.RequantizeI8,
	ppc64le.RequantizeI8VSX,
}

var tblBytesRLEDecodeInt32 = [...]func([]int32, []int32, []int32) int{
	ref.RLEDecodeInt32,
	ref.RLEDecodeInt32,
}

var tblMaskAll = [...]func([]bool) bool{
	ref.MaskAll,
	ppc64le.MaskAllVSX,
}

var tblMaskAny = [...]func([]bool) bool{
	ref.MaskAny,
	ppc64le.MaskAnyVSX,
}

var tblMaskCount = [...]func([]bool) int{
	ref.MaskCount,
	ref.MaskCount,
}

var tblMaskAnd = [...]func([]bool, []bool, []bool){
	ref.MaskAnd,
	ppc64le.MaskAndVSX,
}

var tblMaskOr = [...]func([]bool, []bool, []bool){
	ref.MaskOr,
	ppc64le.MaskOrVSX,
}

var tblMaskXor = [...]func([]bool, []bool, []bool){
	ref.MaskXor,
	ppc64le.MaskXorVSX,
}

var tblMaskNot = [...]func([]bool, []bool){
	ref.MaskNot,
	ppc64le.MaskNotVSX,
}

var tblBytesCount = [...]func([]byte, byte) int{
	ref.CountByte,
	ref.CountByte,
}

var tblBytesIndexByte = [...]func([]byte, byte) int{
	ref.IndexByte,
	ref.IndexByte,
}

var tblBytesLastIndexByte = [...]func([]byte, byte) int{
	ref.LastIndexByte,
	ref.LastIndexByte,
}

var tblBytesPopCount = [...]func([]byte) int{
	ref.PopCount,
	ref.PopCount,
}

var tblBytesMaskBits = [...]func([]byte, []byte, byte){
	ref.MaskBits,
	ref.MaskBits,
}

var tblBytesMaskBitsLess = [...]func([]byte, []byte, byte){
	ref.MaskBitsLess,
	ref.MaskBitsLess,
}

var tblBytesMaskBitsAny4 = [...]func([]byte, []byte, uint32){
	ref.MaskBitsAny4,
	ref.MaskBitsAny4,
}

var tblBytesMaskBitsAny = [...]func([]byte, []byte, uint64){
	ref.MaskBitsAny,
	ref.MaskBitsAny,
}

var tblBytesHamming = [...]func([]byte, []byte) int{
	ref.Hamming,
	ref.Hamming,
}

var tblBytesHammingWords = [...]func([]uint64, []uint64) int{
	ref.HammingWords,
	ref.HammingWords,
}

var tblBytesGrayscale = [...]func([]byte, []byte, []byte, []byte){
	ref.Grayscale,
	ppc64le.GrayscaleU8VSX,
}

var tblBytesRGBToUV = [...]func([]byte, []byte, []byte, []byte, []byte){
	ref.RGBToUV,
	ref.RGBToUV,
}

var tblBytesIsASCII = [...]func([]byte) bool{
	ref.IsASCII,
	ppc64le.IsASCIIVSX,
}

var tblBytesValidUTF8 = [...]func([]byte) bool{
	ref.ValidUTF8,
	ppc64le.ValidUTF8VSX,
}

var tblBytesIndexNonASCII = [...]func([]byte) int{
	ref.IndexNonASCII,
	ref.IndexNonASCII,
}

var tblBytesIndexNonASCII16 = [...]func([]uint16) int{
	ref.IndexNonASCII16,
	ppc64le.IndexNonASCII16VSX,
}

var tblBytesWidenU8U16 = [...]func([]uint16, []byte){
	ref.WidenU8U16,
	ppc64le.WidenU8U16VSX,
}

var tblBytesNarrowU16U8 = [...]func([]byte, []uint16){
	ref.NarrowU16U8,
	ppc64le.NarrowU16U8VSX,
}

var tblBytesWidenU8U32 = [...]func([]uint32, []byte){
	ref.WidenU8U32,
	ref.WidenU8U32,
}

var tblBytesNarrowU32U8 = [...]func([]byte, []uint32){
	ref.NarrowU32U8,
	ppc64le.NarrowU32U8VSX,
}

var tblBytesEqual = [...]func([]byte, []byte) bool{
	ref.EqualBytes,
	ref.EqualBytes,
}

var tblBytesAnd = [...]func([]byte, []byte, []byte){
	ref.BitAnd,
	ppc64le.BitAndVSX,
}

var tblBytesOr = [...]func([]byte, []byte, []byte){
	ref.BitOr,
	ppc64le.BitOrVSX,
}

var tblBytesXor = [...]func([]byte, []byte, []byte){
	ref.BitXor,
	ppc64le.BitXorVSX,
}

var tblBytesAndNot = [...]func([]byte, []byte, []byte){
	ref.BitAndNot,
	ppc64le.BitAndNotVSX,
}

var tblBytesNot = [...]func([]byte, []byte){
	ref.BitNot,
	ppc64le.BitNotVSX,
}

var tblBytesFill = [...]func([]byte, byte){
	ref.FillBytes,
	ppc64le.FillBytesVSX,
}

var tblBytesCompare = [...]func([]byte, []byte) int{
	ref.CompareBytes,
	ref.CompareBytes,
}

var tblBytesCommonPrefix = [...]func([]byte, []byte) int{
	ref.CommonPrefix,
	ref.CommonPrefix,
}

var tblBytesEqualFoldASCII = [...]func([]byte, []byte) bool{
	ref.EqualFoldASCII,
	ref.EqualFoldASCII,
}

var tblBytesIndexAny = [...]func([]byte, []byte) int{
	ref.IndexAny,
	ref.IndexAny,
}

var tblBytesIndexAnyOrLess = [...]func([]byte, []byte, byte) int{
	ref.IndexAnyOrLess,
	ref.IndexAnyOrLess,
}

var tblBytesIndexNotAny = [...]func([]byte, []byte) int{
	ref.IndexNotAny,
	ref.IndexNotAny,
}

var tblBytesLastIndexNotAny = [...]func([]byte, []byte) int{
	ref.LastIndexNotAny,
	ref.LastIndexNotAny,
}

var tblBytesCountAny = [...]func([]byte, []byte) int{
	ref.CountAny,
	ref.CountAny,
}

var tblBytesJSONMasks = [...]func([]byte, []byte, uint32){
	ref.JSONMasks,
	ref.JSONMasks,
}

var tblBytesJSONValidTokens = [...]func([]byte, []uint64, []uint64) int{
	ref.JSONValidTokens,
	ref.JSONValidTokens,
}

var tblBytesJSONValid = [...]func([]byte, []uint64) int{
	ref.JSONValid,
	ref.JSONValid,
}

var tblBytesJSONStage1 = [...]func([]uint64, []byte, int, []uint64, []int64){
	ref.JSONStage1,
	ref.JSONStage1,
}

var tblBytesJSONCopyValid = [...]func([]byte, []byte, byte) int{
	ref.JSONCopyValid,
	ref.JSONCopyValid,
}

var tblBytesJSONQuote = [...]func([]byte, []byte, byte) int{
	ref.JSONQuote,
	ref.JSONQuote,
}

var tblBytesJSONCopyRun = [...]func([]byte, []byte, byte) int{
	ref.JSONCopyRun,
	ref.JSONCopyRun,
}

var tblBytesB64Encode = [...]func([]byte, []byte) int{
	ref.B64Encode,
	ref.B64Encode,
}

var tblBytesB64Decode = [...]func([]byte, []byte) int{
	ref.B64Decode,
	ref.B64Decode,
}

var tblBytesParseInts = [...]func([]int64, []byte, []int32) (int, bool){
	ref.ParseInts,
	ref.ParseInts,
}

var tblBytesParseUints = [...]func([]uint64, []byte, []int32) (int, bool){
	ref.ParseUints,
	ref.ParseUints,
}

var tblBytesFormatInts = [...]func([]byte, []int64, byte) int{
	ref.FormatInts,
	ref.FormatInts,
}

var tblBytesHexDecode = [...]func([]byte, []byte) (int, bool){
	ref.HexDecode,
	ref.HexDecode,
}

var tblBytesHexEncode = [...]func([]byte, []byte) int{
	ref.HexEncode,
	ppc64le.HexEncodeVSX,
}

var tblBytesIndex = [...]func([]byte, []byte) int{
	ref.Index,
	ref.Index,
}

var tblBytesLastIndex = [...]func([]byte, []byte) int{
	ref.LastIndex,
	ref.LastIndex,
}

var tblBytesCountSeq = [...]func([]byte, []byte) int{
	ref.CountSeq,
	ref.CountSeq,
}

var tblBytesToUpperASCII = [...]func([]byte, []byte){
	ref.ToUpperASCII,
	ppc64le.ToUpperASCIIVSX,
}

var tblBytesToLowerASCII = [...]func([]byte, []byte){
	ref.ToLowerASCII,
	ppc64le.ToLowerASCIIVSX,
}

var tblBytesReplaceByte = [...]func([]byte, []byte, byte, byte){
	ref.ReplaceByte,
	ppc64le.ReplaceByteVSX,
}

var tblConvertQuantizeI8 = [...]func([]int8, []float32, float32, int32){
	ref.QuantizeI8,
	ppc64le.QuantizeI8VSX,
}

var tblConvertDequantizeI8 = [...]func([]float32, []int8, float32, int32){
	ref.DequantizeI8,
	ref.DequantizeI8,
}

var tblConvertQuantizeU8 = [...]func([]byte, []float32, float32, int32){
	ref.QuantizeU8,
	ppc64le.QuantizeU8VSX,
}

var tblConvertDequantizeU8 = [...]func([]float32, []byte, float32, int32){
	ref.DequantizeU8,
	ref.DequantizeU8,
}

var tblConvertQuantizePerChannelI8 = [...]func([]int8, []float32, []float32, []int32, int, int){
	ref.QuantizePerChannelI8,
	ref.QuantizePerChannelI8,
}

var tblConvertQuantizePerChannelU8 = [...]func([]byte, []float32, []float32, []int32, int, int){
	ref.QuantizePerChannelU8,
	ref.QuantizePerChannelU8,
}

var tblConvertDequantizePerChannelI8 = [...]func([]float32, []int8, []float32, []int32, int, int){
	ref.DequantizePerChannelI8,
	ref.DequantizePerChannelI8,
}

var tblConvertDequantizePerChannelU8 = [...]func([]float32, []byte, []float32, []int32, int, int){
	ref.DequantizePerChannelU8,
	ref.DequantizePerChannelU8,
}

var tblConvertZigzagEncodeI8 = [...]func([]byte, []int8){
	ref.ZigzagEncodeI8,
	ppc64le.ZigzagEncodeI8VSX,
}

var tblConvertZigzagDecodeI8 = [...]func([]int8, []byte){
	ref.ZigzagDecodeI8,
	ppc64le.ZigzagDecodeI8VSX,
}

var tblConvertZigzagEncodeI16 = [...]func([]uint16, []int16){
	ref.ZigzagEncodeI16,
	ppc64le.ZigzagEncodeI16VSX,
}

var tblConvertZigzagDecodeI16 = [...]func([]int16, []uint16){
	ref.ZigzagDecodeI16,
	ppc64le.ZigzagDecodeI16VSX,
}

var tblConvertZigzagEncodeI32 = [...]func([]uint32, []int32){
	ref.ZigzagEncodeI32,
	ppc64le.ZigzagEncodeI32VSX,
}

var tblConvertZigzagDecodeI32 = [...]func([]int32, []uint32){
	ref.ZigzagDecodeI32,
	ppc64le.ZigzagDecodeI32VSX,
}

var tblConvertZigzagEncodeI64 = [...]func([]uint64, []int64){
	ref.ZigzagEncodeI64,
	ppc64le.ZigzagEncodeI64VSX,
}

var tblConvertZigzagDecodeI64 = [...]func([]int64, []uint64){
	ref.ZigzagDecodeI64,
	ppc64le.ZigzagDecodeI64VSX,
}

var tblConvertVarintLenU32 = [...]func([]int32, []uint32){
	ref.VarintLenU32,
	ppc64le.VarintLenU32VSX,
}

var tblConvertVarintLenU64 = [...]func([]int32, []uint64){
	ref.VarintLenU64,
	ppc64le.VarintLenU64VSX,
}

var tblConvertVarintSizeU32 = [...]func([]uint32) int{
	ref.VarintSizeU32,
	ppc64le.VarintSizeU32VSX,
}

var tblConvertVarintSizeU64 = [...]func([]uint64) int{
	ref.VarintSizeU64,
	ref.VarintSizeU64,
}

var tblConvertBitPackU32 = [...]func([]uint32, []uint32, int32){
	ref.BitPackU32,
	ref.BitPackU32,
}

var tblConvertBitUnpackU32 = [...]func([]uint32, []uint32, int32){
	ref.BitUnpackU32,
	ref.BitUnpackU32,
}

var tblConvertF8E4M3ToF32 = [...]func([]float32, []byte){
	ref.F8E4M3ToF32,
	ref.F8E4M3ToF32,
}

var tblConvertF32ToF8E4M3 = [...]func([]byte, []float32){
	ref.F32ToF8E4M3,
	ref.F32ToF8E4M3,
}

var tblConvertF8E5M2ToF32 = [...]func([]float32, []byte){
	ref.F8E5M2ToF32,
	ref.F8E5M2ToF32,
}

var tblConvertF32ToF8E5M2 = [...]func([]byte, []float32){
	ref.F32ToF8E5M2,
	ref.F32ToF8E5M2,
}

var tblConvertBF16ToF32 = [...]func([]float32, []uint16){
	ref.BF16ToF32,
	ppc64le.Bf16ToF32VSX,
}

var tblConvertF32ToBF16 = [...]func([]uint16, []float32){
	ref.F32ToBF16,
	ppc64le.F32ToBF16VSX,
}

var tblConvertF16ToF32 = [...]func([]float32, []uint16){
	ref.F16ToF32,
	ppc64le.F16ToF32VSX,
}

var tblConvertF32ToF16 = [...]func([]uint16, []float32){
	ref.F32ToF16,
	ppc64le.F32ToF16VSX,
}

var tblBytesVarintDecodeU64 = [...]func([]uint64, []byte) (int, int){
	ref.VarintDecodeU64,
	ref.VarintDecodeU64,
}

var opsF32VSX = kernel.Ops[float32]{
	Rotate:                 ppc64le.RotFloat32VSX,
	Swap:                   ppc64le.SwapFloat32VSX,
	SumValid:               ppc64le.SumValidFloat32VSX,
	Add4:                   ppc64le.Add4Float32VSX,
	Mul4:                   ppc64le.Mul4Float32VSX,
	MinMax:                 ppc64le.MinMaxFloat32VSX,
	FastCumProd:            ppc64le.FastCumProdFloat32VSX,
	FastCumSum:             ppc64le.FastCumSumFloat32VSX,
	Add:                    ppc64le.AddFloat32VSX,
	Sub:                    ppc64le.SubFloat32VSX,
	Mul:                    ppc64le.MulFloat32VSX,
	Minimum:                ppc64le.MinimumFloat32VSX,
	Maximum:                ppc64le.MaximumFloat32VSX,
	Abs:                    ppc64le.AbsFloat32VSX,
	Neg:                    ppc64le.NegFloat32VSX,
	Scale:                  ppc64le.ScaleFloat32VSX,
	AddScalar:              ppc64le.AddScalarFloat32VSX,
	SubScalar:              ppc64le.SubScalarFloat32VSX,
	Clamp:                  ppc64le.ClampFloat32VSX,
	Fill:                   ppc64le.FillFloat32VSX,
	Lerp:                   ppc64le.LerpFloat32VSX,
	AddScaled:              ppc64le.AddScaledFloat32VSX,
	Ramp:                   ppc64le.RampFloat32VSX,
	Div:                    ppc64le.DivFloat32VSX,
	DivScalar:              ppc64le.DivScalarFloat32VSX,
	Sqrt:                   ppc64le.SqrtFloat32VSX,
	Reciprocal:             ppc64le.ReciprocalFloat32VSX,
	Floor:                  ppc64le.FloorFloat32VSX,
	Ceil:                   ppc64le.CeilFloat32VSX,
	Trunc:                  ppc64le.TruncFloat32VSX,
	Round:                  ppc64le.RoundFloat32VSX,
	Min:                    ppc64le.MinrFloat32VSX,
	Max:                    ppc64le.MaxrFloat32VSX,
	Diff:                   ppc64le.DiffFloat32VSX,
	Sum:                    ppc64le.SumFloat32VSX,
	Dot:                    ppc64le.DotFloat32VSX,
	SumLanes:               ppc64le.SumLanesFloat32VSX,
	EqualMask:              ppc64le.EqFloat32MaskVSX,
	EqualScalarMask:        ppc64le.EqScalarFloat32MaskVSX,
	NotEqualMask:           ppc64le.NeFloat32MaskVSX,
	NotEqualScalarMask:     ppc64le.NeScalarFloat32MaskVSX,
	LessMask:               ppc64le.LtFloat32MaskVSX,
	LessScalarMask:         ppc64le.LtScalarFloat32MaskVSX,
	LessEqualMask:          ppc64le.LeFloat32MaskVSX,
	LessEqualScalarMask:    ppc64le.LeScalarFloat32MaskVSX,
	GreaterMask:            ppc64le.GtFloat32MaskVSX,
	GreaterScalarMask:      ppc64le.GtScalarFloat32MaskVSX,
	GreaterEqualMask:       ppc64le.GeFloat32MaskVSX,
	GreaterEqualScalarMask: ppc64le.GeScalarFloat32MaskVSX,
	Exp:                    ppc64le.ExpFloat32VSX,
	Exp2:                   ppc64le.Exp2Float32VSX,
	Expm1:                  ppc64le.Expm1Float32VSX,
	Log:                    ppc64le.LogFloat32VSX,
	Log2:                   ppc64le.Log2Float32VSX,
	Log10:                  ppc64le.Log10Float32VSX,
	Log1p:                  ppc64le.Log1pFloat32VSX,
	Cbrt:                   ppc64le.CbrtFloat32VSX,
	Sigmoid:                ppc64le.SigmoidFloat32VSX,
	Sin:                    ppc64le.SinFloat32VSX,
	Cos:                    ppc64le.CosFloat32VSX,
	Tan:                    ppc64le.TanFloat32VSX,
	Asin:                   ppc64le.AsinFloat32VSX,
	Acos:                   ppc64le.AcosFloat32VSX,
	Atan:                   ppc64le.AtanFloat32VSX,
	Sinh:                   ppc64le.SinhFloat32VSX,
	Cosh:                   ppc64le.CoshFloat32VSX,
	Tanh:                   ppc64le.TanhFloat32VSX,
	Asinh:                  ppc64le.AsinhFloat32VSX,
	Acosh:                  ppc64le.AcoshFloat32VSX,
	Atanh:                  ppc64le.AtanhFloat32VSX,
	Erf:                    ppc64le.ErfFloat32VSX,
	Pow:                    ppc64le.PowFloat32VSX,
	Atan2:                  ppc64le.Atan2Float32VSX,
	Hypot:                  ppc64le.HypotFloat32VSX,
	Norm:                   ppc64le.NormFloat32VSX,
	ShiftDiv:               ppc64le.ShiftDivFloat32VSX,
	LayerNorm:              ppc64le.LayerNormFloat32VSX,
	FastExp:                ppc64le.FastExpFloat32VSX,
	FastExp2:               ppc64le.FastExp2Float32VSX,
	FastExpm1:              ppc64le.FastExpm1Float32VSX,
	FastLog:                ppc64le.FastLogFloat32VSX,
	FastLog2:               ppc64le.FastLog2Float32VSX,
	FastLog10:              ppc64le.FastLog10Float32VSX,
	FastLog1p:              ppc64le.FastLog1pFloat32VSX,
	FastCbrt:               ppc64le.FastCbrtFloat32VSX,
	FastSigmoid:            ppc64le.FastSigmoidFloat32VSX,
	FastSin:                ppc64le.FastSinFloat32VSX,
	FastCos:                ppc64le.FastCosFloat32VSX,
	FastTan:                ppc64le.FastTanFloat32VSX,
	FastAsin:               ppc64le.FastAsinFloat32VSX,
	FastAcos:               ppc64le.FastAcosFloat32VSX,
	FastAtan:               ppc64le.FastAtanFloat32VSX,
	FastSinh:               ppc64le.FastSinhFloat32VSX,
	FastCosh:               ppc64le.FastCoshFloat32VSX,
	FastTanh:               ppc64le.FastTanhFloat32VSX,
	FastAsinh:              ppc64le.FastAsinhFloat32VSX,
	FastAcosh:              ppc64le.FastAcoshFloat32VSX,
	FastAtanh:              ppc64le.FastAtanhFloat32VSX,
	FastErf:                ppc64le.FastErfFloat32VSX,
	FastPow:                ppc64le.FastPowFloat32VSX,
	FastAtan2:              ppc64le.FastAtan2Float32VSX,
	FastHypot:              ppc64le.FastHypotFloat32VSX,
}

var opsF32ByTier = [...]*kernel.Ops[float32]{
	nil,
	&opsF32VSX,
}

var opsF64VSX = kernel.Ops[float64]{
	Rotate:      ppc64le.RotFloat64VSX,
	Swap:        ppc64le.SwapFloat64VSX,
	Add4:        ppc64le.Add4Float64VSX,
	Mul4:        ppc64le.Mul4Float64VSX,
	MinMax:      ppc64le.MinMaxFloat64VSX,
	FastCumProd: ppc64le.FastCumProdFloat64VSX,
	Add:         ppc64le.AddFloat64VSX,
	Sub:         ppc64le.SubFloat64VSX,
	Mul:         ppc64le.MulFloat64VSX,
	Minimum:     ppc64le.MinimumFloat64VSX,
	Maximum:     ppc64le.MaximumFloat64VSX,
	Abs:         ppc64le.AbsFloat64VSX,
	Neg:         ppc64le.NegFloat64VSX,
	Scale:       ppc64le.ScaleFloat64VSX,
	AddScalar:   ppc64le.AddScalarFloat64VSX,
	SubScalar:   ppc64le.SubScalarFloat64VSX,
	Clamp:       ppc64le.ClampFloat64VSX,
	Fill:        ppc64le.FillFloat64VSX,
	Lerp:        ppc64le.LerpFloat64VSX,
	AddScaled:   ppc64le.AddScaledFloat64VSX,
	Ramp:        ppc64le.RampFloat64VSX,
	Div:         ppc64le.DivFloat64VSX,
	DivScalar:   ppc64le.DivScalarFloat64VSX,
	Sqrt:        ppc64le.SqrtFloat64VSX,
	Reciprocal:  ppc64le.ReciprocalFloat64VSX,
	Floor:       ppc64le.FloorFloat64VSX,
	Ceil:        ppc64le.CeilFloat64VSX,
	Trunc:       ppc64le.TruncFloat64VSX,
	Round:       ppc64le.RoundFloat64VSX,
	Min:         ppc64le.MinrFloat64VSX,
	Max:         ppc64le.MaxrFloat64VSX,
	SumSquares:  ppc64le.SumsqFloat64VSX,
	SumSqDev:    ppc64le.SumsqdevFloat64VSX,
	Sum:         ppc64le.SumFloat64VSX,
	Dot:         ppc64le.DotFloat64VSX,
	L1Norm:      ppc64le.L1normFloat64VSX,
	SumLanes:    ppc64le.SumLanesFloat64VSX,
	Exp:         ppc64le.ExpFloat64VSX,
	Exp2:        ppc64le.Exp2Float64VSX,
	Expm1:       ppc64le.Expm1Float64VSX,
	Log:         ppc64le.LogFloat64VSX,
	Log2:        ppc64le.Log2Float64VSX,
	Log10:       ppc64le.Log10Float64VSX,
	Log1p:       ppc64le.Log1pFloat64VSX,
	Cbrt:        ppc64le.CbrtFloat64VSX,
	Sigmoid:     ppc64le.SigmoidFloat64VSX,
	Sin:         ppc64le.SinFloat64VSX,
	Cos:         ppc64le.CosFloat64VSX,
	Tan:         ppc64le.TanFloat64VSX,
	Asin:        ppc64le.AsinFloat64VSX,
	Acos:        ppc64le.AcosFloat64VSX,
	Atan:        ppc64le.AtanFloat64VSX,
	Sinh:        ppc64le.SinhFloat64VSX,
	Cosh:        ppc64le.CoshFloat64VSX,
	Tanh:        ppc64le.TanhFloat64VSX,
	Asinh:       ppc64le.AsinhFloat64VSX,
	Acosh:       ppc64le.AcoshFloat64VSX,
	Atanh:       ppc64le.AtanhFloat64VSX,
	Erf:         ppc64le.ErfFloat64VSX,
	Atan2:       ppc64le.Atan2Float64VSX,
	Hypot:       ppc64le.HypotFloat64VSX,
	Norm:        ppc64le.NormFloat64VSX,
	ShiftDiv:    ppc64le.ShiftDivFloat64VSX,
	LayerNorm:   ppc64le.LayerNormFloat64VSX,
	FastExp:     ppc64le.FastExpFloat64VSX,
	FastExp2:    ppc64le.FastExp2Float64VSX,
	FastExpm1:   ppc64le.FastExpm1Float64VSX,
	FastLog:     ppc64le.FastLogFloat64VSX,
	FastLog2:    ppc64le.FastLog2Float64VSX,
	FastLog10:   ppc64le.FastLog10Float64VSX,
	FastLog1p:   ppc64le.FastLog1pFloat64VSX,
	FastCbrt:    ppc64le.FastCbrtFloat64VSX,
	FastSigmoid: ppc64le.FastSigmoidFloat64VSX,
	FastSin:     ppc64le.FastSinFloat64VSX,
	FastCos:     ppc64le.FastCosFloat64VSX,
	FastTan:     ppc64le.FastTanFloat64VSX,
	FastAsin:    ppc64le.FastAsinFloat64VSX,
	FastAcos:    ppc64le.FastAcosFloat64VSX,
	FastAtan:    ppc64le.FastAtanFloat64VSX,
	FastSinh:    ppc64le.FastSinhFloat64VSX,
	FastCosh:    ppc64le.FastCoshFloat64VSX,
	FastTanh:    ppc64le.FastTanhFloat64VSX,
	FastAsinh:   ppc64le.FastAsinhFloat64VSX,
	FastAcosh:   ppc64le.FastAcoshFloat64VSX,
	FastAtanh:   ppc64le.FastAtanhFloat64VSX,
	FastErf:     ppc64le.FastErfFloat64VSX,
	FastAtan2:   ppc64le.FastAtan2Float64VSX,
	FastHypot:   ppc64le.FastHypotFloat64VSX,
}

var opsF64ByTier = [...]*kernel.Ops[float64]{
	nil,
	&opsF64VSX,
}

var opsI16VSX = kernel.Ops[int16]{
	Add:                    ppc64le.AddInt16VSX,
	Sub:                    ppc64le.SubInt16VSX,
	Mul:                    ppc64le.MulInt16VSX,
	Minimum:                ppc64le.MinimumInt16VSX,
	Maximum:                ppc64le.MaximumInt16VSX,
	Abs:                    ppc64le.AbsInt16VSX,
	Neg:                    ppc64le.NegInt16VSX,
	Scale:                  ppc64le.ScaleInt16VSX,
	AddScalar:              ppc64le.AddScalarInt16VSX,
	SubScalar:              ppc64le.SubScalarInt16VSX,
	Clamp:                  ppc64le.ClampInt16VSX,
	Fill:                   ppc64le.FillInt16VSX,
	Lerp:                   ppc64le.LerpInt16VSX,
	AddScaled:              ppc64le.AddScaledInt16VSX,
	Ramp:                   ppc64le.RampInt16VSX,
	Shl:                    ppc64le.ShlInt16VSX,
	Shr:                    ppc64le.ShrInt16VSX,
	Rotl:                   ppc64le.RotlInt16VSX,
	Rotr:                   ppc64le.RotrInt16VSX,
	OnesCount:              ppc64le.OnesCountInt16VSX,
	LeadingZeros:           ppc64le.LeadingZerosInt16VSX,
	TrailingZeros:          ppc64le.TrailingZerosInt16VSX,
	ByteSwap:               ppc64le.ByteSwapInt16VSX,
	SatAdd:                 ppc64le.SatAddInt16VSX,
	SatSub:                 ppc64le.SatSubInt16VSX,
	Min:                    ppc64le.MinrInt16VSX,
	Max:                    ppc64le.MaxrInt16VSX,
	SumSquares:             ppc64le.SumsqInt16VSX,
	SumSqDev:               ppc64le.SumsqdevInt16VSX,
	SumSqDiff:              ppc64le.SumsqdiffInt16VSX,
	Diff:                   ppc64le.DiffInt16VSX,
	Sum:                    ppc64le.SumInt16VSX,
	Prod:                   ppc64le.ProdInt16VSX,
	Dot:                    ppc64le.DotInt16VSX,
	L1Norm:                 ppc64le.L1normInt16VSX,
	L1Diff:                 ppc64le.L1diffInt16VSX,
	EqualMask:              ppc64le.EqInt16MaskVSX,
	EqualScalarMask:        ppc64le.EqScalarInt16MaskVSX,
	NotEqualMask:           ppc64le.NeInt16MaskVSX,
	NotEqualScalarMask:     ppc64le.NeScalarInt16MaskVSX,
	LessMask:               ppc64le.LtInt16MaskVSX,
	LessScalarMask:         ppc64le.LtScalarInt16MaskVSX,
	LessEqualMask:          ppc64le.LeInt16MaskVSX,
	LessEqualScalarMask:    ppc64le.LeScalarInt16MaskVSX,
	GreaterMask:            ppc64le.GtInt16MaskVSX,
	GreaterScalarMask:      ppc64le.GtScalarInt16MaskVSX,
	GreaterEqualMask:       ppc64le.GeInt16MaskVSX,
	GreaterEqualScalarMask: ppc64le.GeScalarInt16MaskVSX,
}

var opsI16ByTier = [...]*kernel.Ops[int16]{
	nil,
	&opsI16VSX,
}

var opsI32VSX = kernel.Ops[int32]{
	Swap:                   ppc64le.SwapInt32VSX,
	SumValid:               ppc64le.SumValidInt32VSX,
	ArgMin:                 ppc64le.ArgMinInt32VSX,
	ArgMax:                 ppc64le.ArgMaxInt32VSX,
	CumMin:                 ppc64le.CumMinInt32VSX,
	CumMax:                 ppc64le.CumMaxInt32VSX,
	CumProd:                ppc64le.CumProdInt32VSX,
	Add:                    ppc64le.AddInt32VSX,
	Sub:                    ppc64le.SubInt32VSX,
	Mul:                    ppc64le.MulInt32VSX,
	Minimum:                ppc64le.MinimumInt32VSX,
	Maximum:                ppc64le.MaximumInt32VSX,
	Abs:                    ppc64le.AbsInt32VSX,
	Neg:                    ppc64le.NegInt32VSX,
	Scale:                  ppc64le.ScaleInt32VSX,
	AddScalar:              ppc64le.AddScalarInt32VSX,
	SubScalar:              ppc64le.SubScalarInt32VSX,
	Clamp:                  ppc64le.ClampInt32VSX,
	Fill:                   ppc64le.FillInt32VSX,
	Lerp:                   ppc64le.LerpInt32VSX,
	AddScaled:              ppc64le.AddScaledInt32VSX,
	Ramp:                   ppc64le.RampInt32VSX,
	Shl:                    ppc64le.ShlInt32VSX,
	Shr:                    ppc64le.ShrInt32VSX,
	Rotl:                   ppc64le.RotlInt32VSX,
	Rotr:                   ppc64le.RotrInt32VSX,
	OnesCount:              ppc64le.OnesCountInt32VSX,
	LeadingZeros:           ppc64le.LeadingZerosInt32VSX,
	TrailingZeros:          ppc64le.TrailingZerosInt32VSX,
	ByteSwap:               ppc64le.ByteSwapInt32VSX,
	SatAdd:                 ppc64le.SatAddInt32VSX,
	SatSub:                 ppc64le.SatSubInt32VSX,
	Min:                    ppc64le.MinrInt32VSX,
	Max:                    ppc64le.MaxrInt32VSX,
	SumSquares:             ppc64le.SumsqInt32VSX,
	SumSqDev:               ppc64le.SumsqdevInt32VSX,
	SumSqDiff:              ppc64le.SumsqdiffInt32VSX,
	Diff:                   ppc64le.DiffInt32VSX,
	Sum:                    ppc64le.SumInt32VSX,
	Prod:                   ppc64le.ProdInt32VSX,
	Dot:                    ppc64le.DotInt32VSX,
	L1Norm:                 ppc64le.L1normInt32VSX,
	L1Diff:                 ppc64le.L1diffInt32VSX,
	EqualMask:              ppc64le.EqInt32MaskVSX,
	EqualScalarMask:        ppc64le.EqScalarInt32MaskVSX,
	NotEqualMask:           ppc64le.NeInt32MaskVSX,
	NotEqualScalarMask:     ppc64le.NeScalarInt32MaskVSX,
	LessMask:               ppc64le.LtInt32MaskVSX,
	LessScalarMask:         ppc64le.LtScalarInt32MaskVSX,
	LessEqualMask:          ppc64le.LeInt32MaskVSX,
	LessEqualScalarMask:    ppc64le.LeScalarInt32MaskVSX,
	GreaterMask:            ppc64le.GtInt32MaskVSX,
	GreaterScalarMask:      ppc64le.GtScalarInt32MaskVSX,
	GreaterEqualMask:       ppc64le.GeInt32MaskVSX,
	GreaterEqualScalarMask: ppc64le.GeScalarInt32MaskVSX,
}

var opsI32ByTier = [...]*kernel.Ops[int32]{
	nil,
	&opsI32VSX,
}

var opsI64VSX = kernel.Ops[int64]{
	Swap:          ppc64le.SwapInt64VSX,
	SumValid:      ppc64le.SumValidInt64VSX,
	ArgMin:        ppc64le.ArgMinInt64VSX,
	ArgMax:        ppc64le.ArgMaxInt64VSX,
	CumMin:        ppc64le.CumMinInt64VSX,
	CumMax:        ppc64le.CumMaxInt64VSX,
	Add:           ppc64le.AddInt64VSX,
	Sub:           ppc64le.SubInt64VSX,
	Minimum:       ppc64le.MinimumInt64VSX,
	Maximum:       ppc64le.MaximumInt64VSX,
	Abs:           ppc64le.AbsInt64VSX,
	Neg:           ppc64le.NegInt64VSX,
	AddScalar:     ppc64le.AddScalarInt64VSX,
	SubScalar:     ppc64le.SubScalarInt64VSX,
	Clamp:         ppc64le.ClampInt64VSX,
	Fill:          ppc64le.FillInt64VSX,
	Shl:           ppc64le.ShlInt64VSX,
	Shr:           ppc64le.ShrInt64VSX,
	Rotl:          ppc64le.RotlInt64VSX,
	Rotr:          ppc64le.RotrInt64VSX,
	OnesCount:     ppc64le.OnesCountInt64VSX,
	LeadingZeros:  ppc64le.LeadingZerosInt64VSX,
	TrailingZeros: ppc64le.TrailingZerosInt64VSX,
	ByteSwap:      ppc64le.ByteSwapInt64VSX,
	Min:           ppc64le.MinrInt64VSX,
	Max:           ppc64le.MaxrInt64VSX,
	Sum:           ppc64le.SumInt64VSX,
	L1Norm:        ppc64le.L1normInt64VSX,
	L1Diff:        ppc64le.L1diffInt64VSX,
}

var opsI64ByTier = [...]*kernel.Ops[int64]{
	nil,
	&opsI64VSX,
}

var opsI8VSX = kernel.Ops[int8]{
	Mul4:                   ppc64le.Mul4Int8VSX,
	Add:                    ppc64le.AddInt8VSX,
	Sub:                    ppc64le.SubInt8VSX,
	Mul:                    ppc64le.MulInt8VSX,
	Minimum:                ppc64le.MinimumInt8VSX,
	Maximum:                ppc64le.MaximumInt8VSX,
	Abs:                    ppc64le.AbsInt8VSX,
	Neg:                    ppc64le.NegInt8VSX,
	Scale:                  ppc64le.ScaleInt8VSX,
	AddScalar:              ppc64le.AddScalarInt8VSX,
	SubScalar:              ppc64le.SubScalarInt8VSX,
	Clamp:                  ppc64le.ClampInt8VSX,
	Fill:                   ppc64le.FillInt8VSX,
	Lerp:                   ppc64le.LerpInt8VSX,
	AddScaled:              ppc64le.AddScaledInt8VSX,
	Ramp:                   ppc64le.RampInt8VSX,
	Shl:                    ppc64le.ShlInt8VSX,
	Shr:                    ppc64le.ShrInt8VSX,
	Rotl:                   ppc64le.RotlInt8VSX,
	Rotr:                   ppc64le.RotrInt8VSX,
	OnesCount:              ppc64le.OnesCountInt8VSX,
	LeadingZeros:           ppc64le.LeadingZerosInt8VSX,
	TrailingZeros:          ppc64le.TrailingZerosInt8VSX,
	SatAdd:                 ppc64le.SatAddInt8VSX,
	SatSub:                 ppc64le.SatSubInt8VSX,
	Min:                    ppc64le.MinrInt8VSX,
	Max:                    ppc64le.MaxrInt8VSX,
	SumSquares:             ppc64le.SumsqInt8VSX,
	SumSqDev:               ppc64le.SumsqdevInt8VSX,
	SumSqDiff:              ppc64le.SumsqdiffInt8VSX,
	Diff:                   ppc64le.DiffInt8VSX,
	Sum:                    ppc64le.SumInt8VSX,
	Prod:                   ppc64le.ProdInt8VSX,
	Dot:                    ppc64le.DotInt8VSX,
	L1Norm:                 ppc64le.L1normInt8VSX,
	L1Diff:                 ppc64le.L1diffInt8VSX,
	EqualMask:              ppc64le.EqInt8MaskVSX,
	EqualScalarMask:        ppc64le.EqScalarInt8MaskVSX,
	NotEqualMask:           ppc64le.NeInt8MaskVSX,
	NotEqualScalarMask:     ppc64le.NeScalarInt8MaskVSX,
	LessMask:               ppc64le.LtInt8MaskVSX,
	LessScalarMask:         ppc64le.LtScalarInt8MaskVSX,
	LessEqualMask:          ppc64le.LeInt8MaskVSX,
	LessEqualScalarMask:    ppc64le.LeScalarInt8MaskVSX,
	GreaterMask:            ppc64le.GtInt8MaskVSX,
	GreaterScalarMask:      ppc64le.GtScalarInt8MaskVSX,
	GreaterEqualMask:       ppc64le.GeInt8MaskVSX,
	GreaterEqualScalarMask: ppc64le.GeScalarInt8MaskVSX,
}

var opsI8ByTier = [...]*kernel.Ops[int8]{
	nil,
	&opsI8VSX,
}

var opsU16VSX = kernel.Ops[uint16]{
	Add:                    ppc64le.AddUint16VSX,
	Sub:                    ppc64le.SubUint16VSX,
	Mul:                    ppc64le.MulUint16VSX,
	Minimum:                ppc64le.MinimumUint16VSX,
	Maximum:                ppc64le.MaximumUint16VSX,
	Abs:                    ppc64le.AbsUint16VSX,
	Neg:                    ppc64le.NegUint16VSX,
	Scale:                  ppc64le.ScaleUint16VSX,
	AddScalar:              ppc64le.AddScalarUint16VSX,
	SubScalar:              ppc64le.SubScalarUint16VSX,
	Clamp:                  ppc64le.ClampUint16VSX,
	Fill:                   ppc64le.FillUint16VSX,
	Lerp:                   ppc64le.LerpUint16VSX,
	AddScaled:              ppc64le.AddScaledUint16VSX,
	Ramp:                   ppc64le.RampUint16VSX,
	Shl:                    ppc64le.ShlUint16VSX,
	Shr:                    ppc64le.ShrUint16VSX,
	Rotl:                   ppc64le.RotlUint16VSX,
	Rotr:                   ppc64le.RotrUint16VSX,
	OnesCount:              ppc64le.OnesCountUint16VSX,
	LeadingZeros:           ppc64le.LeadingZerosUint16VSX,
	TrailingZeros:          ppc64le.TrailingZerosUint16VSX,
	ByteSwap:               ppc64le.ByteSwapUint16VSX,
	SatAdd:                 ppc64le.SatAddUint16VSX,
	SatSub:                 ppc64le.SatSubUint16VSX,
	Min:                    ppc64le.MinrUint16VSX,
	Max:                    ppc64le.MaxrUint16VSX,
	SumSquares:             ppc64le.SumsqUint16VSX,
	SumSqDev:               ppc64le.SumsqdevUint16VSX,
	SumSqDiff:              ppc64le.SumsqdiffUint16VSX,
	Diff:                   ppc64le.DiffUint16VSX,
	Sum:                    ppc64le.SumUint16VSX,
	Prod:                   ppc64le.ProdUint16VSX,
	Dot:                    ppc64le.DotUint16VSX,
	L1Norm:                 ppc64le.L1normUint16VSX,
	L1Diff:                 ppc64le.L1diffUint16VSX,
	EqualMask:              ppc64le.EqUint16MaskVSX,
	EqualScalarMask:        ppc64le.EqScalarUint16MaskVSX,
	NotEqualMask:           ppc64le.NeUint16MaskVSX,
	NotEqualScalarMask:     ppc64le.NeScalarUint16MaskVSX,
	LessMask:               ppc64le.LtUint16MaskVSX,
	LessScalarMask:         ppc64le.LtScalarUint16MaskVSX,
	LessEqualMask:          ppc64le.LeUint16MaskVSX,
	LessEqualScalarMask:    ppc64le.LeScalarUint16MaskVSX,
	GreaterMask:            ppc64le.GtUint16MaskVSX,
	GreaterScalarMask:      ppc64le.GtScalarUint16MaskVSX,
	GreaterEqualMask:       ppc64le.GeUint16MaskVSX,
	GreaterEqualScalarMask: ppc64le.GeScalarUint16MaskVSX,
}

var opsU16ByTier = [...]*kernel.Ops[uint16]{
	nil,
	&opsU16VSX,
}

var opsU32VSX = kernel.Ops[uint32]{
	Add:                    ppc64le.AddUint32VSX,
	Sub:                    ppc64le.SubUint32VSX,
	Mul:                    ppc64le.MulUint32VSX,
	Minimum:                ppc64le.MinimumUint32VSX,
	Maximum:                ppc64le.MaximumUint32VSX,
	Abs:                    ppc64le.AbsUint32VSX,
	Neg:                    ppc64le.NegUint32VSX,
	Scale:                  ppc64le.ScaleUint32VSX,
	AddScalar:              ppc64le.AddScalarUint32VSX,
	SubScalar:              ppc64le.SubScalarUint32VSX,
	Clamp:                  ppc64le.ClampUint32VSX,
	Fill:                   ppc64le.FillUint32VSX,
	Lerp:                   ppc64le.LerpUint32VSX,
	AddScaled:              ppc64le.AddScaledUint32VSX,
	Ramp:                   ppc64le.RampUint32VSX,
	Shl:                    ppc64le.ShlUint32VSX,
	Shr:                    ppc64le.ShrUint32VSX,
	Rotl:                   ppc64le.RotlUint32VSX,
	Rotr:                   ppc64le.RotrUint32VSX,
	OnesCount:              ppc64le.OnesCountUint32VSX,
	LeadingZeros:           ppc64le.LeadingZerosUint32VSX,
	TrailingZeros:          ppc64le.TrailingZerosUint32VSX,
	ByteSwap:               ppc64le.ByteSwapUint32VSX,
	SatAdd:                 ppc64le.SatAddUint32VSX,
	SatSub:                 ppc64le.SatSubUint32VSX,
	Min:                    ppc64le.MinrUint32VSX,
	Max:                    ppc64le.MaxrUint32VSX,
	SumSquares:             ppc64le.SumsqUint32VSX,
	SumSqDev:               ppc64le.SumsqdevUint32VSX,
	SumSqDiff:              ppc64le.SumsqdiffUint32VSX,
	Diff:                   ppc64le.DiffUint32VSX,
	Sum:                    ppc64le.SumUint32VSX,
	Prod:                   ppc64le.ProdUint32VSX,
	Dot:                    ppc64le.DotUint32VSX,
	L1Norm:                 ppc64le.L1normUint32VSX,
	L1Diff:                 ppc64le.L1diffUint32VSX,
	EqualMask:              ppc64le.EqUint32MaskVSX,
	EqualScalarMask:        ppc64le.EqScalarUint32MaskVSX,
	NotEqualMask:           ppc64le.NeUint32MaskVSX,
	NotEqualScalarMask:     ppc64le.NeScalarUint32MaskVSX,
	LessMask:               ppc64le.LtUint32MaskVSX,
	LessScalarMask:         ppc64le.LtScalarUint32MaskVSX,
	LessEqualMask:          ppc64le.LeUint32MaskVSX,
	LessEqualScalarMask:    ppc64le.LeScalarUint32MaskVSX,
	GreaterMask:            ppc64le.GtUint32MaskVSX,
	GreaterScalarMask:      ppc64le.GtScalarUint32MaskVSX,
	GreaterEqualMask:       ppc64le.GeUint32MaskVSX,
	GreaterEqualScalarMask: ppc64le.GeScalarUint32MaskVSX,
}

var opsU32ByTier = [...]*kernel.Ops[uint32]{
	nil,
	&opsU32VSX,
}

var opsU64VSX = kernel.Ops[uint64]{
	Add:           ppc64le.AddUint64VSX,
	Sub:           ppc64le.SubUint64VSX,
	Minimum:       ppc64le.MinimumUint64VSX,
	Maximum:       ppc64le.MaximumUint64VSX,
	Abs:           ppc64le.AbsUint64VSX,
	Neg:           ppc64le.NegUint64VSX,
	AddScalar:     ppc64le.AddScalarUint64VSX,
	SubScalar:     ppc64le.SubScalarUint64VSX,
	Clamp:         ppc64le.ClampUint64VSX,
	Fill:          ppc64le.FillUint64VSX,
	Shl:           ppc64le.ShlUint64VSX,
	Shr:           ppc64le.ShrUint64VSX,
	Rotl:          ppc64le.RotlUint64VSX,
	Rotr:          ppc64le.RotrUint64VSX,
	OnesCount:     ppc64le.OnesCountUint64VSX,
	LeadingZeros:  ppc64le.LeadingZerosUint64VSX,
	TrailingZeros: ppc64le.TrailingZerosUint64VSX,
	ByteSwap:      ppc64le.ByteSwapUint64VSX,
	Min:           ppc64le.MinrUint64VSX,
	Max:           ppc64le.MaxrUint64VSX,
	Sum:           ppc64le.SumUint64VSX,
	L1Norm:        ppc64le.L1normUint64VSX,
	L1Diff:        ppc64le.L1diffUint64VSX,
}

var opsU64ByTier = [...]*kernel.Ops[uint64]{
	nil,
	&opsU64VSX,
}

var opsU8VSX = kernel.Ops[uint8]{
	Mul4:                   ppc64le.Mul4Uint8VSX,
	Add:                    ppc64le.AddUint8VSX,
	Sub:                    ppc64le.SubUint8VSX,
	Mul:                    ppc64le.MulUint8VSX,
	Minimum:                ppc64le.MinimumUint8VSX,
	Maximum:                ppc64le.MaximumUint8VSX,
	Abs:                    ppc64le.AbsUint8VSX,
	Neg:                    ppc64le.NegUint8VSX,
	Scale:                  ppc64le.ScaleUint8VSX,
	AddScalar:              ppc64le.AddScalarUint8VSX,
	SubScalar:              ppc64le.SubScalarUint8VSX,
	Clamp:                  ppc64le.ClampUint8VSX,
	Fill:                   ppc64le.FillUint8VSX,
	Lerp:                   ppc64le.LerpUint8VSX,
	AddScaled:              ppc64le.AddScaledUint8VSX,
	Ramp:                   ppc64le.RampUint8VSX,
	Shl:                    ppc64le.ShlUint8VSX,
	Shr:                    ppc64le.ShrUint8VSX,
	Rotl:                   ppc64le.RotlUint8VSX,
	Rotr:                   ppc64le.RotrUint8VSX,
	OnesCount:              ppc64le.OnesCountUint8VSX,
	LeadingZeros:           ppc64le.LeadingZerosUint8VSX,
	TrailingZeros:          ppc64le.TrailingZerosUint8VSX,
	SatAdd:                 ppc64le.SatAddUint8VSX,
	SatSub:                 ppc64le.SatSubUint8VSX,
	Min:                    ppc64le.MinrUint8VSX,
	Max:                    ppc64le.MaxrUint8VSX,
	SumSquares:             ppc64le.SumsqUint8VSX,
	SumSqDev:               ppc64le.SumsqdevUint8VSX,
	SumSqDiff:              ppc64le.SumsqdiffUint8VSX,
	Diff:                   ppc64le.DiffUint8VSX,
	Sum:                    ppc64le.SumUint8VSX,
	Prod:                   ppc64le.ProdUint8VSX,
	Dot:                    ppc64le.DotUint8VSX,
	L1Norm:                 ppc64le.L1normUint8VSX,
	L1Diff:                 ppc64le.L1diffUint8VSX,
	EqualMask:              ppc64le.EqUint8MaskVSX,
	EqualScalarMask:        ppc64le.EqScalarUint8MaskVSX,
	NotEqualMask:           ppc64le.NeUint8MaskVSX,
	NotEqualScalarMask:     ppc64le.NeScalarUint8MaskVSX,
	LessMask:               ppc64le.LtUint8MaskVSX,
	LessScalarMask:         ppc64le.LtScalarUint8MaskVSX,
	LessEqualMask:          ppc64le.LeUint8MaskVSX,
	LessEqualScalarMask:    ppc64le.LeScalarUint8MaskVSX,
	GreaterMask:            ppc64le.GtUint8MaskVSX,
	GreaterScalarMask:      ppc64le.GtScalarUint8MaskVSX,
	GreaterEqualMask:       ppc64le.GeUint8MaskVSX,
	GreaterEqualScalarMask: ppc64le.GeScalarUint8MaskVSX,
}

var opsU8ByTier = [...]*kernel.Ops[uint8]{
	nil,
	&opsU8VSX,
}

var cplxC128VSX = kernel.Complex[complex128]{
	Add:     ppc64le.CaddComplex128VSX,
	Sub:     ppc64le.CsubComplex128VSX,
	Mul:     ppc64le.CmulComplex128VSX,
	Neg:     ppc64le.CnegComplex128VSX,
	Conj:    ppc64le.CconjComplex128VSX,
	Sum:     ppc64le.CsumComplex128VSX,
	Dot:     ppc64le.CdotComplex128VSX,
	DotConj: ppc64le.CdotconjComplex128VSX,
}

var cplxC128ByTier = [...]*kernel.Complex[complex128]{
	nil,
	&cplxC128VSX,
}

var cplxC64VSX = kernel.Complex[complex64]{
	Add:  ppc64le.CaddComplex64VSX,
	Sub:  ppc64le.CsubComplex64VSX,
	Mul:  ppc64le.CmulComplex64VSX,
	Div:  ppc64le.CdivComplex64VSX,
	Neg:  ppc64le.CnegComplex64VSX,
	Conj: ppc64le.CconjComplex64VSX,
}

var cplxC64ByTier = [...]*kernel.Complex[complex64]{
	nil,
	&cplxC64VSX,
}

var partsC128PartsVSX = kernel.ComplexParts[complex128, float64]{
	Abs:       ppc64le.CabsComplex128VSX,
	Real:      ppc64le.CrealComplex128VSX,
	Imag:      ppc64le.CimagComplex128VSX,
	Scale:     ppc64le.CscaleComplex128VSX,
	FromParts: ppc64le.CfromPartsComplex128VSX,
}

var partsC128PartsByTier = [...]*kernel.ComplexParts[complex128, float64]{
	nil,
	&partsC128PartsVSX,
}

var partsC64PartsVSX = kernel.ComplexParts[complex64, float32]{
	Abs:       ppc64le.CabsComplex64VSX,
	Real:      ppc64le.CrealComplex64VSX,
	Imag:      ppc64le.CimagComplex64VSX,
	Scale:     ppc64le.CscaleComplex64VSX,
	FromParts: ppc64le.CfromPartsComplex64VSX,
}

var partsC64PartsByTier = [...]*kernel.ComplexParts[complex64, float32]{
	nil,
	&partsC64PartsVSX,
}
