// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/argreduce.c
// Target: arm64/sve2

//go:build arm64 && !purego

package arm64

import "runtime"

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

//go:noescape
func argMinFloat32SVE2(a []float32) int

//go:noescape
func argMaxFloat32SVE2(a []float32) int

//go:noescape
func minMaxFloat32SVE2(a []float32) (lo float32, hi float32)

//go:noescape
func argMinFloat64SVE2(a []float64) int

//go:noescape
func argMaxFloat64SVE2(a []float64) int

//go:noescape
func minMaxFloat64SVE2(a []float64) (lo float64, hi float64)

//go:noescape
func argMinInt32SVE2(a []int32) int

//go:noescape
func argMaxInt32SVE2(a []int32) int

//go:noescape
func minMaxInt32SVE2(a []int32) (lo int32, hi int32)

//go:noescape
func argMinInt64SVE2(a []int64) int

//go:noescape
func argMaxInt64SVE2(a []int64) int

//go:noescape
func minMaxInt64SVE2(a []int64) (lo int64, hi int64)
