// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/arith.c
// Target: arm64/sve2

//go:build arm64 && !purego

package arm64

import "runtime"

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

//go:noescape
func addFloat32SVE2(dst []float32, a []float32, b []float32)

//go:noescape
func subFloat32SVE2(dst []float32, a []float32, b []float32)

//go:noescape
func mulFloat32SVE2(dst []float32, a []float32, b []float32)

//go:noescape
func minimumFloat32SVE2(dst []float32, a []float32, b []float32)

//go:noescape
func maximumFloat32SVE2(dst []float32, a []float32, b []float32)

//go:noescape
func absFloat32SVE2(dst []float32, a []float32)

//go:noescape
func negFloat32SVE2(dst []float32, a []float32)

//go:noescape
func scaleFloat32SVE2(dst []float32, a []float32, s float32)

//go:noescape
func addScalarFloat32SVE2(dst []float32, a []float32, s float32)

//go:noescape
func subScalarFloat32SVE2(dst []float32, a []float32, s float32)

//go:noescape
func clampFloat32SVE2(dst []float32, a []float32, lo float32, hi float32)

//go:noescape
func fillFloat32SVE2(dst []float32, v float32)

//go:noescape
func lerpFloat32SVE2(dst []float32, a []float32, b []float32, t float32)

//go:noescape
func addScaledFloat32SVE2(dst []float32, a []float32, b []float32, s float32)

//go:noescape
func addFloat64SVE2(dst []float64, a []float64, b []float64)

//go:noescape
func subFloat64SVE2(dst []float64, a []float64, b []float64)

//go:noescape
func mulFloat64SVE2(dst []float64, a []float64, b []float64)

//go:noescape
func minimumFloat64SVE2(dst []float64, a []float64, b []float64)

//go:noescape
func maximumFloat64SVE2(dst []float64, a []float64, b []float64)

//go:noescape
func absFloat64SVE2(dst []float64, a []float64)

//go:noescape
func negFloat64SVE2(dst []float64, a []float64)

//go:noescape
func scaleFloat64SVE2(dst []float64, a []float64, s float64)

//go:noescape
func addScalarFloat64SVE2(dst []float64, a []float64, s float64)

//go:noescape
func subScalarFloat64SVE2(dst []float64, a []float64, s float64)

//go:noescape
func clampFloat64SVE2(dst []float64, a []float64, lo float64, hi float64)

//go:noescape
func fillFloat64SVE2(dst []float64, v float64)

//go:noescape
func lerpFloat64SVE2(dst []float64, a []float64, b []float64, t float64)

//go:noescape
func addScaledFloat64SVE2(dst []float64, a []float64, b []float64, s float64)

//go:noescape
func addInt32SVE2(dst []int32, a []int32, b []int32)

//go:noescape
func subInt32SVE2(dst []int32, a []int32, b []int32)

//go:noescape
func mulInt32SVE2(dst []int32, a []int32, b []int32)

//go:noescape
func minimumInt32SVE2(dst []int32, a []int32, b []int32)

//go:noescape
func maximumInt32SVE2(dst []int32, a []int32, b []int32)

//go:noescape
func absInt32SVE2(dst []int32, a []int32)

//go:noescape
func negInt32SVE2(dst []int32, a []int32)

//go:noescape
func scaleInt32SVE2(dst []int32, a []int32, s int32)

//go:noescape
func addScalarInt32SVE2(dst []int32, a []int32, s int32)

//go:noescape
func subScalarInt32SVE2(dst []int32, a []int32, s int32)

//go:noescape
func clampInt32SVE2(dst []int32, a []int32, lo int32, hi int32)

//go:noescape
func fillInt32SVE2(dst []int32, v int32)

//go:noescape
func lerpInt32SVE2(dst []int32, a []int32, b []int32, t int32)

//go:noescape
func addScaledInt32SVE2(dst []int32, a []int32, b []int32, s int32)

//go:noescape
func addInt64SVE2(dst []int64, a []int64, b []int64)

//go:noescape
func subInt64SVE2(dst []int64, a []int64, b []int64)

//go:noescape
func mulInt64SVE2(dst []int64, a []int64, b []int64)

//go:noescape
func minimumInt64SVE2(dst []int64, a []int64, b []int64)

//go:noescape
func maximumInt64SVE2(dst []int64, a []int64, b []int64)

//go:noescape
func absInt64SVE2(dst []int64, a []int64)

//go:noescape
func negInt64SVE2(dst []int64, a []int64)

//go:noescape
func scaleInt64SVE2(dst []int64, a []int64, s int64)

//go:noescape
func addScalarInt64SVE2(dst []int64, a []int64, s int64)

//go:noescape
func subScalarInt64SVE2(dst []int64, a []int64, s int64)

//go:noescape
func clampInt64SVE2(dst []int64, a []int64, lo int64, hi int64)

//go:noescape
func fillInt64SVE2(dst []int64, v int64)

//go:noescape
func lerpInt64SVE2(dst []int64, a []int64, b []int64, t int64)

//go:noescape
func addScaledInt64SVE2(dst []int64, a []int64, b []int64, s int64)

//go:noescape
func divFloat32SVE2(dst []float32, a []float32, b []float32)

//go:noescape
func divScalarFloat32SVE2(dst []float32, a []float32, s float32)

//go:noescape
func sqrtFloat32SVE2(dst []float32, a []float32)

//go:noescape
func reciprocalFloat32SVE2(dst []float32, a []float32)

//go:noescape
func floorFloat32SVE2(dst []float32, a []float32)

//go:noescape
func ceilFloat32SVE2(dst []float32, a []float32)

//go:noescape
func truncFloat32SVE2(dst []float32, a []float32)

//go:noescape
func roundFloat32SVE2(dst []float32, a []float32)

//go:noescape
func roundToEvenFloat32SVE2(dst []float32, a []float32)

//go:noescape
func divFloat64SVE2(dst []float64, a []float64, b []float64)

//go:noescape
func divScalarFloat64SVE2(dst []float64, a []float64, s float64)

//go:noescape
func sqrtFloat64SVE2(dst []float64, a []float64)

//go:noescape
func reciprocalFloat64SVE2(dst []float64, a []float64)

//go:noescape
func floorFloat64SVE2(dst []float64, a []float64)

//go:noescape
func ceilFloat64SVE2(dst []float64, a []float64)

//go:noescape
func truncFloat64SVE2(dst []float64, a []float64)

//go:noescape
func roundFloat64SVE2(dst []float64, a []float64)

//go:noescape
func roundToEvenFloat64SVE2(dst []float64, a []float64)
