// Code generated by simdgen. DO NOT EDIT.
//
// Source:  csrc/blas.c
// Target:  arm64/neon
// Clang:   clang version 22.1.8
// Command: clang --target=aarch64-linux-gnu -march=armv8-a -O3 -ffreestanding -fno-builtin -fno-builtin-memset -fno-builtin-memcpy -fno-jump-tables -fno-math-errno -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -fomit-frame-pointer -fno-stack-protector -mllvm -inline-threshold=1000 -ffp-contract=off -ffixed-x28 -ffixed-x27 -ffixed-x18 -c ../csrc/blas.c -o ../tools/build/tmp/blas_arm64_neon.o
//
// The instruction bytes below are the compiled function verbatim. Branches
// inside a function are PC-relative and remain correct because the whole
// body moves as a unit.

//go:build arm64 && !purego

#include "textflag.h"

// func gerFloat32NEON(a []float32, x []float32, y []float32, alpha float32, m int, n int)
TEXT ·gerFloat32NEON(SB), NOSPLIT|NOFRAME, $0-96
	MOVD a_base+0(FP), R0
	MOVD x_base+24(FP), R1
	MOVD y_base+48(FP), R2
	FMOVS alpha+72(FP), F0
	MOVD m+80(FP), R3
	MOVD n+88(FP), R4
	WORD $0xf100047f
	WORD $0x5400060b
	WORD $0xf100049f
	WORD $0x540005cb
	WORD $0xd37ef489
	WORD $0xaa1f03e8
	WORD $0x927dec8a
	WORD $0x9100400b
	WORD $0x14000006
	WORD $0x91000508
	WORD $0x8b09016b
	WORD $0x8b090000
	WORD $0xeb03011f
	WORD $0x54000480
	WORD $0xbc687821
	WORD $0xf100209f
	WORD $0x1e210801
	WORD $0x54000062
	WORD $0xaa1f03ec
	WORD $0x14000012
	WORD $0x9100404c
	WORD $0xaa0b03ed
	WORD $0x927dec8e
	WORD $0xad7f8d82
	WORD $0xf10021ce
	WORD $0xad7f95a4
	WORD $0x9100818c
	WORD $0x4f819042
	WORD $0x4f819063
	WORD $0x4e22d482
	WORD $0x4e23d4a3
	WORD $0xad3f8da2
	WORD $0x910081ad
	WORD $0x54fffec1
	WORD $0xeb0a009f
	WORD $0x927dec8c
	WORD $0x54fffca0
	WORD $0xd37ef58e
	WORD $0xcb0c008c
	WORD $0x8b0e000d
	WORD $0x8b0e004e
	WORD $0xbc4045c2
	WORD $0xbd4001a3
	WORD $0xf100058c
	WORD $0x1e220822
	WORD $0x1e222862
	WORD $0xbc0045a2
	WORD $0x54ffff41
	WORD $0x17ffffd9
	WORD $0xd65f03c0
	RET

// func rotFloat32NEON(x []float32, y []float32, c float32, s float32)
TEXT ·rotFloat32NEON(SB), NOSPLIT|NOFRAME, $0-56
	MOVD x_base+0(FP), R0
	MOVD y_base+24(FP), R1
	FMOVS c+48(FP), F0
	FMOVS s+52(FP), F1
	MOVD x_len+8(FP), R2
	WORD $0xf100045f
	WORD $0x540004eb
	WORD $0xf100105f
	WORD $0x54000062
	WORD $0xaa1f03e8
	WORD $0x14000013
	WORD $0x927ef048
	WORD $0xaa0003e9
	WORD $0xaa0103ea
	WORD $0x927ef04b
	WORD $0x3dc00122
	WORD $0x3dc00143
	WORD $0xf100116b
	WORD $0x4f809044
	WORD $0x4f819065
	WORD $0x4f809063
	WORD $0x4f819042
	WORD $0x4e25d484
	WORD $0x4ea2d462
	WORD $0x3c810524
	WORD $0x3c810542
	WORD $0x54fffea1
	WORD $0xeb08005f
	WORD $0x54000220
	WORD $0xd37ef50a
	WORD $0xcb080048
	WORD $0x8b0a0029
	WORD $0x8b0a000a
	WORD $0xbd400142
	WORD $0xbd400123
	WORD $0xf1000508
	WORD $0x1e220804
	WORD $0x1e230825
	WORD $0x1e230803
	WORD $0x1e220822
	WORD $0x1e252884
	WORD $0x1e223862
	WORD $0xbc004544
	WORD $0xbc004522
	WORD $0x54fffea1
	WORD $0xd65f03c0
	RET

// func gerFloat64NEON(a []float64, x []float64, y []float64, alpha float64, m int, n int)
TEXT ·gerFloat64NEON(SB), NOSPLIT|NOFRAME, $0-96
	MOVD a_base+0(FP), R0
	MOVD x_base+24(FP), R1
	MOVD y_base+48(FP), R2
	FMOVD alpha+72(FP), F0
	MOVD m+80(FP), R3
	MOVD n+88(FP), R4
	WORD $0xf100047f
	WORD $0x5400060b
	WORD $0xf100049f
	WORD $0x540005cb
	WORD $0xd37df089
	WORD $0xaa1f03e8
	WORD $0x927ef08a
	WORD $0x9100400b
	WORD $0x14000006
	WORD $0x91000508
	WORD $0x8b09016b
	WORD $0x8b090000
	WORD $0xeb03011f
	WORD $0x54000480
	WORD $0xfc687821
	WORD $0xf100109f
	WORD $0x1e610801
	WORD $0x54000062
	WORD $0xaa1f03ec
	WORD $0x14000012
	WORD $0x9100404c
	WORD $0xaa0b03ed
	WORD $0x927ef08e
	WORD $0xad7f8d82
	WORD $0xf10011ce
	WORD $0xad7f95a4
	WORD $0x9100818c
	WORD $0x4fc19042
	WORD $0x4fc19063
	WORD $0x4e62d482
	WORD $0x4e63d4a3
	WORD $0xad3f8da2
	WORD $0x910081ad
	WORD $0x54fffec1
	WORD $0xeb0a009f
	WORD $0x927ef08c
	WORD $0x54fffca0
	WORD $0xd37df18e
	WORD $0xcb0c008c
	WORD $0x8b0e000d
	WORD $0x8b0e004e
	WORD $0xfc4085c2
	WORD $0xfd4001a3
	WORD $0xf100058c
	WORD $0x1e620822
	WORD $0x1e622862
	WORD $0xfc0085a2
	WORD $0x54ffff41
	WORD $0x17ffffd9
	WORD $0xd65f03c0
	RET

// func rotFloat64NEON(x []float64, y []float64, c float64, s float64)
TEXT ·rotFloat64NEON(SB), NOSPLIT|NOFRAME, $0-64
	MOVD x_base+0(FP), R0
	MOVD y_base+24(FP), R1
	FMOVD c+48(FP), F0
	FMOVD s+56(FP), F1
	MOVD x_len+8(FP), R2
	WORD $0xf100045f
	WORD $0x540004cb
	WORD $0x54000061
	WORD $0xaa1f03e8
	WORD $0x14000013
	WORD $0x927ff448
	WORD $0xaa0003e9
	WORD $0xaa0103ea
	WORD $0x927ff44b
	WORD $0x3dc00122
	WORD $0x3dc00143
	WORD $0xf100096b
	WORD $0x4fc09044
	WORD $0x4fc19065
	WORD $0x4fc09063
	WORD $0x4fc19042
	WORD $0x4e65d484
	WORD $0x4ee2d462
	WORD $0x3c810524
	WORD $0x3c810542
	WORD $0x54fffea1
	WORD $0xeb08005f
	WORD $0x54000220
	WORD $0xd37df10a
	WORD $0xcb080048
	WORD $0x8b0a0029
	WORD $0x8b0a000a
	WORD $0xfd400142
	WORD $0xfd400123
	WORD $0xf1000508
	WORD $0x1e620804
	WORD $0x1e630825
	WORD $0x1e630803
	WORD $0x1e620822
	WORD $0x1e652884
	WORD $0x1e623862
	WORD $0xfc008544
	WORD $0xfc008522
	WORD $0x54fffea1
	WORD $0xd65f03c0
	RET

