// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/compress.c
// Target: arm64/sve2

//go:build arm64 && !purego

package arm64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

func indexAllSVE2Guarded(dst []int32, b []byte, c byte) int {
	if len(dst) < 64 {
		return ref.IndexAll(dst, b, c)
	}
	return indexAllSVE2(dst, b, c)
}

func compressFloat32SVE2Guarded(dst []float32, src []float32, keep []bool) int {
	n := min(len(src), len(dst), len(keep))
	if n < 192 || len(dst) < len(src) {
		return ref.CompressFloat32(dst, src, keep)
	}
	return compressFloat32SVE2(dst, src[:n:n], keep)
}

func compressFloat64SVE2Guarded(dst []float64, src []float64, keep []bool) int {
	n := min(len(src), len(dst), len(keep))
	if n < 192 || len(dst) < len(src) {
		return ref.CompressFloat64(dst, src, keep)
	}
	return compressFloat64SVE2(dst, src[:n:n], keep)
}

func compressInt32SVE2Guarded(dst []int32, src []int32, keep []bool) int {
	n := min(len(src), len(dst), len(keep))
	if n < 192 || len(dst) < len(src) {
		return ref.CompressInt32(dst, src, keep)
	}
	return compressInt32SVE2(dst, src[:n:n], keep)
}

func compressInt64SVE2Guarded(dst []int64, src []int64, keep []bool) int {
	n := min(len(src), len(dst), len(keep))
	if n < 192 || len(dst) < len(src) {
		return ref.CompressInt64(dst, src, keep)
	}
	return compressInt64SVE2(dst, src[:n:n], keep)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("sve2")
	s.Bytes.IndexAll = indexAllSVE2Guarded
	s.F32.Compress = compressFloat32SVE2Guarded
	s.F64.Compress = compressFloat64SVE2Guarded
	s.I32.Compress = compressInt32SVE2Guarded
	s.I64.Compress = compressInt64SVE2Guarded
}
