// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/convert.c
// Target: arm64/neon

//go:build arm64 && !purego

package arm64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

func QuantizeI8NEON(dst []int8, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeI8(dst, a, scale, zeroPoint)
		return
	}
	quantizeI8NEON(dst[:n:n], a, scale, zeroPoint)
}

func DequantizeI8NEON(dst []float32, a []int8, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeI8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeI8NEON(dst[:n:n], a, scale, zeroPoint)
}

func QuantizeU8NEON(dst []byte, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeU8(dst, a, scale, zeroPoint)
		return
	}
	quantizeU8NEON(dst[:n:n], a, scale, zeroPoint)
}

func DequantizeU8NEON(dst []float32, a []byte, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeU8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeU8NEON(dst[:n:n], a, scale, zeroPoint)
}

func QuantizePerChannelI8NEON(dst []int8, a []float32, scale []float32, zeroPoint []int32, channels int, inner int) {
	if len(dst) < 16 || channels <= 0 || inner <= 0 || len(scale) < channels || len(zeroPoint) < channels || len(dst) < channels*inner || len(a) < channels*inner {
		ref.QuantizePerChannelI8(dst, a, scale, zeroPoint, channels, inner)
		return
	}
	quantizePerChannelI8NEON(dst, a, scale, zeroPoint, channels, inner)
}

func QuantizePerChannelU8NEON(dst []byte, a []float32, scale []float32, zeroPoint []int32, channels int, inner int) {
	if len(dst) < 16 || channels <= 0 || inner <= 0 || len(scale) < channels || len(zeroPoint) < channels || len(dst) < channels*inner || len(a) < channels*inner {
		ref.QuantizePerChannelU8(dst, a, scale, zeroPoint, channels, inner)
		return
	}
	quantizePerChannelU8NEON(dst, a, scale, zeroPoint, channels, inner)
}

func DequantizePerChannelI8NEON(dst []float32, a []int8, scale []float32, zeroPoint []int32, channels int, inner int) {
	if len(dst) < 16 || channels <= 0 || inner <= 0 || len(scale) < channels || len(zeroPoint) < channels || len(dst) < channels*inner || len(a) < channels*inner {
		ref.DequantizePerChannelI8(dst, a, scale, zeroPoint, channels, inner)
		return
	}
	dequantizePerChannelI8NEON(dst, a, scale, zeroPoint, channels, inner)
}

func DequantizePerChannelU8NEON(dst []float32, a []byte, scale []float32, zeroPoint []int32, channels int, inner int) {
	if len(dst) < 16 || channels <= 0 || inner <= 0 || len(scale) < channels || len(zeroPoint) < channels || len(dst) < channels*inner || len(a) < channels*inner {
		ref.DequantizePerChannelU8(dst, a, scale, zeroPoint, channels, inner)
		return
	}
	dequantizePerChannelU8NEON(dst, a, scale, zeroPoint, channels, inner)
}

func ZigzagEncodeI8NEON(dst []byte, a []int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI8(dst, a)
		return
	}
	zigzagEncodeI8NEON(dst[:n:n], a)
}

func ZigzagDecodeI8NEON(dst []int8, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI8(dst, a)
		return
	}
	zigzagDecodeI8NEON(dst[:n:n], a)
}

func ZigzagEncodeI16NEON(dst []uint16, a []int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI16(dst, a)
		return
	}
	zigzagEncodeI16NEON(dst[:n:n], a)
}

func ZigzagDecodeI16NEON(dst []int16, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI16(dst, a)
		return
	}
	zigzagDecodeI16NEON(dst[:n:n], a)
}

func ZigzagEncodeI32NEON(dst []uint32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI32(dst, a)
		return
	}
	zigzagEncodeI32NEON(dst[:n:n], a)
}

func ZigzagDecodeI32NEON(dst []int32, a []uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI32(dst, a)
		return
	}
	zigzagDecodeI32NEON(dst[:n:n], a)
}

func ZigzagEncodeI64NEON(dst []uint64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI64(dst, a)
		return
	}
	zigzagEncodeI64NEON(dst[:n:n], a)
}

func ZigzagDecodeI64NEON(dst []int64, a []uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI64(dst, a)
		return
	}
	zigzagDecodeI64NEON(dst[:n:n], a)
}

func VarintLenU32NEON(dst []int32, a []uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.VarintLenU32(dst, a)
		return
	}
	varintLenU32NEON(dst[:n:n], a)
}

func VarintLenU64NEON(dst []int32, a []uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.VarintLenU64(dst, a)
		return
	}
	varintLenU64NEON(dst[:n:n], a)
}

func VarintSizeU32NEON(a []uint32) int {
	if len(a) < 16 {
		return ref.VarintSizeU32(a)
	}
	return varintSizeU32NEON(a)
}

func VarintSizeU64NEON(a []uint64) int {
	if len(a) < 16 {
		return ref.VarintSizeU64(a)
	}
	return varintSizeU64NEON(a)
}

func F8e4m3ToF32NEON(dst []float32, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F8E4M3ToF32(dst, a)
		return
	}
	f8e4m3ToF32NEON(dst[:n:n], a)
}

func F8e5m2ToF32NEON(dst []float32, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F8E5M2ToF32(dst, a)
		return
	}
	f8e5m2ToF32NEON(dst[:n:n], a)
}

func Bf16ToF32NEON(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.BF16ToF32(dst, a)
		return
	}
	bf16ToF32NEON(dst[:n:n], a)
}

func F32ToBF16NEON(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToBF16(dst, a)
		return
	}
	f32ToBF16NEON(dst[:n:n], a)
}

func F16ToF32NEON(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F16ToF32(dst, a)
		return
	}
	f16ToF32NEON(dst[:n:n], a)
}

func F32ToF16NEON(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToF16(dst, a)
		return
	}
	f32ToF16NEON(dst[:n:n], a)
}

func VarintDecodeU64NEON(dst []uint64, src []byte) (n int, consumed int) {
	if len(dst) < 0 || len(src) == 0 {
		return ref.VarintDecodeU64(dst, src)
	}
	return varintDecodeU64NEON(dst, src)
}

func registerConvertNEON(s *kernel.Set) {
	s.Convert.QuantizeI8 = QuantizeI8NEON
	s.Convert.DequantizeI8 = DequantizeI8NEON
	s.Convert.QuantizeU8 = QuantizeU8NEON
	s.Convert.DequantizeU8 = DequantizeU8NEON
	s.Convert.QuantizePerChannelI8 = QuantizePerChannelI8NEON
	s.Convert.QuantizePerChannelU8 = QuantizePerChannelU8NEON
	s.Convert.DequantizePerChannelI8 = DequantizePerChannelI8NEON
	s.Convert.DequantizePerChannelU8 = DequantizePerChannelU8NEON
	s.Convert.ZigzagEncodeI8 = ZigzagEncodeI8NEON
	s.Convert.ZigzagDecodeI8 = ZigzagDecodeI8NEON
	s.Convert.ZigzagEncodeI16 = ZigzagEncodeI16NEON
	s.Convert.ZigzagDecodeI16 = ZigzagDecodeI16NEON
	s.Convert.ZigzagEncodeI32 = ZigzagEncodeI32NEON
	s.Convert.ZigzagDecodeI32 = ZigzagDecodeI32NEON
	s.Convert.ZigzagEncodeI64 = ZigzagEncodeI64NEON
	s.Convert.ZigzagDecodeI64 = ZigzagDecodeI64NEON
	s.Convert.VarintLenU32 = VarintLenU32NEON
	s.Convert.VarintLenU64 = VarintLenU64NEON
	s.Convert.VarintSizeU32 = VarintSizeU32NEON
	s.Convert.VarintSizeU64 = VarintSizeU64NEON
	s.Convert.F8E4M3ToF32 = F8e4m3ToF32NEON
	s.Convert.F8E5M2ToF32 = F8e5m2ToF32NEON
	s.Convert.BF16ToF32 = Bf16ToF32NEON
	s.Convert.F32ToBF16 = F32ToBF16NEON
	s.Convert.F16ToF32 = F16ToF32NEON
	s.Convert.F32ToF16 = F32ToF16NEON
	s.Bytes.VarintDecodeU64 = VarintDecodeU64NEON
}
