// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/convert.c
// Target: arm64/sve2

//go:build arm64 && !purego

package arm64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

func quantizeI8SVE2Guarded(dst []int8, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeI8(dst, a, scale, zeroPoint)
		return
	}
	quantizeI8SVE2(dst[:n:n], a, scale, zeroPoint)
}

func dequantizeI8SVE2Guarded(dst []float32, a []int8, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeI8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeI8SVE2(dst[:n:n], a, scale, zeroPoint)
}

func quantizeU8SVE2Guarded(dst []byte, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeU8(dst, a, scale, zeroPoint)
		return
	}
	quantizeU8SVE2(dst[:n:n], a, scale, zeroPoint)
}

func dequantizeU8SVE2Guarded(dst []float32, a []byte, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeU8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeU8SVE2(dst[:n:n], a, scale, zeroPoint)
}

func bf16ToF32SVE2Guarded(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.BF16ToF32(dst, a)
		return
	}
	bf16ToF32SVE2(dst[:n:n], a)
}

func f32ToBF16SVE2Guarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToBF16(dst, a)
		return
	}
	f32ToBF16SVE2(dst[:n:n], a)
}

func f16ToF32SVE2Guarded(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F16ToF32(dst, a)
		return
	}
	f16ToF32SVE2(dst[:n:n], a)
}

func f32ToF16SVE2Guarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToF16(dst, a)
		return
	}
	f32ToF16SVE2(dst[:n:n], a)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("sve2")
	s.Convert.QuantizeI8 = quantizeI8SVE2Guarded
	s.Convert.DequantizeI8 = dequantizeI8SVE2Guarded
	s.Convert.QuantizeU8 = quantizeU8SVE2Guarded
	s.Convert.DequantizeU8 = dequantizeU8SVE2Guarded
	s.Convert.BF16ToF32 = bf16ToF32SVE2Guarded
	s.Convert.F32ToBF16 = f32ToBF16SVE2Guarded
	s.Convert.F16ToF32 = f16ToF32SVE2Guarded
	s.Convert.F32ToF16 = f32ToF16SVE2Guarded
}
