// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/merge.c
// Target: arm64/sve2

//go:build arm64 && !purego

package arm64

import "runtime"

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

//go:noescape
func mergeSortedU32SVE2(dst []uint32, a []uint32, b []uint32) int
