// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/random.c
// Target: arm64/sve2

//go:build arm64 && !purego

package arm64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

func HashU64SVE2(dst []uint64, keys []uint64, seed uint64) {
	n := min(len(dst), len(keys))
	if n < 32 {
		ref.HashU64(dst, keys, seed)
		return
	}
	hashU64SVE2(dst[:n:n], keys, seed)
}

func RandFillU64SVE2(dst []uint64, seed uint64) {
	if len(dst) < 0 {
		ref.RandFillU64(dst, seed)
		return
	}
	randFillU64SVE2(dst, seed)
}

func registerRandomSVE2(s *kernel.Set) {
	s.Bytes.HashU64 = HashU64SVE2
	s.Bytes.RandFillU64 = RandFillU64SVE2
}
