// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/reduce.c
// Target: arm64/neon

//go:build arm64 && !purego

package arm64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

func MinrFloat32NEON(a []float32) float32 {
	if len(a) < 1 {
		return ref.MinReduceFloat(a)
	}
	return minrFloat32NEON(a)
}

func MaxrFloat32NEON(a []float32) float32 {
	if len(a) < 1 {
		return ref.MaxReduceFloat(a)
	}
	return maxrFloat32NEON(a)
}

func SumsqFloat32NEON(a []float32) float32 {
	if len(a) < 0 {
		return ref.SumSquaresFloat(a)
	}
	return sumsqFloat32NEON(a)
}

func SumsqdevFloat32NEON(a []float32, c float32) float32 {
	if len(a) < 0 {
		return ref.SumSqDevFloat(a, c)
	}
	return sumsqdevFloat32NEON(a, c)
}

func SumsqdiffFloat32NEON(a []float32, b []float32) float32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffFloat(a, b)
	}
	return sumsqdiffFloat32NEON(a[:n:n], b)
}

func DiffFloat32NEON(dst []float32, a []float32) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffFloat32NEON(dst, a)
}

func MinrFloat64NEON(a []float64) float64 {
	if len(a) < 1 {
		return ref.MinReduceFloat(a)
	}
	return minrFloat64NEON(a)
}

func MaxrFloat64NEON(a []float64) float64 {
	if len(a) < 1 {
		return ref.MaxReduceFloat(a)
	}
	return maxrFloat64NEON(a)
}

func SumsqFloat64NEON(a []float64) float64 {
	if len(a) < 0 {
		return ref.SumSquaresFloat(a)
	}
	return sumsqFloat64NEON(a)
}

func SumsqdevFloat64NEON(a []float64, c float64) float64 {
	if len(a) < 0 {
		return ref.SumSqDevFloat(a, c)
	}
	return sumsqdevFloat64NEON(a, c)
}

func SumsqdiffFloat64NEON(a []float64, b []float64) float64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffFloat(a, b)
	}
	return sumsqdiffFloat64NEON(a[:n:n], b)
}

func DiffFloat64NEON(dst []float64, a []float64) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffFloat64NEON(dst, a)
}

func MinrInt32NEON(a []int32) int32 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrInt32NEON(a)
}

func MaxrInt32NEON(a []int32) int32 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt32NEON(a)
}

func SumsqInt32NEON(a []int32) int32 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqInt32NEON(a)
}

func SumsqdevInt32NEON(a []int32, c int32) int32 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevInt32NEON(a, c)
}

func SumsqdiffInt32NEON(a []int32, b []int32) int32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffInt32NEON(a[:n:n], b)
}

func DiffInt32NEON(dst []int32, a []int32) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt32NEON(dst, a)
}

func MinrInt64NEON(a []int64) int64 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrInt64NEON(a)
}

func MaxrInt64NEON(a []int64) int64 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt64NEON(a)
}

func DiffInt64NEON(dst []int64, a []int64) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt64NEON(dst, a)
}

func MinrInt8NEON(a []int8) int8 {
	if len(a) < 24 {
		return ref.MinReduceInt(a)
	}
	return minrInt8NEON(a)
}

func MaxrInt8NEON(a []int8) int8 {
	if len(a) < 24 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt8NEON(a)
}

func SumsqInt8NEON(a []int8) int8 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqInt8NEON(a)
}

func SumsqdevInt8NEON(a []int8, c int8) int8 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevInt8NEON(a, c)
}

func SumsqdiffInt8NEON(a []int8, b []int8) int8 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffInt8NEON(a[:n:n], b)
}

func DiffInt8NEON(dst []int8, a []int8) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt8NEON(dst, a)
}

func MinrInt16NEON(a []int16) int16 {
	if len(a) < 16 {
		return ref.MinReduceInt(a)
	}
	return minrInt16NEON(a)
}

func MaxrInt16NEON(a []int16) int16 {
	if len(a) < 16 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt16NEON(a)
}

func SumsqInt16NEON(a []int16) int16 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqInt16NEON(a)
}

func SumsqdevInt16NEON(a []int16, c int16) int16 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevInt16NEON(a, c)
}

func SumsqdiffInt16NEON(a []int16, b []int16) int16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffInt16NEON(a[:n:n], b)
}

func DiffInt16NEON(dst []int16, a []int16) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt16NEON(dst, a)
}

func MinrUint8NEON(a []byte) byte {
	if len(a) < 24 {
		return ref.MinReduceInt(a)
	}
	return minrUint8NEON(a)
}

func MaxrUint8NEON(a []byte) byte {
	if len(a) < 24 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint8NEON(a)
}

func SumsqUint8NEON(a []byte) byte {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqUint8NEON(a)
}

func SumsqdevUint8NEON(a []byte, c byte) byte {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevUint8NEON(a, c)
}

func SumsqdiffUint8NEON(a []byte, b []byte) byte {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffUint8NEON(a[:n:n], b)
}

func DiffUint8NEON(dst []byte, a []byte) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint8NEON(dst, a)
}

func MinrUint16NEON(a []uint16) uint16 {
	if len(a) < 16 {
		return ref.MinReduceInt(a)
	}
	return minrUint16NEON(a)
}

func MaxrUint16NEON(a []uint16) uint16 {
	if len(a) < 16 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint16NEON(a)
}

func SumsqUint16NEON(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqUint16NEON(a)
}

func SumsqdevUint16NEON(a []uint16, c uint16) uint16 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevUint16NEON(a, c)
}

func SumsqdiffUint16NEON(a []uint16, b []uint16) uint16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffUint16NEON(a[:n:n], b)
}

func DiffUint16NEON(dst []uint16, a []uint16) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint16NEON(dst, a)
}

func MinrUint32NEON(a []uint32) uint32 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrUint32NEON(a)
}

func MaxrUint32NEON(a []uint32) uint32 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint32NEON(a)
}

func SumsqUint32NEON(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqUint32NEON(a)
}

func SumsqdevUint32NEON(a []uint32, c uint32) uint32 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevUint32NEON(a, c)
}

func SumsqdiffUint32NEON(a []uint32, b []uint32) uint32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffUint32NEON(a[:n:n], b)
}

func DiffUint32NEON(dst []uint32, a []uint32) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint32NEON(dst, a)
}

func MinrUint64NEON(a []uint64) uint64 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrUint64NEON(a)
}

func MaxrUint64NEON(a []uint64) uint64 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint64NEON(a)
}

func DiffUint64NEON(dst []uint64, a []uint64) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint64NEON(dst, a)
}

func SumFloat32NEON(a []float32) float32 {
	if len(a) < 0 {
		return ref.SumFloat(a)
	}
	return sumFloat32NEON(a)
}

func DotFloat32NEON(a []float32, b []float32) float32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotFloat(a, b)
	}
	return dotFloat32NEON(a[:n:n], b)
}

func L1normFloat32NEON(a []float32) float32 {
	if len(a) < 0 {
		return ref.L1NormFloat(a)
	}
	return l1normFloat32NEON(a)
}

func L1diffFloat32NEON(a []float32, b []float32) float32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffFloat(a, b)
	}
	return l1diffFloat32NEON(a[:n:n], b)
}

func SumLanesFloat32NEON(dst []float32, a []float32) {
	if len(a) < 0 {
		ref.SumLanesFloat(dst, a)
		return
	}
	sumLanesFloat32NEON(dst, a)
}

func SparseDotFloat32NEON(v []float32, idx []int32, x []float32) float32 {
	if len(x) < 0 {
		return ref.SparseDotFloat(v, idx, x)
	}
	return sparseDotFloat32NEON(v, idx, x)
}

func SumFloat64NEON(a []float64) float64 {
	if len(a) < 0 {
		return ref.SumFloat(a)
	}
	return sumFloat64NEON(a)
}

func DotFloat64NEON(a []float64, b []float64) float64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotFloat(a, b)
	}
	return dotFloat64NEON(a[:n:n], b)
}

func L1normFloat64NEON(a []float64) float64 {
	if len(a) < 0 {
		return ref.L1NormFloat(a)
	}
	return l1normFloat64NEON(a)
}

func L1diffFloat64NEON(a []float64, b []float64) float64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffFloat(a, b)
	}
	return l1diffFloat64NEON(a[:n:n], b)
}

func SumLanesFloat64NEON(dst []float64, a []float64) {
	if len(a) < 0 {
		ref.SumLanesFloat(dst, a)
		return
	}
	sumLanesFloat64NEON(dst, a)
}

func SparseDotFloat64NEON(v []float64, idx []int32, x []float64) float64 {
	if len(x) < 0 {
		return ref.SparseDotFloat(v, idx, x)
	}
	return sparseDotFloat64NEON(v, idx, x)
}

func SumInt32NEON(a []int32) int32 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt32NEON(a)
}

func ProdInt32NEON(a []int32) int32 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodInt32NEON(a)
}

func DotInt32NEON(a []int32, b []int32) int32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotInt32NEON(a[:n:n], b)
}

func L1normInt32NEON(a []int32) int32 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt32NEON(a)
}

func L1diffInt32NEON(a []int32, b []int32) int32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt32NEON(a[:n:n], b)
}

func SumInt64NEON(a []int64) int64 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt64NEON(a)
}

func L1normInt64NEON(a []int64) int64 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt64NEON(a)
}

func L1diffInt64NEON(a []int64, b []int64) int64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt64NEON(a[:n:n], b)
}

func SumInt8NEON(a []int8) int8 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt8NEON(a)
}

func ProdInt8NEON(a []int8) int8 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodInt8NEON(a)
}

func DotInt8NEON(a []int8, b []int8) int8 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotInt8NEON(a[:n:n], b)
}

func L1normInt8NEON(a []int8) int8 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt8NEON(a)
}

func L1diffInt8NEON(a []int8, b []int8) int8 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt8NEON(a[:n:n], b)
}

func SumInt16NEON(a []int16) int16 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt16NEON(a)
}

func ProdInt16NEON(a []int16) int16 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodInt16NEON(a)
}

func DotInt16NEON(a []int16, b []int16) int16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotInt16NEON(a[:n:n], b)
}

func L1normInt16NEON(a []int16) int16 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt16NEON(a)
}

func L1diffInt16NEON(a []int16, b []int16) int16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt16NEON(a[:n:n], b)
}

func SumUint8NEON(a []byte) byte {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint8NEON(a)
}

func ProdUint8NEON(a []byte) byte {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodUint8NEON(a)
}

func DotUint8NEON(a []byte, b []byte) byte {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotUint8NEON(a[:n:n], b)
}

func L1normUint8NEON(a []byte) byte {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint8NEON(a)
}

func L1diffUint8NEON(a []byte, b []byte) byte {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint8NEON(a[:n:n], b)
}

func SumUint16NEON(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint16NEON(a)
}

func ProdUint16NEON(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodUint16NEON(a)
}

func DotUint16NEON(a []uint16, b []uint16) uint16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotUint16NEON(a[:n:n], b)
}

func L1normUint16NEON(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint16NEON(a)
}

func L1diffUint16NEON(a []uint16, b []uint16) uint16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint16NEON(a[:n:n], b)
}

func SumUint32NEON(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint32NEON(a)
}

func ProdUint32NEON(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodUint32NEON(a)
}

func DotUint32NEON(a []uint32, b []uint32) uint32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotUint32NEON(a[:n:n], b)
}

func L1normUint32NEON(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint32NEON(a)
}

func L1diffUint32NEON(a []uint32, b []uint32) uint32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint32NEON(a[:n:n], b)
}

func SumUint64NEON(a []uint64) uint64 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint64NEON(a)
}

func L1normUint64NEON(a []uint64) uint64 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint64NEON(a)
}

func L1diffUint64NEON(a []uint64, b []uint64) uint64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint64NEON(a[:n:n], b)
}

func registerReduceNEON(s *kernel.Set) {
	s.F32.Min = MinrFloat32NEON
	s.F32.Max = MaxrFloat32NEON
	s.F32.SumSquares = SumsqFloat32NEON
	s.F32.SumSqDev = SumsqdevFloat32NEON
	s.F32.SumSqDiff = SumsqdiffFloat32NEON
	s.F32.Diff = DiffFloat32NEON
	s.F64.Min = MinrFloat64NEON
	s.F64.Max = MaxrFloat64NEON
	s.F64.SumSquares = SumsqFloat64NEON
	s.F64.SumSqDev = SumsqdevFloat64NEON
	s.F64.SumSqDiff = SumsqdiffFloat64NEON
	s.F64.Diff = DiffFloat64NEON
	s.I32.Min = MinrInt32NEON
	s.I32.Max = MaxrInt32NEON
	s.I32.SumSquares = SumsqInt32NEON
	s.I32.SumSqDev = SumsqdevInt32NEON
	s.I32.SumSqDiff = SumsqdiffInt32NEON
	s.I32.Diff = DiffInt32NEON
	s.I64.Min = MinrInt64NEON
	s.I64.Max = MaxrInt64NEON
	s.I64.Diff = DiffInt64NEON
	s.I8.Min = MinrInt8NEON
	s.I8.Max = MaxrInt8NEON
	s.I8.SumSquares = SumsqInt8NEON
	s.I8.SumSqDev = SumsqdevInt8NEON
	s.I8.SumSqDiff = SumsqdiffInt8NEON
	s.I8.Diff = DiffInt8NEON
	s.I16.Min = MinrInt16NEON
	s.I16.Max = MaxrInt16NEON
	s.I16.SumSquares = SumsqInt16NEON
	s.I16.SumSqDev = SumsqdevInt16NEON
	s.I16.SumSqDiff = SumsqdiffInt16NEON
	s.I16.Diff = DiffInt16NEON
	s.U8.Min = MinrUint8NEON
	s.U8.Max = MaxrUint8NEON
	s.U8.SumSquares = SumsqUint8NEON
	s.U8.SumSqDev = SumsqdevUint8NEON
	s.U8.SumSqDiff = SumsqdiffUint8NEON
	s.U8.Diff = DiffUint8NEON
	s.U16.Min = MinrUint16NEON
	s.U16.Max = MaxrUint16NEON
	s.U16.SumSquares = SumsqUint16NEON
	s.U16.SumSqDev = SumsqdevUint16NEON
	s.U16.SumSqDiff = SumsqdiffUint16NEON
	s.U16.Diff = DiffUint16NEON
	s.U32.Min = MinrUint32NEON
	s.U32.Max = MaxrUint32NEON
	s.U32.SumSquares = SumsqUint32NEON
	s.U32.SumSqDev = SumsqdevUint32NEON
	s.U32.SumSqDiff = SumsqdiffUint32NEON
	s.U32.Diff = DiffUint32NEON
	s.U64.Min = MinrUint64NEON
	s.U64.Max = MaxrUint64NEON
	s.U64.Diff = DiffUint64NEON
	s.F32.Sum = SumFloat32NEON
	s.F32.Dot = DotFloat32NEON
	s.F32.L1Norm = L1normFloat32NEON
	s.F32.L1Diff = L1diffFloat32NEON
	s.F32.SumLanes = SumLanesFloat32NEON
	s.F32.SparseDot = SparseDotFloat32NEON
	s.F64.Sum = SumFloat64NEON
	s.F64.Dot = DotFloat64NEON
	s.F64.L1Norm = L1normFloat64NEON
	s.F64.L1Diff = L1diffFloat64NEON
	s.F64.SumLanes = SumLanesFloat64NEON
	s.F64.SparseDot = SparseDotFloat64NEON
	s.I32.Sum = SumInt32NEON
	s.I32.Prod = ProdInt32NEON
	s.I32.Dot = DotInt32NEON
	s.I32.L1Norm = L1normInt32NEON
	s.I32.L1Diff = L1diffInt32NEON
	s.I64.Sum = SumInt64NEON
	s.I64.L1Norm = L1normInt64NEON
	s.I64.L1Diff = L1diffInt64NEON
	s.I8.Sum = SumInt8NEON
	s.I8.Prod = ProdInt8NEON
	s.I8.Dot = DotInt8NEON
	s.I8.L1Norm = L1normInt8NEON
	s.I8.L1Diff = L1diffInt8NEON
	s.I16.Sum = SumInt16NEON
	s.I16.Prod = ProdInt16NEON
	s.I16.Dot = DotInt16NEON
	s.I16.L1Norm = L1normInt16NEON
	s.I16.L1Diff = L1diffInt16NEON
	s.U8.Sum = SumUint8NEON
	s.U8.Prod = ProdUint8NEON
	s.U8.Dot = DotUint8NEON
	s.U8.L1Norm = L1normUint8NEON
	s.U8.L1Diff = L1diffUint8NEON
	s.U16.Sum = SumUint16NEON
	s.U16.Prod = ProdUint16NEON
	s.U16.Dot = DotUint16NEON
	s.U16.L1Norm = L1normUint16NEON
	s.U16.L1Diff = L1diffUint16NEON
	s.U32.Sum = SumUint32NEON
	s.U32.Prod = ProdUint32NEON
	s.U32.Dot = DotUint32NEON
	s.U32.L1Norm = L1normUint32NEON
	s.U32.L1Diff = L1diffUint32NEON
	s.U64.Sum = SumUint64NEON
	s.U64.L1Norm = L1normUint64NEON
	s.U64.L1Diff = L1diffUint64NEON
}
