// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/scan.c
// Target: arm64/neon

//go:build arm64 && !purego

package arm64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for arm64. The build
// constraint above and the _arm64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "arm64": {}}

func RollingMinFloat32NEON(dst []float32, a []float32, window int) {
	if len(dst) < 16 {
		ref.RollingMinFloat(dst, a, window)
		return
	}
	rollingMinFloat32NEON(dst, a, window)
}

func RollingMaxFloat32NEON(dst []float32, a []float32, window int) {
	if len(dst) < 16 {
		ref.RollingMaxFloat(dst, a, window)
		return
	}
	rollingMaxFloat32NEON(dst, a, window)
}

func FastCumProdFloat32NEON(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.FastCumProdFloat(dst, a)
		return
	}
	fastCumProdFloat32NEON(dst[:n:n], a)
}

func FastCumSumFloat32NEON(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.FastCumSumFloat(dst, a)
		return
	}
	fastCumSumFloat32NEON(dst[:n:n], a)
}

func FastCumProdFloat64NEON(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.FastCumProdFloat(dst, a)
		return
	}
	fastCumProdFloat64NEON(dst[:n:n], a)
}

func RollingMinInt32NEON(dst []int32, a []int32, window int) {
	if len(dst) < 16 {
		ref.RollingMinInt(dst, a, window)
		return
	}
	rollingMinInt32NEON(dst, a, window)
}

func RollingMaxInt32NEON(dst []int32, a []int32, window int) {
	if len(dst) < 16 {
		ref.RollingMaxInt(dst, a, window)
		return
	}
	rollingMaxInt32NEON(dst, a, window)
}

func CumMinInt32NEON(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMinInt(dst, a)
		return
	}
	cumMinInt32NEON(dst[:n:n], a)
}

func CumMaxInt32NEON(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMaxInt(dst, a)
		return
	}
	cumMaxInt32NEON(dst[:n:n], a)
}

func CumProdInt32NEON(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumProdInt(dst, a)
		return
	}
	cumProdInt32NEON(dst[:n:n], a)
}

func RollingMinInt64NEON(dst []int64, a []int64, window int) {
	if len(dst) < 16 {
		ref.RollingMinInt(dst, a, window)
		return
	}
	rollingMinInt64NEON(dst, a, window)
}

func RollingMaxInt64NEON(dst []int64, a []int64, window int) {
	if len(dst) < 16 {
		ref.RollingMaxInt(dst, a, window)
		return
	}
	rollingMaxInt64NEON(dst, a, window)
}

func CumMinInt64NEON(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMinInt(dst, a)
		return
	}
	cumMinInt64NEON(dst[:n:n], a)
}

func CumMaxInt64NEON(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMaxInt(dst, a)
		return
	}
	cumMaxInt64NEON(dst[:n:n], a)
}

func RleDecodeI32NEON(dst []int32, values []int32, counts []int32) int {
	if len(dst) < 0 || len(values) != len(counts) {
		return ref.RLEDecodeInt32(dst, values, counts)
	}
	return rleDecodeI32NEON(dst, values, counts)
}

func registerScanNEON(s *kernel.Set) {
	s.F32.RollingMin = RollingMinFloat32NEON
	s.F32.RollingMax = RollingMaxFloat32NEON
	s.F32.FastCumProd = FastCumProdFloat32NEON
	s.F32.FastCumSum = FastCumSumFloat32NEON
	s.F64.FastCumProd = FastCumProdFloat64NEON
	s.I32.RollingMin = RollingMinInt32NEON
	s.I32.RollingMax = RollingMaxInt32NEON
	s.I32.CumMin = CumMinInt32NEON
	s.I32.CumMax = CumMaxInt32NEON
	s.I32.CumProd = CumProdInt32NEON
	s.I64.RollingMin = RollingMinInt64NEON
	s.I64.RollingMax = RollingMaxInt64NEON
	s.I64.CumMin = CumMinInt64NEON
	s.I64.CumMax = CumMaxInt64NEON
	s.Bytes.RLEDecodeInt32 = RleDecodeI32NEON
}
