// Code generated by simdgen. DO NOT EDIT.
//
// Whole-set assembly for the conformance and coverage machinery. Tests
// call this; consumers never do, so none of it is linked into their
// binaries and the per-operation dispatch tables keep their dead-code
// elimination.

//go:build arm64 && !purego

package arm64

import (
	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Sets returns every tier's complete kernel set, the reference standing
// in for anything not generated, in accelerated-tier order.
func Sets() map[string]kernel.Set {
	out := map[string]kernel.Set{}
	{
		s := ref.Set()
		s.Name = "neon"
		registerBlasNEON(&s)
		registerCompressNEON(&s)
		registerColumnarNEON(&s)
		registerSetsNEON(&s)
		registerGemmNEON(&s)
		registerNaryNEON(&s)
		registerArgreduceNEON(&s)
		registerScanNEON(&s)
		registerArithNEON(&s)
		registerReduceNEON(&s)
		registerCompareNEON(&s)
		registerBytesNEON(&s)
		registerMathNEON(&s)
		registerNumericNEON(&s)
		registerComplexNEON(&s)
		registerConvertNEON(&s)
		registerFastmathNEON(&s)
		ref.FillFastFallbacks(&s)
		out["neon"] = s
	}
	{
		s := ref.Set()
		s.Name = "sve2"
		registerBlasSVE2(&s)
		registerCompressSVE2(&s)
		registerColumnarSVE2(&s)
		registerSetsSVE2(&s)
		registerGemmSVE2(&s)
		registerNarySVE2(&s)
		registerSortSVE2(&s)
		registerArgreduceSVE2(&s)
		registerScanSVE2(&s)
		registerArithSVE2(&s)
		registerReduceSVE2(&s)
		registerCompareSVE2(&s)
		registerBytesSVE2(&s)
		registerMathSVE2(&s)
		registerNumericSVE2(&s)
		registerComplexSVE2(&s)
		registerConvertSVE2(&s)
		registerFastmathSVE2(&s)
		ref.FillFastFallbacks(&s)
		out["sve2"] = s
	}
	return out
}

// TierOrder is the accelerated tier order Sets covers.
var TierOrder = [...]string{"neon", "sve2"}
