// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/columnar.c
// Target: loong64/lasx

//go:build loong64 && !purego

package loong64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for loong64. The build
// constraint above and the _loong64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "loong64": {}}

func SumValidFloat32LASX(a []float32, bm []byte) float32 {
	if len(a) < 0 || len(bm) < (len(a)+7)/8 {
		return ref.SumValidFloat32(a, bm)
	}
	return sumValidFloat32LASX(a, bm)
}

func SumValidFloat64LASX(a []float64, bm []byte) float64 {
	if len(a) < 0 || len(bm) < (len(a)+7)/8 {
		return ref.SumValidFloat64(a, bm)
	}
	return sumValidFloat64LASX(a, bm)
}

func SumValidInt32LASX(a []int32, bm []byte) int32 {
	if len(a) < 0 || len(bm) < (len(a)+7)/8 {
		return ref.SumValidInt32(a, bm)
	}
	return sumValidInt32LASX(a, bm)
}

func SumValidInt64LASX(a []int64, bm []byte) int64 {
	if len(a) < 0 || len(bm) < (len(a)+7)/8 {
		return ref.SumValidInt64(a, bm)
	}
	return sumValidInt64LASX(a, bm)
}

func registerColumnarLASX(s *kernel.Set) {
	s.F32.SumValid = SumValidFloat32LASX
	s.F64.SumValid = SumValidFloat64LASX
	s.I32.SumValid = SumValidInt32LASX
	s.I64.SumValid = SumValidInt64LASX
}
