// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/compare.c
// Target: loong64/lasx

//go:build loong64 && !purego

package loong64

import "runtime"

// Compile-time check that this file is only ever built for loong64. The build
// constraint above and the _loong64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "loong64": {}}

//go:noescape
func eqFloat32MaskLASX(dst []bool, a []float32, b []float32)

//go:noescape
func eqScalarFloat32MaskLASX(dst []bool, a []float32, v float32)

//go:noescape
func neFloat32MaskLASX(dst []bool, a []float32, b []float32)

//go:noescape
func neScalarFloat32MaskLASX(dst []bool, a []float32, v float32)

//go:noescape
func ltFloat32MaskLASX(dst []bool, a []float32, b []float32)

//go:noescape
func ltScalarFloat32MaskLASX(dst []bool, a []float32, v float32)

//go:noescape
func leFloat32MaskLASX(dst []bool, a []float32, b []float32)

//go:noescape
func leScalarFloat32MaskLASX(dst []bool, a []float32, v float32)

//go:noescape
func gtFloat32MaskLASX(dst []bool, a []float32, b []float32)

//go:noescape
func gtScalarFloat32MaskLASX(dst []bool, a []float32, v float32)

//go:noescape
func geFloat32MaskLASX(dst []bool, a []float32, b []float32)

//go:noescape
func geScalarFloat32MaskLASX(dst []bool, a []float32, v float32)

//go:noescape
func selectFloat32LASX(dst []float32, mask []bool, yes []float32, no []float32)

//go:noescape
func lowerBoundFloat32LASX(dst []int32, a []float32, q []float32)

//go:noescape
func eqFloat64MaskLASX(dst []bool, a []float64, b []float64)

//go:noescape
func eqScalarFloat64MaskLASX(dst []bool, a []float64, v float64)

//go:noescape
func neFloat64MaskLASX(dst []bool, a []float64, b []float64)

//go:noescape
func neScalarFloat64MaskLASX(dst []bool, a []float64, v float64)

//go:noescape
func ltFloat64MaskLASX(dst []bool, a []float64, b []float64)

//go:noescape
func ltScalarFloat64MaskLASX(dst []bool, a []float64, v float64)

//go:noescape
func leFloat64MaskLASX(dst []bool, a []float64, b []float64)

//go:noescape
func leScalarFloat64MaskLASX(dst []bool, a []float64, v float64)

//go:noescape
func gtFloat64MaskLASX(dst []bool, a []float64, b []float64)

//go:noescape
func gtScalarFloat64MaskLASX(dst []bool, a []float64, v float64)

//go:noescape
func geFloat64MaskLASX(dst []bool, a []float64, b []float64)

//go:noescape
func geScalarFloat64MaskLASX(dst []bool, a []float64, v float64)

//go:noescape
func selectFloat64LASX(dst []float64, mask []bool, yes []float64, no []float64)

//go:noescape
func lowerBoundFloat64LASX(dst []int32, a []float64, q []float64)

//go:noescape
func eqInt32MaskLASX(dst []bool, a []int32, b []int32)

//go:noescape
func eqScalarInt32MaskLASX(dst []bool, a []int32, v int32)

//go:noescape
func neInt32MaskLASX(dst []bool, a []int32, b []int32)

//go:noescape
func neScalarInt32MaskLASX(dst []bool, a []int32, v int32)

//go:noescape
func ltInt32MaskLASX(dst []bool, a []int32, b []int32)

//go:noescape
func ltScalarInt32MaskLASX(dst []bool, a []int32, v int32)

//go:noescape
func leInt32MaskLASX(dst []bool, a []int32, b []int32)

//go:noescape
func leScalarInt32MaskLASX(dst []bool, a []int32, v int32)

//go:noescape
func gtInt32MaskLASX(dst []bool, a []int32, b []int32)

//go:noescape
func gtScalarInt32MaskLASX(dst []bool, a []int32, v int32)

//go:noescape
func geInt32MaskLASX(dst []bool, a []int32, b []int32)

//go:noescape
func geScalarInt32MaskLASX(dst []bool, a []int32, v int32)

//go:noescape
func selectInt32LASX(dst []int32, mask []bool, yes []int32, no []int32)

//go:noescape
func lowerBoundInt32LASX(dst []int32, a []int32, q []int32)

//go:noescape
func eqInt64MaskLASX(dst []bool, a []int64, b []int64)

//go:noescape
func eqScalarInt64MaskLASX(dst []bool, a []int64, v int64)

//go:noescape
func neInt64MaskLASX(dst []bool, a []int64, b []int64)

//go:noescape
func neScalarInt64MaskLASX(dst []bool, a []int64, v int64)

//go:noescape
func ltInt64MaskLASX(dst []bool, a []int64, b []int64)

//go:noescape
func ltScalarInt64MaskLASX(dst []bool, a []int64, v int64)

//go:noescape
func leInt64MaskLASX(dst []bool, a []int64, b []int64)

//go:noescape
func leScalarInt64MaskLASX(dst []bool, a []int64, v int64)

//go:noescape
func gtInt64MaskLASX(dst []bool, a []int64, b []int64)

//go:noescape
func gtScalarInt64MaskLASX(dst []bool, a []int64, v int64)

//go:noescape
func geInt64MaskLASX(dst []bool, a []int64, b []int64)

//go:noescape
func geScalarInt64MaskLASX(dst []bool, a []int64, v int64)

//go:noescape
func selectInt64LASX(dst []int64, mask []bool, yes []int64, no []int64)

//go:noescape
func lowerBoundInt64LASX(dst []int32, a []int64, q []int64)

//go:noescape
func eqInt8MaskLASX(dst []bool, a []int8, b []int8)

//go:noescape
func eqScalarInt8MaskLASX(dst []bool, a []int8, v int8)

//go:noescape
func neInt8MaskLASX(dst []bool, a []int8, b []int8)

//go:noescape
func neScalarInt8MaskLASX(dst []bool, a []int8, v int8)

//go:noescape
func ltInt8MaskLASX(dst []bool, a []int8, b []int8)

//go:noescape
func ltScalarInt8MaskLASX(dst []bool, a []int8, v int8)

//go:noescape
func leInt8MaskLASX(dst []bool, a []int8, b []int8)

//go:noescape
func leScalarInt8MaskLASX(dst []bool, a []int8, v int8)

//go:noescape
func gtInt8MaskLASX(dst []bool, a []int8, b []int8)

//go:noescape
func gtScalarInt8MaskLASX(dst []bool, a []int8, v int8)

//go:noescape
func geInt8MaskLASX(dst []bool, a []int8, b []int8)

//go:noescape
func geScalarInt8MaskLASX(dst []bool, a []int8, v int8)

//go:noescape
func selectInt8LASX(dst []int8, mask []bool, yes []int8, no []int8)

//go:noescape
func lowerBoundInt8LASX(dst []int32, a []int8, q []int8)

//go:noescape
func eqInt16MaskLASX(dst []bool, a []int16, b []int16)

//go:noescape
func eqScalarInt16MaskLASX(dst []bool, a []int16, v int16)

//go:noescape
func neInt16MaskLASX(dst []bool, a []int16, b []int16)

//go:noescape
func neScalarInt16MaskLASX(dst []bool, a []int16, v int16)

//go:noescape
func ltInt16MaskLASX(dst []bool, a []int16, b []int16)

//go:noescape
func ltScalarInt16MaskLASX(dst []bool, a []int16, v int16)

//go:noescape
func leInt16MaskLASX(dst []bool, a []int16, b []int16)

//go:noescape
func leScalarInt16MaskLASX(dst []bool, a []int16, v int16)

//go:noescape
func gtInt16MaskLASX(dst []bool, a []int16, b []int16)

//go:noescape
func gtScalarInt16MaskLASX(dst []bool, a []int16, v int16)

//go:noescape
func geInt16MaskLASX(dst []bool, a []int16, b []int16)

//go:noescape
func geScalarInt16MaskLASX(dst []bool, a []int16, v int16)

//go:noescape
func selectInt16LASX(dst []int16, mask []bool, yes []int16, no []int16)

//go:noescape
func lowerBoundInt16LASX(dst []int32, a []int16, q []int16)

//go:noescape
func eqUint8MaskLASX(dst []bool, a []byte, b []byte)

//go:noescape
func eqScalarUint8MaskLASX(dst []bool, a []byte, v byte)

//go:noescape
func neUint8MaskLASX(dst []bool, a []byte, b []byte)

//go:noescape
func neScalarUint8MaskLASX(dst []bool, a []byte, v byte)

//go:noescape
func ltUint8MaskLASX(dst []bool, a []byte, b []byte)

//go:noescape
func ltScalarUint8MaskLASX(dst []bool, a []byte, v byte)

//go:noescape
func leUint8MaskLASX(dst []bool, a []byte, b []byte)

//go:noescape
func leScalarUint8MaskLASX(dst []bool, a []byte, v byte)

//go:noescape
func gtUint8MaskLASX(dst []bool, a []byte, b []byte)

//go:noescape
func gtScalarUint8MaskLASX(dst []bool, a []byte, v byte)

//go:noescape
func geUint8MaskLASX(dst []bool, a []byte, b []byte)

//go:noescape
func geScalarUint8MaskLASX(dst []bool, a []byte, v byte)

//go:noescape
func selectUint8LASX(dst []byte, mask []bool, yes []byte, no []byte)

//go:noescape
func lowerBoundUint8LASX(dst []int32, a []byte, q []byte)

//go:noescape
func eqUint16MaskLASX(dst []bool, a []uint16, b []uint16)

//go:noescape
func eqScalarUint16MaskLASX(dst []bool, a []uint16, v uint16)

//go:noescape
func neUint16MaskLASX(dst []bool, a []uint16, b []uint16)

//go:noescape
func neScalarUint16MaskLASX(dst []bool, a []uint16, v uint16)

//go:noescape
func ltUint16MaskLASX(dst []bool, a []uint16, b []uint16)

//go:noescape
func ltScalarUint16MaskLASX(dst []bool, a []uint16, v uint16)

//go:noescape
func leUint16MaskLASX(dst []bool, a []uint16, b []uint16)

//go:noescape
func leScalarUint16MaskLASX(dst []bool, a []uint16, v uint16)

//go:noescape
func gtUint16MaskLASX(dst []bool, a []uint16, b []uint16)

//go:noescape
func gtScalarUint16MaskLASX(dst []bool, a []uint16, v uint16)

//go:noescape
func geUint16MaskLASX(dst []bool, a []uint16, b []uint16)

//go:noescape
func geScalarUint16MaskLASX(dst []bool, a []uint16, v uint16)

//go:noescape
func selectUint16LASX(dst []uint16, mask []bool, yes []uint16, no []uint16)

//go:noescape
func lowerBoundUint16LASX(dst []int32, a []uint16, q []uint16)

//go:noescape
func eqUint32MaskLASX(dst []bool, a []uint32, b []uint32)

//go:noescape
func eqScalarUint32MaskLASX(dst []bool, a []uint32, v uint32)

//go:noescape
func neUint32MaskLASX(dst []bool, a []uint32, b []uint32)

//go:noescape
func neScalarUint32MaskLASX(dst []bool, a []uint32, v uint32)

//go:noescape
func ltUint32MaskLASX(dst []bool, a []uint32, b []uint32)

//go:noescape
func ltScalarUint32MaskLASX(dst []bool, a []uint32, v uint32)

//go:noescape
func leUint32MaskLASX(dst []bool, a []uint32, b []uint32)

//go:noescape
func leScalarUint32MaskLASX(dst []bool, a []uint32, v uint32)

//go:noescape
func gtUint32MaskLASX(dst []bool, a []uint32, b []uint32)

//go:noescape
func gtScalarUint32MaskLASX(dst []bool, a []uint32, v uint32)

//go:noescape
func geUint32MaskLASX(dst []bool, a []uint32, b []uint32)

//go:noescape
func geScalarUint32MaskLASX(dst []bool, a []uint32, v uint32)

//go:noescape
func selectUint32LASX(dst []uint32, mask []bool, yes []uint32, no []uint32)

//go:noescape
func lowerBoundUint32LASX(dst []int32, a []uint32, q []uint32)

//go:noescape
func eqUint64MaskLASX(dst []bool, a []uint64, b []uint64)

//go:noescape
func eqScalarUint64MaskLASX(dst []bool, a []uint64, v uint64)

//go:noescape
func neUint64MaskLASX(dst []bool, a []uint64, b []uint64)

//go:noescape
func neScalarUint64MaskLASX(dst []bool, a []uint64, v uint64)

//go:noescape
func ltUint64MaskLASX(dst []bool, a []uint64, b []uint64)

//go:noescape
func ltScalarUint64MaskLASX(dst []bool, a []uint64, v uint64)

//go:noescape
func leUint64MaskLASX(dst []bool, a []uint64, b []uint64)

//go:noescape
func leScalarUint64MaskLASX(dst []bool, a []uint64, v uint64)

//go:noescape
func gtUint64MaskLASX(dst []bool, a []uint64, b []uint64)

//go:noescape
func gtScalarUint64MaskLASX(dst []bool, a []uint64, v uint64)

//go:noescape
func geUint64MaskLASX(dst []bool, a []uint64, b []uint64)

//go:noescape
func geScalarUint64MaskLASX(dst []bool, a []uint64, v uint64)

//go:noescape
func selectUint64LASX(dst []uint64, mask []bool, yes []uint64, no []uint64)

//go:noescape
func lowerBoundUint64LASX(dst []int32, a []uint64, q []uint64)

//go:noescape
func maskAllLASX(m []bool) bool

//go:noescape
func maskAnyLASX(m []bool) bool

//go:noescape
func maskCountLASX(m []bool) int

//go:noescape
func maskAndLASX(dst []bool, a []bool, b []bool)

//go:noescape
func maskOrLASX(dst []bool, a []bool, b []bool)

//go:noescape
func maskXorLASX(dst []bool, a []bool, b []bool)

//go:noescape
func maskNotLASX(dst []bool, a []bool)
