// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/convert.c
// Target: loong64/lasx

//go:build loong64 && !purego

package loong64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for loong64. The build
// constraint above and the _loong64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "loong64": {}}

func quantizeI8LASXGuarded(dst []int8, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeI8(dst, a, scale, zeroPoint)
		return
	}
	quantizeI8LASX(dst[:n:n], a, scale, zeroPoint)
}

func dequantizeI8LASXGuarded(dst []float32, a []int8, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeI8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeI8LASX(dst[:n:n], a, scale, zeroPoint)
}

func quantizeU8LASXGuarded(dst []byte, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeU8(dst, a, scale, zeroPoint)
		return
	}
	quantizeU8LASX(dst[:n:n], a, scale, zeroPoint)
}

func dequantizeU8LASXGuarded(dst []float32, a []byte, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeU8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeU8LASX(dst[:n:n], a, scale, zeroPoint)
}

func zigzagEncodeI8LASXGuarded(dst []byte, a []int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI8(dst, a)
		return
	}
	zigzagEncodeI8LASX(dst[:n:n], a)
}

func zigzagDecodeI8LASXGuarded(dst []int8, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI8(dst, a)
		return
	}
	zigzagDecodeI8LASX(dst[:n:n], a)
}

func zigzagEncodeI16LASXGuarded(dst []uint16, a []int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI16(dst, a)
		return
	}
	zigzagEncodeI16LASX(dst[:n:n], a)
}

func zigzagDecodeI16LASXGuarded(dst []int16, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI16(dst, a)
		return
	}
	zigzagDecodeI16LASX(dst[:n:n], a)
}

func zigzagEncodeI32LASXGuarded(dst []uint32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI32(dst, a)
		return
	}
	zigzagEncodeI32LASX(dst[:n:n], a)
}

func zigzagDecodeI32LASXGuarded(dst []int32, a []uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI32(dst, a)
		return
	}
	zigzagDecodeI32LASX(dst[:n:n], a)
}

func zigzagEncodeI64LASXGuarded(dst []uint64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagEncodeI64(dst, a)
		return
	}
	zigzagEncodeI64LASX(dst[:n:n], a)
}

func zigzagDecodeI64LASXGuarded(dst []int64, a []uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ZigzagDecodeI64(dst, a)
		return
	}
	zigzagDecodeI64LASX(dst[:n:n], a)
}

func bf16ToF32LASXGuarded(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.BF16ToF32(dst, a)
		return
	}
	bf16ToF32LASX(dst[:n:n], a)
}

func f32ToBF16LASXGuarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToBF16(dst, a)
		return
	}
	f32ToBF16LASX(dst[:n:n], a)
}

func f32ToF16LASXGuarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToF16(dst, a)
		return
	}
	f32ToF16LASX(dst[:n:n], a)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("lasx")
	s.Convert.QuantizeI8 = quantizeI8LASXGuarded
	s.Convert.DequantizeI8 = dequantizeI8LASXGuarded
	s.Convert.QuantizeU8 = quantizeU8LASXGuarded
	s.Convert.DequantizeU8 = dequantizeU8LASXGuarded
	s.Convert.ZigzagEncodeI8 = zigzagEncodeI8LASXGuarded
	s.Convert.ZigzagDecodeI8 = zigzagDecodeI8LASXGuarded
	s.Convert.ZigzagEncodeI16 = zigzagEncodeI16LASXGuarded
	s.Convert.ZigzagDecodeI16 = zigzagDecodeI16LASXGuarded
	s.Convert.ZigzagEncodeI32 = zigzagEncodeI32LASXGuarded
	s.Convert.ZigzagDecodeI32 = zigzagDecodeI32LASXGuarded
	s.Convert.ZigzagEncodeI64 = zigzagEncodeI64LASXGuarded
	s.Convert.ZigzagDecodeI64 = zigzagDecodeI64LASXGuarded
	s.Convert.BF16ToF32 = bf16ToF32LASXGuarded
	s.Convert.F32ToBF16 = f32ToBF16LASXGuarded
	s.Convert.F32ToF16 = f32ToF16LASXGuarded
}
