// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/math.c
// Target: loong64/lasx

//go:build loong64 && !purego

package loong64

import "runtime"

// Compile-time check that this file is only ever built for loong64. The build
// constraint above and the _loong64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "loong64": {}}

//go:noescape
func expFloat64LASX(dst []float64, a []float64)

//go:noescape
func exp2Float64LASX(dst []float64, a []float64)

//go:noescape
func logFloat64LASX(dst []float64, a []float64)

//go:noescape
func log2Float64LASX(dst []float64, a []float64)

//go:noescape
func log10Float64LASX(dst []float64, a []float64)

//go:noescape
func log1pFloat64LASX(dst []float64, a []float64)

//go:noescape
func cbrtFloat64LASX(dst []float64, a []float64)

//go:noescape
func sigmoidFloat64LASX(dst []float64, a []float64)

//go:noescape
func sinFloat64LASX(dst []float64, a []float64)

//go:noescape
func cosFloat64LASX(dst []float64, a []float64)

//go:noescape
func tanFloat64LASX(dst []float64, a []float64)

//go:noescape
func asinFloat64LASX(dst []float64, a []float64)

//go:noescape
func acosFloat64LASX(dst []float64, a []float64)

//go:noescape
func atanFloat64LASX(dst []float64, a []float64)

//go:noescape
func coshFloat64LASX(dst []float64, a []float64)
