// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/numeric.c
// Target: loong64/lasx

//go:build loong64 && !purego

package loong64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for loong64. The build
// constraint above and the _loong64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "loong64": {}}

func NormFloat32LASX(a []float32) float32 {
	if len(a) < 0 {
		return ref.NormFloat(a)
	}
	return normFloat32LASX(a)
}

func PolyEvalFloat32LASX(dst []float32, x []float32, coeffs []float32) {
	if len(dst) < 16 {
		ref.PolyEval(dst, x, coeffs)
		return
	}
	polyEvalFloat32LASX(dst, x, coeffs)
}

func ConvolveFloat32LASX(dst []float32, sig []float32, ker []float32) {
	if len(dst) < 16 {
		ref.Convolve(dst, sig, ker)
		return
	}
	convolveFloat32LASX(dst, sig, ker)
}

func CorrelateFloat32LASX(dst []float32, sig []float32, ker []float32) {
	if len(dst) < 16 {
		ref.Correlate(dst, sig, ker)
		return
	}
	correlateFloat32LASX(dst, sig, ker)
}

func NormFloat64LASX(a []float64) float64 {
	if len(a) < 0 {
		return ref.NormFloat(a)
	}
	return normFloat64LASX(a)
}

func PolyEvalFloat64LASX(dst []float64, x []float64, coeffs []float64) {
	if len(dst) < 16 {
		ref.PolyEval(dst, x, coeffs)
		return
	}
	polyEvalFloat64LASX(dst, x, coeffs)
}

func ConvolveFloat64LASX(dst []float64, sig []float64, ker []float64) {
	if len(dst) < 16 {
		ref.Convolve(dst, sig, ker)
		return
	}
	convolveFloat64LASX(dst, sig, ker)
}

func CorrelateFloat64LASX(dst []float64, sig []float64, ker []float64) {
	if len(dst) < 16 {
		ref.Correlate(dst, sig, ker)
		return
	}
	correlateFloat64LASX(dst, sig, ker)
}

func TileFloat32LASX(dst []float32, pattern []float32) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileFloat32LASX(dst, pattern)
}

func GatherFloat32LASX(dst []float32, src []float32, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherFloat32LASX(dst, src, idx)
}

func TileFloat64LASX(dst []float64, pattern []float64) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileFloat64LASX(dst, pattern)
}

func GatherFloat64LASX(dst []float64, src []float64, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherFloat64LASX(dst, src, idx)
}

func TileInt32LASX(dst []int32, pattern []int32) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileInt32LASX(dst, pattern)
}

func GatherInt32LASX(dst []int32, src []int32, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherInt32LASX(dst, src, idx)
}

func TileInt64LASX(dst []int64, pattern []int64) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileInt64LASX(dst, pattern)
}

func GatherInt64LASX(dst []int64, src []int64, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherInt64LASX(dst, src, idx)
}

func TileInt8LASX(dst []int8, pattern []int8) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileInt8LASX(dst, pattern)
}

func GatherInt8LASX(dst []int8, src []int8, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherInt8LASX(dst, src, idx)
}

func TileInt16LASX(dst []int16, pattern []int16) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileInt16LASX(dst, pattern)
}

func GatherInt16LASX(dst []int16, src []int16, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherInt16LASX(dst, src, idx)
}

func TileUint8LASX(dst []byte, pattern []byte) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileUint8LASX(dst, pattern)
}

func GatherUint8LASX(dst []byte, src []byte, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherUint8LASX(dst, src, idx)
}

func TileUint16LASX(dst []uint16, pattern []uint16) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileUint16LASX(dst, pattern)
}

func GatherUint16LASX(dst []uint16, src []uint16, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherUint16LASX(dst, src, idx)
}

func TileUint32LASX(dst []uint32, pattern []uint32) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileUint32LASX(dst, pattern)
}

func GatherUint32LASX(dst []uint32, src []uint32, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherUint32LASX(dst, src, idx)
}

func TileUint64LASX(dst []uint64, pattern []uint64) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileUint64LASX(dst, pattern)
}

func GatherUint64LASX(dst []uint64, src []uint64, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherUint64LASX(dst, src, idx)
}

func ShiftDivFloat32LASX(dst []float32, a []float32, shift float32, denom float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ShiftDiv(dst, a, shift, denom)
		return
	}
	shiftDivFloat32LASX(dst[:n:n], a, shift, denom)
}

func LayerNormFloat32LASX(dst []float32, a []float32, gamma []float32, beta []float32, shift float32, denom float32) {
	n := min(len(dst), len(a), len(gamma), len(beta))
	if n < 16 {
		ref.LayerNorm(dst, a, gamma, beta, shift, denom)
		return
	}
	layerNormFloat32LASX(dst[:n:n], a, gamma, beta, shift, denom)
}

func ShiftDivFloat64LASX(dst []float64, a []float64, shift float64, denom float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ShiftDiv(dst, a, shift, denom)
		return
	}
	shiftDivFloat64LASX(dst[:n:n], a, shift, denom)
}

func LayerNormFloat64LASX(dst []float64, a []float64, gamma []float64, beta []float64, shift float64, denom float64) {
	n := min(len(dst), len(a), len(gamma), len(beta))
	if n < 16 {
		ref.LayerNorm(dst, a, gamma, beta, shift, denom)
		return
	}
	layerNormFloat64LASX(dst[:n:n], a, gamma, beta, shift, denom)
}

func RandomU64LASX(dst []uint64, seed uint64) {
	if len(dst) < 16 {
		ref.RandomU64(dst, seed)
		return
	}
	randomU64LASX(dst, seed)
}

func RandomF64LASX(dst []float64, seed uint64) {
	if len(dst) < 16 {
		ref.RandomF64(dst, seed)
		return
	}
	randomF64LASX(dst, seed)
}

func RandomF32LASX(dst []float32, seed uint64) {
	if len(dst) < 16 {
		ref.RandomF32(dst, seed)
		return
	}
	randomF32LASX(dst, seed)
}

func registerNumericLASX(s *kernel.Set) {
	s.F32.Norm = NormFloat32LASX
	s.F32.PolyEval = PolyEvalFloat32LASX
	s.F32.Convolve = ConvolveFloat32LASX
	s.F32.Correlate = CorrelateFloat32LASX
	s.F64.Norm = NormFloat64LASX
	s.F64.PolyEval = PolyEvalFloat64LASX
	s.F64.Convolve = ConvolveFloat64LASX
	s.F64.Correlate = CorrelateFloat64LASX
	s.F32.Tile = TileFloat32LASX
	s.F32.Gather = GatherFloat32LASX
	s.F64.Tile = TileFloat64LASX
	s.F64.Gather = GatherFloat64LASX
	s.I32.Tile = TileInt32LASX
	s.I32.Gather = GatherInt32LASX
	s.I64.Tile = TileInt64LASX
	s.I64.Gather = GatherInt64LASX
	s.I8.Tile = TileInt8LASX
	s.I8.Gather = GatherInt8LASX
	s.I16.Tile = TileInt16LASX
	s.I16.Gather = GatherInt16LASX
	s.U8.Tile = TileUint8LASX
	s.U8.Gather = GatherUint8LASX
	s.U16.Tile = TileUint16LASX
	s.U16.Gather = GatherUint16LASX
	s.U32.Tile = TileUint32LASX
	s.U32.Gather = GatherUint32LASX
	s.U64.Tile = TileUint64LASX
	s.U64.Gather = GatherUint64LASX
	s.F32.ShiftDiv = ShiftDivFloat32LASX
	s.F32.LayerNorm = LayerNormFloat32LASX
	s.F64.ShiftDiv = ShiftDivFloat64LASX
	s.F64.LayerNorm = LayerNormFloat64LASX
	s.U64.Random = RandomU64LASX
	s.F64.Random = RandomF64LASX
	s.F32.Random = RandomF32LASX
}
