// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/numeric.c
// Target: loong64/lasx

//go:build loong64 && !purego

package loong64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for loong64. The build
// constraint above and the _loong64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "loong64": {}}

func normFloat32LASXGuarded(a []float32) float32 {
	if len(a) < 0 {
		return ref.NormFloat(a)
	}
	return normFloat32LASX(a)
}

func polyEvalFloat32LASXGuarded(dst []float32, x []float32, coeffs []float32) {
	if len(dst) < 16 {
		ref.PolyEval(dst, x, coeffs)
		return
	}
	polyEvalFloat32LASX(dst, x, coeffs)
}

func convolveFloat32LASXGuarded(dst []float32, sig []float32, ker []float32) {
	if len(dst) < 16 {
		ref.Convolve(dst, sig, ker)
		return
	}
	convolveFloat32LASX(dst, sig, ker)
}

func correlateFloat32LASXGuarded(dst []float32, sig []float32, ker []float32) {
	if len(dst) < 16 {
		ref.Correlate(dst, sig, ker)
		return
	}
	correlateFloat32LASX(dst, sig, ker)
}

func normFloat64LASXGuarded(a []float64) float64 {
	if len(a) < 0 {
		return ref.NormFloat(a)
	}
	return normFloat64LASX(a)
}

func polyEvalFloat64LASXGuarded(dst []float64, x []float64, coeffs []float64) {
	if len(dst) < 16 {
		ref.PolyEval(dst, x, coeffs)
		return
	}
	polyEvalFloat64LASX(dst, x, coeffs)
}

func convolveFloat64LASXGuarded(dst []float64, sig []float64, ker []float64) {
	if len(dst) < 16 {
		ref.Convolve(dst, sig, ker)
		return
	}
	convolveFloat64LASX(dst, sig, ker)
}

func correlateFloat64LASXGuarded(dst []float64, sig []float64, ker []float64) {
	if len(dst) < 16 {
		ref.Correlate(dst, sig, ker)
		return
	}
	correlateFloat64LASX(dst, sig, ker)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("lasx")
	s.F32.Norm = normFloat32LASXGuarded
	s.F32.PolyEval = polyEvalFloat32LASXGuarded
	s.F32.Convolve = convolveFloat32LASXGuarded
	s.F32.Correlate = correlateFloat32LASXGuarded
	s.F64.Norm = normFloat64LASXGuarded
	s.F64.PolyEval = polyEvalFloat64LASXGuarded
	s.F64.Convolve = convolveFloat64LASXGuarded
	s.F64.Correlate = correlateFloat64LASXGuarded
}
