// Code generated by simdgen. DO NOT EDIT.
//
// Whole-set assembly for the conformance and coverage machinery. Tests
// call this; consumers never do, so none of it is linked into their
// binaries and the per-operation dispatch tables keep their dead-code
// elimination.

//go:build loong64 && !purego

package loong64

import (
	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Sets returns every tier's complete kernel set, the reference standing
// in for anything not generated, in accelerated-tier order.
func Sets() map[string]kernel.Set {
	out := map[string]kernel.Set{}
	{
		s := ref.Set()
		s.Name = "lasx"
		registerBlasLASX(&s)
		registerCompressLASX(&s)
		registerColumnarLASX(&s)
		registerRandomLASX(&s)
		registerShuffleLASX(&s)
		registerBitunpackLASX(&s)
		registerSetsLASX(&s)
		registerGemmLASX(&s)
		registerNaryLASX(&s)
		registerArgreduceLASX(&s)
		registerScanLASX(&s)
		registerArithLASX(&s)
		registerReduceLASX(&s)
		registerCompareLASX(&s)
		registerBytesLASX(&s)
		registerMathLASX(&s)
		registerNumericLASX(&s)
		registerComplexLASX(&s)
		registerConvertLASX(&s)
		registerFastmathLASX(&s)
		ref.FillFastFallbacks(&s)
		out["lasx"] = s
	}
	return out
}

// TierOrder is the accelerated tier order Sets covers.
var TierOrder = [...]string{"lasx"}
