// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/bytes.c
// Target: amd64/avx512

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func CountByteAVX512(b []byte, c byte) int {
	if len(b) < 1073741824 {
		return ref.CountByte(b, c)
	}
	return countByteAVX512(b, c)
}

func IndexByteAVX512(b []byte, c byte) int {
	if len(b) < 1024 {
		return ref.IndexByte(b, c)
	}
	return indexByteAVX512(b, c)
}

func LastIndexByteAVX512(b []byte, c byte) int {
	if len(b) < 64 {
		return ref.LastIndexByte(b, c)
	}
	return lastIndexByteAVX512(b, c)
}

func PopCountAVX512(b []byte) int {
	if len(b) < 64 {
		return ref.PopCount(b)
	}
	return popCountAVX512(b)
}

func MaskBitsAVX512(dst []byte, b []byte, c byte) {
	if len(b) < 64 {
		ref.MaskBits(dst, b, c)
		return
	}
	maskBitsAVX512(dst, b, c)
}

func MaskBitsLessAVX512(dst []byte, b []byte, c byte) {
	if len(b) < 64 {
		ref.MaskBitsLess(dst, b, c)
		return
	}
	maskBitsLessAVX512(dst, b, c)
}

func MaskBitsAny4AVX512(dst []byte, b []byte, chars uint32) {
	if len(b) < 64 {
		ref.MaskBitsAny4(dst, b, chars)
		return
	}
	maskBitsAny4AVX512(dst, b, chars)
}

func MaskBitsAnyAVX512(dst []byte, b []byte, chars uint64) {
	if len(b) < 64 {
		ref.MaskBitsAny(dst, b, chars)
		return
	}
	maskBitsAnyAVX512(dst, b, chars)
}

func HammingU8AVX512(a []byte, b []byte) int {
	n := min(len(a), len(b))
	if n < 64 {
		return ref.Hamming(a, b)
	}
	return hammingU8AVX512(a[:n:n], b)
}

func HammingU64AVX512(a []uint64, b []uint64) int {
	n := min(len(a), len(b))
	if n < 64 {
		return ref.HammingWords(a, b)
	}
	return hammingU64AVX512(a[:n:n], b)
}

func GrayscaleU8AVX512(dst []byte, r []byte, g []byte, b []byte) {
	n := min(len(dst), len(r), len(g), len(b))
	if n < 32 {
		ref.Grayscale(dst, r, g, b)
		return
	}
	grayscaleU8AVX512(dst[:n:n], r, g, b)
}

func RgbToUVU8AVX512(u []byte, v []byte, r []byte, g []byte, b []byte) {
	n := min(len(u), len(v), len(r), len(g), len(b))
	if n < 32 {
		ref.RGBToUV(u, v, r, g, b)
		return
	}
	rgbToUVU8AVX512(u[:n:n], v, r, g, b)
}

func IsASCIIAVX512(b []byte) bool {
	if len(b) < 64 {
		return ref.IsASCII(b)
	}
	return isASCIIAVX512(b)
}

func ValidUTF8AVX512(b []byte) bool {
	if len(b) < 64 {
		return ref.ValidUTF8(b)
	}
	return validUTF8AVX512(b)
}

func IndexNonASCIIAVX512(b []byte) int {
	if len(b) < 64 {
		return ref.IndexNonASCII(b)
	}
	return indexNonASCIIAVX512(b)
}

func IndexNonASCII16AVX512(b []uint16) int {
	if len(b) < 64 {
		return ref.IndexNonASCII16(b)
	}
	return indexNonASCII16AVX512(b)
}

func WidenU8U16AVX512(dst []uint16, s []byte) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.WidenU8U16(dst, s)
		return
	}
	widenU8U16AVX512(dst[:n:n], s)
}

func NarrowU16U8AVX512(dst []byte, s []uint16) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.NarrowU16U8(dst, s)
		return
	}
	narrowU16U8AVX512(dst[:n:n], s)
}

func WidenU8U32AVX512(dst []uint32, s []byte) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.WidenU8U32(dst, s)
		return
	}
	widenU8U32AVX512(dst[:n:n], s)
}

func NarrowU32U8AVX512(dst []byte, s []uint32) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.NarrowU32U8(dst, s)
		return
	}
	narrowU32U8AVX512(dst[:n:n], s)
}

func EqualBytesAVX512(a []byte, b []byte) bool {
	n := min(len(a), len(b))
	if n < 1073741824 || len(a) != len(b) {
		return ref.EqualBytes(a, b)
	}
	return equalBytesAVX512(a[:n:n], b)
}

func BitAndAVX512(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAnd(dst, a, b)
		return
	}
	bitAndAVX512(dst[:n:n], a, b)
}

func BitOrAVX512(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitOr(dst, a, b)
		return
	}
	bitOrAVX512(dst[:n:n], a, b)
}

func BitXorAVX512(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitXor(dst, a, b)
		return
	}
	bitXorAVX512(dst[:n:n], a, b)
}

func BitAndNotAVX512(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAndNot(dst, a, b)
		return
	}
	bitAndNotAVX512(dst[:n:n], a, b)
}

func BitNotAVX512(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.BitNot(dst, b)
		return
	}
	bitNotAVX512(dst[:n:n], b)
}

func FillBytesAVX512(dst []byte, v byte) {
	if len(dst) < 32 {
		ref.FillBytes(dst, v)
		return
	}
	fillBytesAVX512(dst, v)
}

func CompareBytesAVX512(a []byte, b []byte) int {
	if len(a) < 2048 {
		return ref.CompareBytes(a, b)
	}
	return compareBytesAVX512(a, b)
}

func CommonPrefixAVX512(a []byte, b []byte) int {
	if len(a) < 64 {
		return ref.CommonPrefix(a, b)
	}
	return commonPrefixAVX512(a, b)
}

func EqualFoldASCIIAVX512(a []byte, b []byte) bool {
	n := min(len(a), len(b))
	if n < 64 || len(a) != len(b) {
		return ref.EqualFoldASCII(a, b)
	}
	return equalFoldASCIIAVX512(a[:n:n], b)
}

func IndexAnyAVX512(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.IndexAny(b, chars)
	}
	return indexAnyAVX512(b, chars)
}

func IndexAnyOrLessAVX512(b []byte, chars []byte, lo byte) int {
	if len(b) < 64 {
		return ref.IndexAnyOrLess(b, chars, lo)
	}
	return indexAnyOrLessAVX512(b, chars, lo)
}

func IndexNotAnyAVX512(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.IndexNotAny(b, chars)
	}
	return indexNotAnyAVX512(b, chars)
}

func LastIndexNotAnyAVX512(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.LastIndexNotAny(b, chars)
	}
	return lastIndexNotAnyAVX512(b, chars)
}

func CountAnyAVX512(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.CountAny(b, chars)
	}
	return countAnyAVX512(b, chars)
}

func JsonMasksAVX512(dst []byte, b []byte, want uint32) {
	if len(b) < 64 || len(dst) < 5*(((len(b)+63)/64)*8) {
		ref.JSONMasks(dst, b, want)
		return
	}
	jsonMasksAVX512(dst, b, want)
}

func JsonValidTokensAVX512(b []byte, masks []uint64, stk []uint64) int {
	if len(b) < 64 || len(b) == 0 || len(masks) < 2*((len(b)+63)/64) {
		return ref.JSONValidTokens(b, masks, stk)
	}
	return jsonValidTokensAVX512(b, masks, stk)
}

func JsonValidAVX512(b []byte, stk []uint64) int {
	if len(b) < 64 || len(b) == 0 {
		return ref.JSONValid(b, stk)
	}
	return jsonValidAVX512(b, stk)
}

func JsonStage1AVX512(out []uint64, masks []byte, nw int, carr []uint64, res []int64) {
	if len(out) < 64 || nw <= 0 || len(out) < 3*nw || len(masks) < 5*nw*8 || len(carr) < 3 || len(res) < 3 {
		ref.JSONStage1(out, masks, nw, carr, res)
		return
	}
	jsonStage1AVX512(out, masks, nw, carr, res)
}

func JsonCopyValidAVX512(dst []byte, b []byte, html byte) int {
	if len(b) < 64 || len(dst) < len(b) {
		return ref.JSONCopyValid(dst, b, html)
	}
	return jsonCopyValidAVX512(dst, b, html)
}

func JsonQuoteAVX512(dst []byte, b []byte, html byte) int {
	if len(b) < 64 || len(dst) < 6*len(b) {
		return ref.JSONQuote(dst, b, html)
	}
	return jsonQuoteAVX512(dst, b, html)
}

func JsonCopyRunAVX512(dst []byte, b []byte, html byte) int {
	if len(b) < 32 || len(dst) < len(b) {
		return ref.JSONCopyRun(dst, b, html)
	}
	return jsonCopyRunAVX512(dst, b, html)
}

func B64EncodeAVX512(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.B64Encode(dst, b)
	}
	return b64EncodeAVX512(dst, b)
}

func B64DecodeAVX512(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.B64Decode(dst, b)
	}
	return b64DecodeAVX512(dst, b)
}

func ParseIntsAVX512(dst []int64, src []byte, idx []int32) (count int, ok bool) {
	n := min(len(idx), len(dst), len(src))
	if n < 32 {
		return ref.ParseInts(dst, src, idx)
	}
	return parseIntsAVX512(dst, src, idx[:n:n])
}

func ParseUintsAVX512(dst []uint64, src []byte, idx []int32) (count int, ok bool) {
	n := min(len(idx), len(dst), len(src))
	if n < 32 {
		return ref.ParseUints(dst, src, idx)
	}
	return parseUintsAVX512(dst, src, idx[:n:n])
}

func FormatIntsAVX512(dst []byte, vals []int64, sep byte) int {
	if len(vals) < 0 || len(dst) < 21*len(vals) {
		return ref.FormatInts(dst, vals, sep)
	}
	return formatIntsAVX512(dst, vals, sep)
}

func HexDecodeAVX512(dst []byte, src []byte) (n int, ok bool) {
	if len(dst) < 32 {
		return ref.HexDecode(dst, src)
	}
	return hexDecodeAVX512(dst, src)
}

func HexEncodeAVX512(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.HexEncode(dst, b)
	}
	return hexEncodeAVX512(dst, b)
}

func IndexAVX512(haystack []byte, needle []byte) int {
	if len(haystack) < 256 {
		return ref.Index(haystack, needle)
	}
	return indexAVX512(haystack, needle)
}

func LastIndexAVX512(haystack []byte, needle []byte) int {
	if len(haystack) < 64 {
		return ref.LastIndex(haystack, needle)
	}
	return lastIndexAVX512(haystack, needle)
}

func CountSeqAVX512(haystack []byte, needle []byte) int {
	if len(haystack) < 256 || len(needle) == 0 {
		return ref.CountSeq(haystack, needle)
	}
	return countSeqAVX512(haystack, needle)
}

func ToUpperASCIIAVX512(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToUpperASCII(dst, b)
		return
	}
	toUpperASCIIAVX512(dst[:n:n], b)
}

func ToLowerASCIIAVX512(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToLowerASCII(dst, b)
		return
	}
	toLowerASCIIAVX512(dst[:n:n], b)
}

func ReplaceByteAVX512(dst []byte, b []byte, old byte, with byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ReplaceByte(dst, b, old, with)
		return
	}
	replaceByteAVX512(dst[:n:n], b, old, with)
}

func registerBytesAVX512(s *kernel.Set) {
	s.Bytes.Count = CountByteAVX512
	s.Bytes.IndexByte = IndexByteAVX512
	s.Bytes.LastIndexByte = LastIndexByteAVX512
	s.Bytes.PopCount = PopCountAVX512
	s.Bytes.MaskBits = MaskBitsAVX512
	s.Bytes.MaskBitsLess = MaskBitsLessAVX512
	s.Bytes.MaskBitsAny4 = MaskBitsAny4AVX512
	s.Bytes.MaskBitsAny = MaskBitsAnyAVX512
	s.Bytes.Hamming = HammingU8AVX512
	s.Bytes.HammingWords = HammingU64AVX512
	s.Bytes.Grayscale = GrayscaleU8AVX512
	s.Bytes.RGBToUV = RgbToUVU8AVX512
	s.Bytes.IsASCII = IsASCIIAVX512
	s.Bytes.ValidUTF8 = ValidUTF8AVX512
	s.Bytes.IndexNonASCII = IndexNonASCIIAVX512
	s.Bytes.IndexNonASCII16 = IndexNonASCII16AVX512
	s.Bytes.WidenU8U16 = WidenU8U16AVX512
	s.Bytes.NarrowU16U8 = NarrowU16U8AVX512
	s.Bytes.WidenU8U32 = WidenU8U32AVX512
	s.Bytes.NarrowU32U8 = NarrowU32U8AVX512
	s.Bytes.Equal = EqualBytesAVX512
	s.Bytes.And = BitAndAVX512
	s.Bytes.Or = BitOrAVX512
	s.Bytes.Xor = BitXorAVX512
	s.Bytes.AndNot = BitAndNotAVX512
	s.Bytes.Not = BitNotAVX512
	s.Bytes.Fill = FillBytesAVX512
	s.Bytes.Compare = CompareBytesAVX512
	s.Bytes.CommonPrefix = CommonPrefixAVX512
	s.Bytes.EqualFoldASCII = EqualFoldASCIIAVX512
	s.Bytes.IndexAny = IndexAnyAVX512
	s.Bytes.IndexAnyOrLess = IndexAnyOrLessAVX512
	s.Bytes.IndexNotAny = IndexNotAnyAVX512
	s.Bytes.LastIndexNotAny = LastIndexNotAnyAVX512
	s.Bytes.CountAny = CountAnyAVX512
	s.Bytes.JSONMasks = JsonMasksAVX512
	s.Bytes.JSONValidTokens = JsonValidTokensAVX512
	s.Bytes.JSONValid = JsonValidAVX512
	s.Bytes.JSONStage1 = JsonStage1AVX512
	s.Bytes.JSONCopyValid = JsonCopyValidAVX512
	s.Bytes.JSONQuote = JsonQuoteAVX512
	s.Bytes.JSONCopyRun = JsonCopyRunAVX512
	s.Bytes.B64Encode = B64EncodeAVX512
	s.Bytes.B64Decode = B64DecodeAVX512
	s.Bytes.ParseInts = ParseIntsAVX512
	s.Bytes.ParseUints = ParseUintsAVX512
	s.Bytes.FormatInts = FormatIntsAVX512
	s.Bytes.HexDecode = HexDecodeAVX512
	s.Bytes.HexEncode = HexEncodeAVX512
	s.Bytes.Index = IndexAVX512
	s.Bytes.LastIndex = LastIndexAVX512
	s.Bytes.CountSeq = CountSeqAVX512
	s.Bytes.ToUpperASCII = ToUpperASCIIAVX512
	s.Bytes.ToLowerASCII = ToLowerASCIIAVX512
	s.Bytes.ReplaceByte = ReplaceByteAVX512
}
