// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/bytes.c
// Target: amd64/avx512

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func countByteAVX512Guarded(b []byte, c byte) int {
	if len(b) < 1073741824 {
		return ref.CountByte(b, c)
	}
	return countByteAVX512(b, c)
}

func indexByteAVX512Guarded(b []byte, c byte) int {
	if len(b) < 1024 {
		return ref.IndexByte(b, c)
	}
	return indexByteAVX512(b, c)
}

func lastIndexByteAVX512Guarded(b []byte, c byte) int {
	if len(b) < 64 {
		return ref.LastIndexByte(b, c)
	}
	return lastIndexByteAVX512(b, c)
}

func popCountAVX512Guarded(b []byte) int {
	if len(b) < 64 {
		return ref.PopCount(b)
	}
	return popCountAVX512(b)
}

func isASCIIAVX512Guarded(b []byte) bool {
	if len(b) < 64 {
		return ref.IsASCII(b)
	}
	return isASCIIAVX512(b)
}

func validUTF8AVX512Guarded(b []byte) bool {
	if len(b) < 64 {
		return ref.ValidUTF8(b)
	}
	return validUTF8AVX512(b)
}

func indexNonASCIIAVX512Guarded(b []byte) int {
	if len(b) < 64 {
		return ref.IndexNonASCII(b)
	}
	return indexNonASCIIAVX512(b)
}

func indexNonASCII16AVX512Guarded(b []uint16) int {
	if len(b) < 64 {
		return ref.IndexNonASCII16(b)
	}
	return indexNonASCII16AVX512(b)
}

func widenU8U16AVX512Guarded(dst []uint16, s []byte) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.WidenU8U16(dst, s)
		return
	}
	widenU8U16AVX512(dst[:n:n], s)
}

func narrowU16U8AVX512Guarded(dst []byte, s []uint16) {
	n := min(len(dst), len(s))
	if n < 32 {
		ref.NarrowU16U8(dst, s)
		return
	}
	narrowU16U8AVX512(dst[:n:n], s)
}

func equalBytesAVX512Guarded(a []byte, b []byte) bool {
	n := min(len(a), len(b))
	if n < 1073741824 || len(a) != len(b) {
		return ref.EqualBytes(a, b)
	}
	return equalBytesAVX512(a[:n:n], b)
}

func bitAndAVX512Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAnd(dst, a, b)
		return
	}
	bitAndAVX512(dst[:n:n], a, b)
}

func bitOrAVX512Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitOr(dst, a, b)
		return
	}
	bitOrAVX512(dst[:n:n], a, b)
}

func bitXorAVX512Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitXor(dst, a, b)
		return
	}
	bitXorAVX512(dst[:n:n], a, b)
}

func bitAndNotAVX512Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAndNot(dst, a, b)
		return
	}
	bitAndNotAVX512(dst[:n:n], a, b)
}

func bitNotAVX512Guarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.BitNot(dst, b)
		return
	}
	bitNotAVX512(dst[:n:n], b)
}

func fillBytesAVX512Guarded(dst []byte, v byte) {
	if len(dst) < 32 {
		ref.FillBytes(dst, v)
		return
	}
	fillBytesAVX512(dst, v)
}

func compareBytesAVX512Guarded(a []byte, b []byte) int {
	if len(a) < 2048 {
		return ref.CompareBytes(a, b)
	}
	return compareBytesAVX512(a, b)
}

func equalFoldASCIIAVX512Guarded(a []byte, b []byte) bool {
	n := min(len(a), len(b))
	if n < 64 || len(a) != len(b) {
		return ref.EqualFoldASCII(a, b)
	}
	return equalFoldASCIIAVX512(a[:n:n], b)
}

func indexAnyAVX512Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.IndexAny(b, chars)
	}
	return indexAnyAVX512(b, chars)
}

func indexNotAnyAVX512Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.IndexNotAny(b, chars)
	}
	return indexNotAnyAVX512(b, chars)
}

func lastIndexNotAnyAVX512Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.LastIndexNotAny(b, chars)
	}
	return lastIndexNotAnyAVX512(b, chars)
}

func countAnyAVX512Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.CountAny(b, chars)
	}
	return countAnyAVX512(b, chars)
}

func b64EncodeAVX512Guarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.B64Encode(dst, b)
	}
	return b64EncodeAVX512(dst, b)
}

func b64DecodeAVX512Guarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.B64Decode(dst, b)
	}
	return b64DecodeAVX512(dst, b)
}

func parseIntsAVX512Guarded(dst []int64, src []byte, idx []int32) (count int, ok bool) {
	n := min(len(idx), len(dst), len(src))
	if n < 32 {
		return ref.ParseInts(dst, src, idx)
	}
	return parseIntsAVX512(dst, src, idx[:n:n])
}

func formatIntsAVX512Guarded(dst []byte, vals []int64, sep byte) int {
	if len(vals) < 0 || len(dst) < 21*len(vals) {
		return ref.FormatInts(dst, vals, sep)
	}
	return formatIntsAVX512(dst, vals, sep)
}

func hexDecodeAVX512Guarded(dst []byte, src []byte) (n int, ok bool) {
	if len(dst) < 32 {
		return ref.HexDecode(dst, src)
	}
	return hexDecodeAVX512(dst, src)
}

func hexEncodeAVX512Guarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.HexEncode(dst, b)
	}
	return hexEncodeAVX512(dst, b)
}

func indexAVX512Guarded(haystack []byte, needle []byte) int {
	if len(haystack) < 256 {
		return ref.Index(haystack, needle)
	}
	return indexAVX512(haystack, needle)
}

func lastIndexAVX512Guarded(haystack []byte, needle []byte) int {
	if len(haystack) < 64 {
		return ref.LastIndex(haystack, needle)
	}
	return lastIndexAVX512(haystack, needle)
}

func countSeqAVX512Guarded(haystack []byte, needle []byte) int {
	if len(haystack) < 256 || len(needle) == 0 {
		return ref.CountSeq(haystack, needle)
	}
	return countSeqAVX512(haystack, needle)
}

func toUpperASCIIAVX512Guarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToUpperASCII(dst, b)
		return
	}
	toUpperASCIIAVX512(dst[:n:n], b)
}

func toLowerASCIIAVX512Guarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToLowerASCII(dst, b)
		return
	}
	toLowerASCIIAVX512(dst[:n:n], b)
}

func replaceByteAVX512Guarded(dst []byte, b []byte, old byte, with byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ReplaceByte(dst, b, old, with)
		return
	}
	replaceByteAVX512(dst[:n:n], b, old, with)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("avx512")
	s.Bytes.Count = countByteAVX512Guarded
	s.Bytes.IndexByte = indexByteAVX512Guarded
	s.Bytes.LastIndexByte = lastIndexByteAVX512Guarded
	s.Bytes.PopCount = popCountAVX512Guarded
	s.Bytes.IsASCII = isASCIIAVX512Guarded
	s.Bytes.ValidUTF8 = validUTF8AVX512Guarded
	s.Bytes.IndexNonASCII = indexNonASCIIAVX512Guarded
	s.Bytes.IndexNonASCII16 = indexNonASCII16AVX512Guarded
	s.Bytes.WidenU8U16 = widenU8U16AVX512Guarded
	s.Bytes.NarrowU16U8 = narrowU16U8AVX512Guarded
	s.Bytes.Equal = equalBytesAVX512Guarded
	s.Bytes.And = bitAndAVX512Guarded
	s.Bytes.Or = bitOrAVX512Guarded
	s.Bytes.Xor = bitXorAVX512Guarded
	s.Bytes.AndNot = bitAndNotAVX512Guarded
	s.Bytes.Not = bitNotAVX512Guarded
	s.Bytes.Fill = fillBytesAVX512Guarded
	s.Bytes.Compare = compareBytesAVX512Guarded
	s.Bytes.EqualFoldASCII = equalFoldASCIIAVX512Guarded
	s.Bytes.IndexAny = indexAnyAVX512Guarded
	s.Bytes.IndexNotAny = indexNotAnyAVX512Guarded
	s.Bytes.LastIndexNotAny = lastIndexNotAnyAVX512Guarded
	s.Bytes.CountAny = countAnyAVX512Guarded
	s.Bytes.B64Encode = b64EncodeAVX512Guarded
	s.Bytes.B64Decode = b64DecodeAVX512Guarded
	s.Bytes.ParseInts = parseIntsAVX512Guarded
	s.Bytes.FormatInts = formatIntsAVX512Guarded
	s.Bytes.HexDecode = hexDecodeAVX512Guarded
	s.Bytes.HexEncode = hexEncodeAVX512Guarded
	s.Bytes.Index = indexAVX512Guarded
	s.Bytes.LastIndex = lastIndexAVX512Guarded
	s.Bytes.CountSeq = countSeqAVX512Guarded
	s.Bytes.ToUpperASCII = toUpperASCIIAVX512Guarded
	s.Bytes.ToLowerASCII = toLowerASCIIAVX512Guarded
	s.Bytes.ReplaceByte = replaceByteAVX512Guarded
}
