// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/bytes.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import "runtime"

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

//go:noescape
func countByteAVX2(b []byte, c byte) int

//go:noescape
func indexByteAVX2(b []byte, c byte) int

//go:noescape
func lastIndexByteAVX2(b []byte, c byte) int

//go:noescape
func popCountAVX2(b []byte) int

//go:noescape
func maskBitsAVX2(dst []byte, b []byte, c byte)

//go:noescape
func maskBitsLessAVX2(dst []byte, b []byte, c byte)

//go:noescape
func maskBitsAny4AVX2(dst []byte, b []byte, chars uint32)

//go:noescape
func maskBitsAnyAVX2(dst []byte, b []byte, chars uint64)

//go:noescape
func hammingU8AVX2(a []byte, b []byte) int

//go:noescape
func hammingU64AVX2(a []uint64, b []uint64) int

//go:noescape
func grayscaleU8AVX2(dst []byte, r []byte, g []byte, b []byte)

//go:noescape
func rgbToUVU8AVX2(u []byte, v []byte, r []byte, g []byte, b []byte)

//go:noescape
func isASCIIAVX2(b []byte) bool

//go:noescape
func validUTF8AVX2(b []byte) bool

//go:noescape
func indexNonASCIIAVX2(b []byte) int

//go:noescape
func indexNonASCII16AVX2(b []uint16) int

//go:noescape
func widenU8U16AVX2(dst []uint16, s []byte)

//go:noescape
func narrowU16U8AVX2(dst []byte, s []uint16)

//go:noescape
func widenU8U32AVX2(dst []uint32, s []byte)

//go:noescape
func narrowU32U8AVX2(dst []byte, s []uint32)

//go:noescape
func equalBytesAVX2(a []byte, b []byte) bool

//go:noescape
func bitAndAVX2(dst []byte, a []byte, b []byte)

//go:noescape
func bitOrAVX2(dst []byte, a []byte, b []byte)

//go:noescape
func bitXorAVX2(dst []byte, a []byte, b []byte)

//go:noescape
func bitAndNotAVX2(dst []byte, a []byte, b []byte)

//go:noescape
func bitNotAVX2(dst []byte, b []byte)

//go:noescape
func fillBytesAVX2(dst []byte, v byte)

//go:noescape
func compareBytesAVX2(a []byte, b []byte) int

//go:noescape
func commonPrefixAVX2(a []byte, b []byte) int

//go:noescape
func equalFoldASCIIAVX2(a []byte, b []byte) bool

//go:noescape
func indexAnyAVX2(b []byte, chars []byte) int

//go:noescape
func indexNotAnyAVX2(b []byte, chars []byte) int

//go:noescape
func lastIndexNotAnyAVX2(b []byte, chars []byte) int

//go:noescape
func countAnyAVX2(b []byte, chars []byte) int

//go:noescape
func b64EncodeAVX2(dst []byte, b []byte) int

//go:noescape
func b64DecodeAVX2(dst []byte, b []byte) int

//go:noescape
func parseIntsAVX2(dst []int64, src []byte, idx []int32) (count int, ok bool)

//go:noescape
func parseUintsAVX2(dst []uint64, src []byte, idx []int32) (count int, ok bool)

//go:noescape
func formatIntsAVX2(dst []byte, vals []int64, sep byte) int

//go:noescape
func hexDecodeAVX2(dst []byte, src []byte) (n int, ok bool)

//go:noescape
func hexEncodeAVX2(dst []byte, b []byte) int

//go:noescape
func indexAVX2(haystack []byte, needle []byte) int

//go:noescape
func lastIndexAVX2(haystack []byte, needle []byte) int

//go:noescape
func countSeqAVX2(haystack []byte, needle []byte) int

//go:noescape
func toUpperASCIIAVX2(dst []byte, b []byte)

//go:noescape
func toLowerASCIIAVX2(dst []byte, b []byte)

//go:noescape
func replaceByteAVX2(dst []byte, b []byte, old byte, with byte)
