// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/bytes.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func countByteAVX2Guarded(b []byte, c byte) int {
	if len(b) < 1073741824 {
		return ref.CountByte(b, c)
	}
	return countByteAVX2(b, c)
}

func indexByteAVX2Guarded(b []byte, c byte) int {
	if len(b) < 1024 {
		return ref.IndexByte(b, c)
	}
	return indexByteAVX2(b, c)
}

func lastIndexByteAVX2Guarded(b []byte, c byte) int {
	if len(b) < 64 {
		return ref.LastIndexByte(b, c)
	}
	return lastIndexByteAVX2(b, c)
}

func popCountAVX2Guarded(b []byte) int {
	if len(b) < 64 {
		return ref.PopCount(b)
	}
	return popCountAVX2(b)
}

func isASCIIAVX2Guarded(b []byte) bool {
	if len(b) < 64 {
		return ref.IsASCII(b)
	}
	return isASCIIAVX2(b)
}

func validUTF8AVX2Guarded(b []byte) bool {
	if len(b) < 64 {
		return ref.ValidUTF8(b)
	}
	return validUTF8AVX2(b)
}

func equalBytesAVX2Guarded(a []byte, b []byte) bool {
	n := min(len(a), len(b))
	if n < 1073741824 || len(a) != len(b) {
		return ref.EqualBytes(a, b)
	}
	return equalBytesAVX2(a[:n:n], b)
}

func bitAndAVX2Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAnd(dst, a, b)
		return
	}
	bitAndAVX2(dst[:n:n], a, b)
}

func bitOrAVX2Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitOr(dst, a, b)
		return
	}
	bitOrAVX2(dst[:n:n], a, b)
}

func bitXorAVX2Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitXor(dst, a, b)
		return
	}
	bitXorAVX2(dst[:n:n], a, b)
}

func bitAndNotAVX2Guarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAndNot(dst, a, b)
		return
	}
	bitAndNotAVX2(dst[:n:n], a, b)
}

func bitNotAVX2Guarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.BitNot(dst, b)
		return
	}
	bitNotAVX2(dst[:n:n], b)
}

func fillBytesAVX2Guarded(dst []byte, v byte) {
	if len(dst) < 32 {
		ref.FillBytes(dst, v)
		return
	}
	fillBytesAVX2(dst, v)
}

func compareBytesAVX2Guarded(a []byte, b []byte) int {
	if len(a) < 2048 {
		return ref.CompareBytes(a, b)
	}
	return compareBytesAVX2(a, b)
}

func equalFoldASCIIAVX2Guarded(a []byte, b []byte) bool {
	n := min(len(a), len(b))
	if n < 64 || len(a) != len(b) {
		return ref.EqualFoldASCII(a, b)
	}
	return equalFoldASCIIAVX2(a[:n:n], b)
}

func indexAnyAVX2Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.IndexAny(b, chars)
	}
	return indexAnyAVX2(b, chars)
}

func indexNotAnyAVX2Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.IndexNotAny(b, chars)
	}
	return indexNotAnyAVX2(b, chars)
}

func lastIndexNotAnyAVX2Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.LastIndexNotAny(b, chars)
	}
	return lastIndexNotAnyAVX2(b, chars)
}

func countAnyAVX2Guarded(b []byte, chars []byte) int {
	if len(b) < 64 {
		return ref.CountAny(b, chars)
	}
	return countAnyAVX2(b, chars)
}

func b64EncodeAVX2Guarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.B64Encode(dst, b)
	}
	return b64EncodeAVX2(dst, b)
}

func b64DecodeAVX2Guarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.B64Decode(dst, b)
	}
	return b64DecodeAVX2(dst, b)
}

func hexDecodeAVX2Guarded(dst []byte, src []byte) (n int, ok bool) {
	if len(dst) < 32 {
		return ref.HexDecode(dst, src)
	}
	return hexDecodeAVX2(dst, src)
}

func hexEncodeAVX2Guarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.HexEncode(dst, b)
	}
	return hexEncodeAVX2(dst, b)
}

func indexAVX2Guarded(haystack []byte, needle []byte) int {
	if len(haystack) < 256 {
		return ref.Index(haystack, needle)
	}
	return indexAVX2(haystack, needle)
}

func lastIndexAVX2Guarded(haystack []byte, needle []byte) int {
	if len(haystack) < 64 {
		return ref.LastIndex(haystack, needle)
	}
	return lastIndexAVX2(haystack, needle)
}

func countSeqAVX2Guarded(haystack []byte, needle []byte) int {
	if len(haystack) < 256 || len(needle) == 0 {
		return ref.CountSeq(haystack, needle)
	}
	return countSeqAVX2(haystack, needle)
}

func toUpperASCIIAVX2Guarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToUpperASCII(dst, b)
		return
	}
	toUpperASCIIAVX2(dst[:n:n], b)
}

func toLowerASCIIAVX2Guarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToLowerASCII(dst, b)
		return
	}
	toLowerASCIIAVX2(dst[:n:n], b)
}

func replaceByteAVX2Guarded(dst []byte, b []byte, old byte, with byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ReplaceByte(dst, b, old, with)
		return
	}
	replaceByteAVX2(dst[:n:n], b, old, with)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("avx2")
	s.Bytes.Count = countByteAVX2Guarded
	s.Bytes.IndexByte = indexByteAVX2Guarded
	s.Bytes.LastIndexByte = lastIndexByteAVX2Guarded
	s.Bytes.PopCount = popCountAVX2Guarded
	s.Bytes.IsASCII = isASCIIAVX2Guarded
	s.Bytes.ValidUTF8 = validUTF8AVX2Guarded
	s.Bytes.Equal = equalBytesAVX2Guarded
	s.Bytes.And = bitAndAVX2Guarded
	s.Bytes.Or = bitOrAVX2Guarded
	s.Bytes.Xor = bitXorAVX2Guarded
	s.Bytes.AndNot = bitAndNotAVX2Guarded
	s.Bytes.Not = bitNotAVX2Guarded
	s.Bytes.Fill = fillBytesAVX2Guarded
	s.Bytes.Compare = compareBytesAVX2Guarded
	s.Bytes.EqualFoldASCII = equalFoldASCIIAVX2Guarded
	s.Bytes.IndexAny = indexAnyAVX2Guarded
	s.Bytes.IndexNotAny = indexNotAnyAVX2Guarded
	s.Bytes.LastIndexNotAny = lastIndexNotAnyAVX2Guarded
	s.Bytes.CountAny = countAnyAVX2Guarded
	s.Bytes.B64Encode = b64EncodeAVX2Guarded
	s.Bytes.B64Decode = b64DecodeAVX2Guarded
	s.Bytes.HexDecode = hexDecodeAVX2Guarded
	s.Bytes.HexEncode = hexEncodeAVX2Guarded
	s.Bytes.Index = indexAVX2Guarded
	s.Bytes.LastIndex = lastIndexAVX2Guarded
	s.Bytes.CountSeq = countSeqAVX2Guarded
	s.Bytes.ToUpperASCII = toUpperASCIIAVX2Guarded
	s.Bytes.ToLowerASCII = toLowerASCIIAVX2Guarded
	s.Bytes.ReplaceByte = replaceByteAVX2Guarded
}
