// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/complex.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func CaddComplex64AVX2(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CAdd(dst, a, b)
		return
	}
	caddComplex64AVX2(dst[:n:n], a, b)
}

func CsubComplex64AVX2(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CSub(dst, a, b)
		return
	}
	csubComplex64AVX2(dst[:n:n], a, b)
}

func CmulComplex64AVX2(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CMul64(dst, a, b)
		return
	}
	cmulComplex64AVX2(dst[:n:n], a, b)
}

func CdivComplex64AVX2(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CDiv64(dst, a, b)
		return
	}
	cdivComplex64AVX2(dst[:n:n], a, b)
}

func CnegComplex64AVX2(dst []complex64, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CNeg(dst, a)
		return
	}
	cnegComplex64AVX2(dst[:n:n], a)
}

func CconjComplex64AVX2(dst []complex64, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CConj64(dst, a)
		return
	}
	cconjComplex64AVX2(dst[:n:n], a)
}

func CabsComplex64AVX2(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CAbs64(dst, a)
		return
	}
	cabsComplex64AVX2(dst[:n:n], a)
}

func CrealComplex64AVX2(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CReal64(dst, a)
		return
	}
	crealComplex64AVX2(dst[:n:n], a)
}

func CimagComplex64AVX2(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CImag64(dst, a)
		return
	}
	cimagComplex64AVX2(dst[:n:n], a)
}

func CscaleComplex64AVX2(dst []complex64, a []complex64, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CScale64(dst, a, s)
		return
	}
	cscaleComplex64AVX2(dst[:n:n], a, s)
}

func CsumComplex64AVX2(a []complex64) complex64 {
	if len(a) < 0 {
		return ref.CSum64(a)
	}
	return csumComplex64AVX2(a)
}

func CdotComplex64AVX2(a []complex64, b []complex64) complex64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.CDot64(a, b)
	}
	return cdotComplex64AVX2(a[:n:n], b)
}

func CdotconjComplex64AVX2(a []complex64, b []complex64) complex64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.CDotConj64(a, b)
	}
	return cdotconjComplex64AVX2(a[:n:n], b)
}

func CfromPartsComplex64AVX2(dst []complex64, re []float32, im []float32) {
	n := min(len(dst), len(re), len(im))
	if n < 16 {
		ref.CFromParts64(dst, re, im)
		return
	}
	cfromPartsComplex64AVX2(dst[:n:n], re, im)
}

func CaddComplex128AVX2(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CAdd(dst, a, b)
		return
	}
	caddComplex128AVX2(dst[:n:n], a, b)
}

func CsubComplex128AVX2(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CSub(dst, a, b)
		return
	}
	csubComplex128AVX2(dst[:n:n], a, b)
}

func CmulComplex128AVX2(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CMul128(dst, a, b)
		return
	}
	cmulComplex128AVX2(dst[:n:n], a, b)
}

func CdivComplex128AVX2(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CDiv128(dst, a, b)
		return
	}
	cdivComplex128AVX2(dst[:n:n], a, b)
}

func CnegComplex128AVX2(dst []complex128, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CNeg(dst, a)
		return
	}
	cnegComplex128AVX2(dst[:n:n], a)
}

func CconjComplex128AVX2(dst []complex128, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CConj128(dst, a)
		return
	}
	cconjComplex128AVX2(dst[:n:n], a)
}

func CabsComplex128AVX2(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CAbs128(dst, a)
		return
	}
	cabsComplex128AVX2(dst[:n:n], a)
}

func CrealComplex128AVX2(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CReal128(dst, a)
		return
	}
	crealComplex128AVX2(dst[:n:n], a)
}

func CimagComplex128AVX2(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CImag128(dst, a)
		return
	}
	cimagComplex128AVX2(dst[:n:n], a)
}

func CscaleComplex128AVX2(dst []complex128, a []complex128, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CScale128(dst, a, s)
		return
	}
	cscaleComplex128AVX2(dst[:n:n], a, s)
}

func CsumComplex128AVX2(a []complex128) complex128 {
	if len(a) < 0 {
		return ref.CSum128(a)
	}
	return csumComplex128AVX2(a)
}

func CdotComplex128AVX2(a []complex128, b []complex128) complex128 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.CDot128(a, b)
	}
	return cdotComplex128AVX2(a[:n:n], b)
}

func CdotconjComplex128AVX2(a []complex128, b []complex128) complex128 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.CDotConj128(a, b)
	}
	return cdotconjComplex128AVX2(a[:n:n], b)
}

func CfromPartsComplex128AVX2(dst []complex128, re []float64, im []float64) {
	n := min(len(dst), len(re), len(im))
	if n < 16 {
		ref.CFromParts128(dst, re, im)
		return
	}
	cfromPartsComplex128AVX2(dst[:n:n], re, im)
}

func registerComplexAVX2(s *kernel.Set) {
	s.C64.Add = CaddComplex64AVX2
	s.C64.Sub = CsubComplex64AVX2
	s.C64.Mul = CmulComplex64AVX2
	s.C64.Div = CdivComplex64AVX2
	s.C64.Neg = CnegComplex64AVX2
	s.C64.Conj = CconjComplex64AVX2
	s.C64Parts.Abs = CabsComplex64AVX2
	s.C64Parts.Real = CrealComplex64AVX2
	s.C64Parts.Imag = CimagComplex64AVX2
	s.C64Parts.Scale = CscaleComplex64AVX2
	s.C64.Sum = CsumComplex64AVX2
	s.C64.Dot = CdotComplex64AVX2
	s.C64.DotConj = CdotconjComplex64AVX2
	s.C64Parts.FromParts = CfromPartsComplex64AVX2
	s.C128.Add = CaddComplex128AVX2
	s.C128.Sub = CsubComplex128AVX2
	s.C128.Mul = CmulComplex128AVX2
	s.C128.Div = CdivComplex128AVX2
	s.C128.Neg = CnegComplex128AVX2
	s.C128.Conj = CconjComplex128AVX2
	s.C128Parts.Abs = CabsComplex128AVX2
	s.C128Parts.Real = CrealComplex128AVX2
	s.C128Parts.Imag = CimagComplex128AVX2
	s.C128Parts.Scale = CscaleComplex128AVX2
	s.C128.Sum = CsumComplex128AVX2
	s.C128.Dot = CdotComplex128AVX2
	s.C128.DotConj = CdotconjComplex128AVX2
	s.C128Parts.FromParts = CfromPartsComplex128AVX2
}
