// Code generated by simdgen. DO NOT EDIT.
//
// Source:  csrc/compress.c
// Target:  amd64/sse2
// Clang:   clang version 22.1.8
// Command: clang --target=x86_64-linux-gnu -march=x86-64 -O3 -ffreestanding -fno-builtin -fno-builtin-memset -fno-builtin-memcpy -fno-jump-tables -fno-math-errno -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -fomit-frame-pointer -fno-stack-protector -mllvm -inline-threshold=1000 -ffp-contract=off -mno-red-zone -mstackrealign -c ../csrc/compress.c -o ../tools/build/tmp/compress_amd64_sse2.o
//
// The instruction bytes below are the compiled function verbatim. Branches
// inside a function are PC-relative and remain correct because the whole
// body moves as a unit.

//go:build amd64 && !purego

#include "textflag.h"

// func runStartsI32SSE2(dst []bool, a []int32)
TEXT ·runStartsI32SSE2(SB), NOSPLIT|NOFRAME, $0-48
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ a_len+32(FP), DX
	// Constant pool appended below the body; the displacements
	// above were patched to reach it and the aligned loads made
	// unaligned, since nothing promises alignment inside a TEXT.
	QUAD $0xf8e48348e5894855
	QUAD $0x0000b28e0fd28548
	QUAD $0x01fa83480107c600
	QUAD $0x01b8000000a5840f
	QUAD $0x0f09fa8348000000
	QUAD $0x4a8d480000008382
	QUAD $0xf8e08349c88949ff
	QUAD $0x66c9314501408d49
	QUAD $0x0d0d6f0ff3c0760f
	QUAD $0x0000441f0f000001
	QUAD $0x42f38e146f0f42f3
	QUAD $0x760f66048e5c6f0f
	QUAD $0x0f42f3db6b0f66da
	QUAD $0x6f0f42f3108e546f
	QUAD $0x66e2760f66148e64
	QUAD $0x66d8ef0f66e46b0f
	QUAD $0x66d9db0f66db630f
	QUAD $0x66e4630f66e0ef0f
	QUAD $0x5c7e0f4266e1db0f
	QUAD $0x0f647e0f4266010f
	QUAD $0xc8394d08c1834905
	QUAD $0x901474c1394ca675
	QUAD $0x0ffc864c3b860c8b
	QUAD $0x3948c0ff48070495
	QUAD $0xc35dec8948ed75c2
	QUAD $0xffffffffffffffff
	QUAD $0x0000ffffffffffff
	QUAD $0xffffffffffffffff
	QUAD $0x0000ffffffffffff
	QUAD $0xffffffffffffffff
	QUAD $0x0000ffffffffffff
	QUAD $0xffffffffffffffff
	QUAD $0x0000ffffffffffff
	QUAD $0x0000000d0000000c
	QUAD $0x0000000f0000000e
	QUAD $0x0000000900000008
	QUAD $0x0000000b0000000a
	QUAD $0x0000000500000004
	QUAD $0x0000000700000006
	QUAD $0x0000000100000000
	QUAD $0x0000000300000002
	QUAD $0xffffffffffffffff
	QUAD $0x0000ffffffffffff
	QUAD $0x0000000001010101
	QUAD $0x0000000000000000
	QUAD $0x0000000000000101
	QUAD $0x0000000000000000
	QUAD $0x0101010101010101
	QUAD $0x0101010101010101
	QUAD $0x0101010101010101
	QUAD $0x0000000000000000
	RET

// func runStartsI64SSE2(dst []bool, a []int64)
TEXT ·runStartsI64SSE2(SB), NOSPLIT|NOFRAME, $0-48
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ a_len+32(FP), DX
	// Constant pool appended below the body; the displacements
	// above were patched to reach it and the aligned loads made
	// unaligned, since nothing promises alignment inside a TEXT.
	QUAD $0xf8e48348e5894855
	QUAD $0x0000e48e0fd28548
	QUAD $0x01fa83480107c600
	QUAD $0x01b8000000d7840f
	QUAD $0x0f05fa8348000000
	QUAD $0x4a8d48000000b382
	QUAD $0xfce08349c88949ff
	QUAD $0x66c9314501408d49
	QUAD $0x4f0d6f0ff3c0760f
	QUAD $0x0000441f0f000001
	QUAD $0x42f3ce146f0f42f3
	QUAD $0x760f6608ce5c6f0f
	QUAD $0x10ce546f0f42f3da
	QUAD $0x6618ce646f0f42f3
	QUAD $0xb1d3700f66e2760f
	QUAD $0xd26b0f66d3db0f66
	QUAD $0xd26b0f66d0ef0f66
	QUAD $0xd1db0f66d2630f66
	QUAD $0xdb0f66b1dc700f66
	QUAD $0xef0f66db6b0f66dc
	QUAD $0x630f66db6b0f66d8
	QUAD $0x0f4166d9db0f66db
	QUAD $0x010f54894666d27e
	QUAD $0x894666da7e0f4166
	QUAD $0x4d04c18349030f54
	QUAD $0x74c1394c8475c839
	QUAD $0x2e66666666666624
	QUAD $0x0000000000841f0f
	QUAD $0xc64c3b48c60c8b48
	QUAD $0xc0ff480704950ff8
	QUAD $0xec8948eb75c23948
	QUAD $0xffffffffffffc35d
	QUAD $0xffffffffffffffff
	QUAD $0xffffffffffff0000
	QUAD $0xffffffffffffffff
	QUAD $0xffffffffffff0000
	QUAD $0xffffffffffffffff
	QUAD $0xffffffffffff0000
	QUAD $0xffffffffffffffff
	QUAD $0x000d0000000c0000
	QUAD $0x000f0000000e0000
	QUAD $0x0009000000080000
	QUAD $0x000b0000000a0000
	QUAD $0x0005000000040000
	QUAD $0x0007000000060000
	QUAD $0x0001000000000000
	QUAD $0x0003000000020000
	QUAD $0xffffffffffff0000
	QUAD $0xffffffffffffffff
	QUAD $0x0000010101010000
	QUAD $0x0000000000000000
	QUAD $0x0000000001010000
	QUAD $0x0000000000000000
	QUAD $0x0101010101010000
	QUAD $0x0101010101010101
	QUAD $0x0101010101010101
	QUAD $0x0000000000000101
	BYTE $0x00
	BYTE $0x00
	RET

// func runStartsU8SSE2(dst []bool, a []byte)
TEXT ·runStartsU8SSE2(SB), NOSPLIT|NOFRAME, $0-48
	MOVQ dst_base+0(FP), DI
	MOVQ a_base+24(FP), SI
	MOVQ a_len+32(FP), DX
	// Constant pool appended below the body; the displacements
	// above were patched to reach it and the aligned loads made
	// unaligned, since nothing promises alignment inside a TEXT.
	QUAD $0xf8e48348e5894855
	QUAD $0x0000e68e0fd28548
	QUAD $0x01fa83480107c600
	QUAD $0xb841000000d9840f
	QUAD $0x09fa834800000001
	QUAD $0x8d48000000b2820f
	QUAD $0x047321fa8348ff42
	QUAD $0x48c189485febc931
	QUAD $0x0ff3c03145e0e183
	QUAD $0x906600000167056f
	QUAD $0x42f3060c6f0f42f3
	QUAD $0x740f660106546f0f
	QUAD $0x10064c6f0f42f3d1
	QUAD $0x6611065c6f0f42f3
	QUAD $0x66d0df0f66d9740f
	QUAD $0x547f0f42f3d8df0f
	QUAD $0x075c7f0f42f30107
	QUAD $0xc1394c20c0834911
	QUAD $0xa86074c83948be75
	QUAD $0x8349c18949617418
	QUAD $0x0ff301418d4df8e1
	QUAD $0x906600000117056f
	QUAD $0x0ff3010e4c7e0ff3
	QUAD $0x66d1740f660e147e
	QUAD $0x0f54d60f66d0df0f
	QUAD $0xc9394908c1834801
	QUAD $0x662074c8394cde75
	QUAD $0x0000000000841f0f
	QUAD $0x443a420604b60f42
	QUAD $0x490704950f42ff06
	QUAD $0x48e975c2394cc0ff
	QUAD $0x01c98348c35dec89
	QUAD $0xffffffdbebc88949
	QUAD $0xffffffffffffffff
	QUAD $0xffffff0000ffffff
	QUAD $0xffffffffffffffff
	QUAD $0xffffff0000ffffff
	QUAD $0xffffffffffffffff
	QUAD $0xffffff0000ffffff
	QUAD $0xffffffffffffffff
	QUAD $0x00000c0000ffffff
	QUAD $0x00000e0000000d00
	QUAD $0x0000080000000f00
	QUAD $0x00000a0000000900
	QUAD $0x0000040000000b00
	QUAD $0x0000060000000500
	QUAD $0x0000000000000700
	QUAD $0x0000020000000100
	QUAD $0xffffff0000000300
	QUAD $0xffffffffffffffff
	QUAD $0x0101010000ffffff
	QUAD $0x0000000000000001
	QUAD $0x0001010000000000
	QUAD $0x0000000000000000
	QUAD $0x0101010000000000
	QUAD $0x0101010101010101
	QUAD $0x0101010101010101
	QUAD $0x0000000101010101
	LONG $0x00000000
	BYTE $0x00
	RET

