// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/compare.c
// Target: amd64/sse2

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func EqFloat32MaskSSE2(dst []bool, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqFloat32MaskSSE2(dst[:n:n], a, b)
}

func EqScalarFloat32MaskSSE2(dst []bool, a []float32, v float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarFloat32MaskSSE2(dst[:n:n], a, v)
}

func NeFloat32MaskSSE2(dst []bool, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neFloat32MaskSSE2(dst[:n:n], a, b)
}

func NeScalarFloat32MaskSSE2(dst []bool, a []float32, v float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarFloat32MaskSSE2(dst[:n:n], a, v)
}

func LtFloat32MaskSSE2(dst []bool, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltFloat32MaskSSE2(dst[:n:n], a, b)
}

func LtScalarFloat32MaskSSE2(dst []bool, a []float32, v float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarFloat32MaskSSE2(dst[:n:n], a, v)
}

func LeFloat32MaskSSE2(dst []bool, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leFloat32MaskSSE2(dst[:n:n], a, b)
}

func LeScalarFloat32MaskSSE2(dst []bool, a []float32, v float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarFloat32MaskSSE2(dst[:n:n], a, v)
}

func GtFloat32MaskSSE2(dst []bool, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtFloat32MaskSSE2(dst[:n:n], a, b)
}

func GtScalarFloat32MaskSSE2(dst []bool, a []float32, v float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarFloat32MaskSSE2(dst[:n:n], a, v)
}

func GeFloat32MaskSSE2(dst []bool, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geFloat32MaskSSE2(dst[:n:n], a, b)
}

func GeScalarFloat32MaskSSE2(dst []bool, a []float32, v float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarFloat32MaskSSE2(dst[:n:n], a, v)
}

func SelectFloat32SSE2(dst []float32, mask []bool, yes []float32, no []float32) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectFloat32SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundFloat32SSE2(dst []int32, a []float32, q []float32) {
	if len(a) < 16 {
		ref.LowerBoundFloat(dst, a, q)
		return
	}
	lowerBoundFloat32SSE2(dst, a, q)
}

func EqFloat64MaskSSE2(dst []bool, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqFloat64MaskSSE2(dst[:n:n], a, b)
}

func EqScalarFloat64MaskSSE2(dst []bool, a []float64, v float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarFloat64MaskSSE2(dst[:n:n], a, v)
}

func NeFloat64MaskSSE2(dst []bool, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neFloat64MaskSSE2(dst[:n:n], a, b)
}

func NeScalarFloat64MaskSSE2(dst []bool, a []float64, v float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarFloat64MaskSSE2(dst[:n:n], a, v)
}

func LtFloat64MaskSSE2(dst []bool, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltFloat64MaskSSE2(dst[:n:n], a, b)
}

func LtScalarFloat64MaskSSE2(dst []bool, a []float64, v float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarFloat64MaskSSE2(dst[:n:n], a, v)
}

func LeFloat64MaskSSE2(dst []bool, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leFloat64MaskSSE2(dst[:n:n], a, b)
}

func LeScalarFloat64MaskSSE2(dst []bool, a []float64, v float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarFloat64MaskSSE2(dst[:n:n], a, v)
}

func GtFloat64MaskSSE2(dst []bool, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtFloat64MaskSSE2(dst[:n:n], a, b)
}

func GtScalarFloat64MaskSSE2(dst []bool, a []float64, v float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarFloat64MaskSSE2(dst[:n:n], a, v)
}

func GeFloat64MaskSSE2(dst []bool, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geFloat64MaskSSE2(dst[:n:n], a, b)
}

func GeScalarFloat64MaskSSE2(dst []bool, a []float64, v float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarFloat64MaskSSE2(dst[:n:n], a, v)
}

func SelectFloat64SSE2(dst []float64, mask []bool, yes []float64, no []float64) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectFloat64SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundFloat64SSE2(dst []int32, a []float64, q []float64) {
	if len(a) < 16 {
		ref.LowerBoundFloat(dst, a, q)
		return
	}
	lowerBoundFloat64SSE2(dst, a, q)
}

func EqInt32MaskSSE2(dst []bool, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqInt32MaskSSE2(dst[:n:n], a, b)
}

func EqScalarInt32MaskSSE2(dst []bool, a []int32, v int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarInt32MaskSSE2(dst[:n:n], a, v)
}

func NeInt32MaskSSE2(dst []bool, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neInt32MaskSSE2(dst[:n:n], a, b)
}

func NeScalarInt32MaskSSE2(dst []bool, a []int32, v int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarInt32MaskSSE2(dst[:n:n], a, v)
}

func LtInt32MaskSSE2(dst []bool, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltInt32MaskSSE2(dst[:n:n], a, b)
}

func LtScalarInt32MaskSSE2(dst []bool, a []int32, v int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarInt32MaskSSE2(dst[:n:n], a, v)
}

func LeInt32MaskSSE2(dst []bool, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leInt32MaskSSE2(dst[:n:n], a, b)
}

func LeScalarInt32MaskSSE2(dst []bool, a []int32, v int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarInt32MaskSSE2(dst[:n:n], a, v)
}

func GtInt32MaskSSE2(dst []bool, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtInt32MaskSSE2(dst[:n:n], a, b)
}

func GtScalarInt32MaskSSE2(dst []bool, a []int32, v int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarInt32MaskSSE2(dst[:n:n], a, v)
}

func GeInt32MaskSSE2(dst []bool, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geInt32MaskSSE2(dst[:n:n], a, b)
}

func GeScalarInt32MaskSSE2(dst []bool, a []int32, v int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarInt32MaskSSE2(dst[:n:n], a, v)
}

func SelectInt32SSE2(dst []int32, mask []bool, yes []int32, no []int32) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectInt32SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundInt32SSE2(dst []int32, a []int32, q []int32) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundInt32SSE2(dst, a, q)
}

func EqInt64MaskSSE2(dst []bool, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqInt64MaskSSE2(dst[:n:n], a, b)
}

func EqScalarInt64MaskSSE2(dst []bool, a []int64, v int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarInt64MaskSSE2(dst[:n:n], a, v)
}

func NeInt64MaskSSE2(dst []bool, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neInt64MaskSSE2(dst[:n:n], a, b)
}

func LtInt64MaskSSE2(dst []bool, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltInt64MaskSSE2(dst[:n:n], a, b)
}

func LtScalarInt64MaskSSE2(dst []bool, a []int64, v int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarInt64MaskSSE2(dst[:n:n], a, v)
}

func LeInt64MaskSSE2(dst []bool, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leInt64MaskSSE2(dst[:n:n], a, b)
}

func GtInt64MaskSSE2(dst []bool, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtInt64MaskSSE2(dst[:n:n], a, b)
}

func GtScalarInt64MaskSSE2(dst []bool, a []int64, v int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarInt64MaskSSE2(dst[:n:n], a, v)
}

func GeInt64MaskSSE2(dst []bool, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geInt64MaskSSE2(dst[:n:n], a, b)
}

func SelectInt64SSE2(dst []int64, mask []bool, yes []int64, no []int64) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectInt64SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundInt64SSE2(dst []int32, a []int64, q []int64) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundInt64SSE2(dst, a, q)
}

func EqInt8MaskSSE2(dst []bool, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqInt8MaskSSE2(dst[:n:n], a, b)
}

func EqScalarInt8MaskSSE2(dst []bool, a []int8, v int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarInt8MaskSSE2(dst[:n:n], a, v)
}

func NeInt8MaskSSE2(dst []bool, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neInt8MaskSSE2(dst[:n:n], a, b)
}

func NeScalarInt8MaskSSE2(dst []bool, a []int8, v int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarInt8MaskSSE2(dst[:n:n], a, v)
}

func LtInt8MaskSSE2(dst []bool, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltInt8MaskSSE2(dst[:n:n], a, b)
}

func LtScalarInt8MaskSSE2(dst []bool, a []int8, v int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarInt8MaskSSE2(dst[:n:n], a, v)
}

func LeInt8MaskSSE2(dst []bool, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leInt8MaskSSE2(dst[:n:n], a, b)
}

func LeScalarInt8MaskSSE2(dst []bool, a []int8, v int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarInt8MaskSSE2(dst[:n:n], a, v)
}

func GtInt8MaskSSE2(dst []bool, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtInt8MaskSSE2(dst[:n:n], a, b)
}

func GtScalarInt8MaskSSE2(dst []bool, a []int8, v int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarInt8MaskSSE2(dst[:n:n], a, v)
}

func GeInt8MaskSSE2(dst []bool, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geInt8MaskSSE2(dst[:n:n], a, b)
}

func GeScalarInt8MaskSSE2(dst []bool, a []int8, v int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarInt8MaskSSE2(dst[:n:n], a, v)
}

func SelectInt8SSE2(dst []int8, mask []bool, yes []int8, no []int8) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectInt8SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundInt8SSE2(dst []int32, a []int8, q []int8) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundInt8SSE2(dst, a, q)
}

func EqInt16MaskSSE2(dst []bool, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqInt16MaskSSE2(dst[:n:n], a, b)
}

func EqScalarInt16MaskSSE2(dst []bool, a []int16, v int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarInt16MaskSSE2(dst[:n:n], a, v)
}

func NeInt16MaskSSE2(dst []bool, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neInt16MaskSSE2(dst[:n:n], a, b)
}

func NeScalarInt16MaskSSE2(dst []bool, a []int16, v int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarInt16MaskSSE2(dst[:n:n], a, v)
}

func LtInt16MaskSSE2(dst []bool, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltInt16MaskSSE2(dst[:n:n], a, b)
}

func LtScalarInt16MaskSSE2(dst []bool, a []int16, v int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarInt16MaskSSE2(dst[:n:n], a, v)
}

func LeInt16MaskSSE2(dst []bool, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leInt16MaskSSE2(dst[:n:n], a, b)
}

func LeScalarInt16MaskSSE2(dst []bool, a []int16, v int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarInt16MaskSSE2(dst[:n:n], a, v)
}

func GtInt16MaskSSE2(dst []bool, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtInt16MaskSSE2(dst[:n:n], a, b)
}

func GtScalarInt16MaskSSE2(dst []bool, a []int16, v int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarInt16MaskSSE2(dst[:n:n], a, v)
}

func GeInt16MaskSSE2(dst []bool, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geInt16MaskSSE2(dst[:n:n], a, b)
}

func GeScalarInt16MaskSSE2(dst []bool, a []int16, v int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarInt16MaskSSE2(dst[:n:n], a, v)
}

func SelectInt16SSE2(dst []int16, mask []bool, yes []int16, no []int16) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectInt16SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundInt16SSE2(dst []int32, a []int16, q []int16) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundInt16SSE2(dst, a, q)
}

func EqUint8MaskSSE2(dst []bool, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqUint8MaskSSE2(dst[:n:n], a, b)
}

func EqScalarUint8MaskSSE2(dst []bool, a []byte, v byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarUint8MaskSSE2(dst[:n:n], a, v)
}

func NeUint8MaskSSE2(dst []bool, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neUint8MaskSSE2(dst[:n:n], a, b)
}

func NeScalarUint8MaskSSE2(dst []bool, a []byte, v byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarUint8MaskSSE2(dst[:n:n], a, v)
}

func LtUint8MaskSSE2(dst []bool, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltUint8MaskSSE2(dst[:n:n], a, b)
}

func LtScalarUint8MaskSSE2(dst []bool, a []byte, v byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarUint8MaskSSE2(dst[:n:n], a, v)
}

func LeUint8MaskSSE2(dst []bool, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leUint8MaskSSE2(dst[:n:n], a, b)
}

func LeScalarUint8MaskSSE2(dst []bool, a []byte, v byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarUint8MaskSSE2(dst[:n:n], a, v)
}

func GtUint8MaskSSE2(dst []bool, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtUint8MaskSSE2(dst[:n:n], a, b)
}

func GtScalarUint8MaskSSE2(dst []bool, a []byte, v byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarUint8MaskSSE2(dst[:n:n], a, v)
}

func GeUint8MaskSSE2(dst []bool, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geUint8MaskSSE2(dst[:n:n], a, b)
}

func GeScalarUint8MaskSSE2(dst []bool, a []byte, v byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarUint8MaskSSE2(dst[:n:n], a, v)
}

func SelectUint8SSE2(dst []byte, mask []bool, yes []byte, no []byte) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectUint8SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundUint8SSE2(dst []int32, a []byte, q []byte) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundUint8SSE2(dst, a, q)
}

func EqUint16MaskSSE2(dst []bool, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqUint16MaskSSE2(dst[:n:n], a, b)
}

func EqScalarUint16MaskSSE2(dst []bool, a []uint16, v uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarUint16MaskSSE2(dst[:n:n], a, v)
}

func NeUint16MaskSSE2(dst []bool, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neUint16MaskSSE2(dst[:n:n], a, b)
}

func NeScalarUint16MaskSSE2(dst []bool, a []uint16, v uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarUint16MaskSSE2(dst[:n:n], a, v)
}

func LtUint16MaskSSE2(dst []bool, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltUint16MaskSSE2(dst[:n:n], a, b)
}

func LtScalarUint16MaskSSE2(dst []bool, a []uint16, v uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarUint16MaskSSE2(dst[:n:n], a, v)
}

func LeUint16MaskSSE2(dst []bool, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leUint16MaskSSE2(dst[:n:n], a, b)
}

func LeScalarUint16MaskSSE2(dst []bool, a []uint16, v uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarUint16MaskSSE2(dst[:n:n], a, v)
}

func GtUint16MaskSSE2(dst []bool, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtUint16MaskSSE2(dst[:n:n], a, b)
}

func GtScalarUint16MaskSSE2(dst []bool, a []uint16, v uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarUint16MaskSSE2(dst[:n:n], a, v)
}

func GeUint16MaskSSE2(dst []bool, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geUint16MaskSSE2(dst[:n:n], a, b)
}

func GeScalarUint16MaskSSE2(dst []bool, a []uint16, v uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarUint16MaskSSE2(dst[:n:n], a, v)
}

func SelectUint16SSE2(dst []uint16, mask []bool, yes []uint16, no []uint16) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectUint16SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundUint16SSE2(dst []int32, a []uint16, q []uint16) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundUint16SSE2(dst, a, q)
}

func EqUint32MaskSSE2(dst []bool, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqUint32MaskSSE2(dst[:n:n], a, b)
}

func EqScalarUint32MaskSSE2(dst []bool, a []uint32, v uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarUint32MaskSSE2(dst[:n:n], a, v)
}

func NeUint32MaskSSE2(dst []bool, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neUint32MaskSSE2(dst[:n:n], a, b)
}

func NeScalarUint32MaskSSE2(dst []bool, a []uint32, v uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NotEqualScalarMask(dst, a, v)
		return
	}
	neScalarUint32MaskSSE2(dst[:n:n], a, v)
}

func LtUint32MaskSSE2(dst []bool, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessMask(dst, a, b)
		return
	}
	ltUint32MaskSSE2(dst[:n:n], a, b)
}

func LtScalarUint32MaskSSE2(dst []bool, a []uint32, v uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessScalarMask(dst, a, v)
		return
	}
	ltScalarUint32MaskSSE2(dst[:n:n], a, v)
}

func LeUint32MaskSSE2(dst []bool, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.LessEqualMask(dst, a, b)
		return
	}
	leUint32MaskSSE2(dst[:n:n], a, b)
}

func LeScalarUint32MaskSSE2(dst []bool, a []uint32, v uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.LessEqualScalarMask(dst, a, v)
		return
	}
	leScalarUint32MaskSSE2(dst[:n:n], a, v)
}

func GtUint32MaskSSE2(dst []bool, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterMask(dst, a, b)
		return
	}
	gtUint32MaskSSE2(dst[:n:n], a, b)
}

func GtScalarUint32MaskSSE2(dst []bool, a []uint32, v uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterScalarMask(dst, a, v)
		return
	}
	gtScalarUint32MaskSSE2(dst[:n:n], a, v)
}

func GeUint32MaskSSE2(dst []bool, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.GreaterEqualMask(dst, a, b)
		return
	}
	geUint32MaskSSE2(dst[:n:n], a, b)
}

func GeScalarUint32MaskSSE2(dst []bool, a []uint32, v uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.GreaterEqualScalarMask(dst, a, v)
		return
	}
	geScalarUint32MaskSSE2(dst[:n:n], a, v)
}

func SelectUint32SSE2(dst []uint32, mask []bool, yes []uint32, no []uint32) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectUint32SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundUint32SSE2(dst []int32, a []uint32, q []uint32) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundUint32SSE2(dst, a, q)
}

func EqUint64MaskSSE2(dst []bool, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.EqualMask(dst, a, b)
		return
	}
	eqUint64MaskSSE2(dst[:n:n], a, b)
}

func EqScalarUint64MaskSSE2(dst []bool, a []uint64, v uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.EqualScalarMask(dst, a, v)
		return
	}
	eqScalarUint64MaskSSE2(dst[:n:n], a, v)
}

func NeUint64MaskSSE2(dst []bool, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.NotEqualMask(dst, a, b)
		return
	}
	neUint64MaskSSE2(dst[:n:n], a, b)
}

func SelectUint64SSE2(dst []uint64, mask []bool, yes []uint64, no []uint64) {
	n := min(len(dst), len(mask), len(yes), len(no))
	if n < 16 {
		ref.Select(dst, mask, yes, no)
		return
	}
	selectUint64SSE2(dst[:n:n], mask, yes, no)
}

func LowerBoundUint64SSE2(dst []int32, a []uint64, q []uint64) {
	if len(a) < 16 {
		ref.LowerBoundInt(dst, a, q)
		return
	}
	lowerBoundUint64SSE2(dst, a, q)
}

func MaskAllSSE2(m []bool) bool {
	if len(m) < 32 {
		return ref.MaskAll(m)
	}
	return maskAllSSE2(m)
}

func MaskAnySSE2(m []bool) bool {
	if len(m) < 32 {
		return ref.MaskAny(m)
	}
	return maskAnySSE2(m)
}

func MaskCountSSE2(m []bool) int {
	if len(m) < 32 {
		return ref.MaskCount(m)
	}
	return maskCountSSE2(m)
}

func MaskAndSSE2(dst []bool, a []bool, b []bool) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.MaskAnd(dst, a, b)
		return
	}
	maskAndSSE2(dst[:n:n], a, b)
}

func MaskOrSSE2(dst []bool, a []bool, b []bool) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.MaskOr(dst, a, b)
		return
	}
	maskOrSSE2(dst[:n:n], a, b)
}

func MaskXorSSE2(dst []bool, a []bool, b []bool) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.MaskXor(dst, a, b)
		return
	}
	maskXorSSE2(dst[:n:n], a, b)
}

func MaskNotSSE2(dst []bool, a []bool) {
	n := min(len(dst), len(a))
	if n < 32 {
		ref.MaskNot(dst, a)
		return
	}
	maskNotSSE2(dst[:n:n], a)
}

func registerCompareSSE2(s *kernel.Set) {
	s.F32.EqualMask = EqFloat32MaskSSE2
	s.F32.EqualScalarMask = EqScalarFloat32MaskSSE2
	s.F32.NotEqualMask = NeFloat32MaskSSE2
	s.F32.NotEqualScalarMask = NeScalarFloat32MaskSSE2
	s.F32.LessMask = LtFloat32MaskSSE2
	s.F32.LessScalarMask = LtScalarFloat32MaskSSE2
	s.F32.LessEqualMask = LeFloat32MaskSSE2
	s.F32.LessEqualScalarMask = LeScalarFloat32MaskSSE2
	s.F32.GreaterMask = GtFloat32MaskSSE2
	s.F32.GreaterScalarMask = GtScalarFloat32MaskSSE2
	s.F32.GreaterEqualMask = GeFloat32MaskSSE2
	s.F32.GreaterEqualScalarMask = GeScalarFloat32MaskSSE2
	s.F32.Select = SelectFloat32SSE2
	s.F32.LowerBound = LowerBoundFloat32SSE2
	s.F64.EqualMask = EqFloat64MaskSSE2
	s.F64.EqualScalarMask = EqScalarFloat64MaskSSE2
	s.F64.NotEqualMask = NeFloat64MaskSSE2
	s.F64.NotEqualScalarMask = NeScalarFloat64MaskSSE2
	s.F64.LessMask = LtFloat64MaskSSE2
	s.F64.LessScalarMask = LtScalarFloat64MaskSSE2
	s.F64.LessEqualMask = LeFloat64MaskSSE2
	s.F64.LessEqualScalarMask = LeScalarFloat64MaskSSE2
	s.F64.GreaterMask = GtFloat64MaskSSE2
	s.F64.GreaterScalarMask = GtScalarFloat64MaskSSE2
	s.F64.GreaterEqualMask = GeFloat64MaskSSE2
	s.F64.GreaterEqualScalarMask = GeScalarFloat64MaskSSE2
	s.F64.Select = SelectFloat64SSE2
	s.F64.LowerBound = LowerBoundFloat64SSE2
	s.I32.EqualMask = EqInt32MaskSSE2
	s.I32.EqualScalarMask = EqScalarInt32MaskSSE2
	s.I32.NotEqualMask = NeInt32MaskSSE2
	s.I32.NotEqualScalarMask = NeScalarInt32MaskSSE2
	s.I32.LessMask = LtInt32MaskSSE2
	s.I32.LessScalarMask = LtScalarInt32MaskSSE2
	s.I32.LessEqualMask = LeInt32MaskSSE2
	s.I32.LessEqualScalarMask = LeScalarInt32MaskSSE2
	s.I32.GreaterMask = GtInt32MaskSSE2
	s.I32.GreaterScalarMask = GtScalarInt32MaskSSE2
	s.I32.GreaterEqualMask = GeInt32MaskSSE2
	s.I32.GreaterEqualScalarMask = GeScalarInt32MaskSSE2
	s.I32.Select = SelectInt32SSE2
	s.I32.LowerBound = LowerBoundInt32SSE2
	s.I64.EqualMask = EqInt64MaskSSE2
	s.I64.EqualScalarMask = EqScalarInt64MaskSSE2
	s.I64.NotEqualMask = NeInt64MaskSSE2
	s.I64.LessMask = LtInt64MaskSSE2
	s.I64.LessScalarMask = LtScalarInt64MaskSSE2
	s.I64.LessEqualMask = LeInt64MaskSSE2
	s.I64.GreaterMask = GtInt64MaskSSE2
	s.I64.GreaterScalarMask = GtScalarInt64MaskSSE2
	s.I64.GreaterEqualMask = GeInt64MaskSSE2
	s.I64.Select = SelectInt64SSE2
	s.I64.LowerBound = LowerBoundInt64SSE2
	s.I8.EqualMask = EqInt8MaskSSE2
	s.I8.EqualScalarMask = EqScalarInt8MaskSSE2
	s.I8.NotEqualMask = NeInt8MaskSSE2
	s.I8.NotEqualScalarMask = NeScalarInt8MaskSSE2
	s.I8.LessMask = LtInt8MaskSSE2
	s.I8.LessScalarMask = LtScalarInt8MaskSSE2
	s.I8.LessEqualMask = LeInt8MaskSSE2
	s.I8.LessEqualScalarMask = LeScalarInt8MaskSSE2
	s.I8.GreaterMask = GtInt8MaskSSE2
	s.I8.GreaterScalarMask = GtScalarInt8MaskSSE2
	s.I8.GreaterEqualMask = GeInt8MaskSSE2
	s.I8.GreaterEqualScalarMask = GeScalarInt8MaskSSE2
	s.I8.Select = SelectInt8SSE2
	s.I8.LowerBound = LowerBoundInt8SSE2
	s.I16.EqualMask = EqInt16MaskSSE2
	s.I16.EqualScalarMask = EqScalarInt16MaskSSE2
	s.I16.NotEqualMask = NeInt16MaskSSE2
	s.I16.NotEqualScalarMask = NeScalarInt16MaskSSE2
	s.I16.LessMask = LtInt16MaskSSE2
	s.I16.LessScalarMask = LtScalarInt16MaskSSE2
	s.I16.LessEqualMask = LeInt16MaskSSE2
	s.I16.LessEqualScalarMask = LeScalarInt16MaskSSE2
	s.I16.GreaterMask = GtInt16MaskSSE2
	s.I16.GreaterScalarMask = GtScalarInt16MaskSSE2
	s.I16.GreaterEqualMask = GeInt16MaskSSE2
	s.I16.GreaterEqualScalarMask = GeScalarInt16MaskSSE2
	s.I16.Select = SelectInt16SSE2
	s.I16.LowerBound = LowerBoundInt16SSE2
	s.U8.EqualMask = EqUint8MaskSSE2
	s.U8.EqualScalarMask = EqScalarUint8MaskSSE2
	s.U8.NotEqualMask = NeUint8MaskSSE2
	s.U8.NotEqualScalarMask = NeScalarUint8MaskSSE2
	s.U8.LessMask = LtUint8MaskSSE2
	s.U8.LessScalarMask = LtScalarUint8MaskSSE2
	s.U8.LessEqualMask = LeUint8MaskSSE2
	s.U8.LessEqualScalarMask = LeScalarUint8MaskSSE2
	s.U8.GreaterMask = GtUint8MaskSSE2
	s.U8.GreaterScalarMask = GtScalarUint8MaskSSE2
	s.U8.GreaterEqualMask = GeUint8MaskSSE2
	s.U8.GreaterEqualScalarMask = GeScalarUint8MaskSSE2
	s.U8.Select = SelectUint8SSE2
	s.U8.LowerBound = LowerBoundUint8SSE2
	s.U16.EqualMask = EqUint16MaskSSE2
	s.U16.EqualScalarMask = EqScalarUint16MaskSSE2
	s.U16.NotEqualMask = NeUint16MaskSSE2
	s.U16.NotEqualScalarMask = NeScalarUint16MaskSSE2
	s.U16.LessMask = LtUint16MaskSSE2
	s.U16.LessScalarMask = LtScalarUint16MaskSSE2
	s.U16.LessEqualMask = LeUint16MaskSSE2
	s.U16.LessEqualScalarMask = LeScalarUint16MaskSSE2
	s.U16.GreaterMask = GtUint16MaskSSE2
	s.U16.GreaterScalarMask = GtScalarUint16MaskSSE2
	s.U16.GreaterEqualMask = GeUint16MaskSSE2
	s.U16.GreaterEqualScalarMask = GeScalarUint16MaskSSE2
	s.U16.Select = SelectUint16SSE2
	s.U16.LowerBound = LowerBoundUint16SSE2
	s.U32.EqualMask = EqUint32MaskSSE2
	s.U32.EqualScalarMask = EqScalarUint32MaskSSE2
	s.U32.NotEqualMask = NeUint32MaskSSE2
	s.U32.NotEqualScalarMask = NeScalarUint32MaskSSE2
	s.U32.LessMask = LtUint32MaskSSE2
	s.U32.LessScalarMask = LtScalarUint32MaskSSE2
	s.U32.LessEqualMask = LeUint32MaskSSE2
	s.U32.LessEqualScalarMask = LeScalarUint32MaskSSE2
	s.U32.GreaterMask = GtUint32MaskSSE2
	s.U32.GreaterScalarMask = GtScalarUint32MaskSSE2
	s.U32.GreaterEqualMask = GeUint32MaskSSE2
	s.U32.GreaterEqualScalarMask = GeScalarUint32MaskSSE2
	s.U32.Select = SelectUint32SSE2
	s.U32.LowerBound = LowerBoundUint32SSE2
	s.U64.EqualMask = EqUint64MaskSSE2
	s.U64.EqualScalarMask = EqScalarUint64MaskSSE2
	s.U64.NotEqualMask = NeUint64MaskSSE2
	s.U64.Select = SelectUint64SSE2
	s.U64.LowerBound = LowerBoundUint64SSE2
	s.Mask.All = MaskAllSSE2
	s.Mask.Any = MaskAnySSE2
	s.Mask.Count = MaskCountSSE2
	s.Mask.And = MaskAndSSE2
	s.Mask.Or = MaskOrSSE2
	s.Mask.Xor = MaskXorSSE2
	s.Mask.Not = MaskNotSSE2
}
