// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/complex.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func caddComplex64AVX2Guarded(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CAdd(dst, a, b)
		return
	}
	caddComplex64AVX2(dst[:n:n], a, b)
}

func csubComplex64AVX2Guarded(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CSub(dst, a, b)
		return
	}
	csubComplex64AVX2(dst[:n:n], a, b)
}

func cmulComplex64AVX2Guarded(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CMul64(dst, a, b)
		return
	}
	cmulComplex64AVX2(dst[:n:n], a, b)
}

func cdivComplex64AVX2Guarded(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CDiv64(dst, a, b)
		return
	}
	cdivComplex64AVX2(dst[:n:n], a, b)
}

func cnegComplex64AVX2Guarded(dst []complex64, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CNeg(dst, a)
		return
	}
	cnegComplex64AVX2(dst[:n:n], a)
}

func cconjComplex64AVX2Guarded(dst []complex64, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CConj64(dst, a)
		return
	}
	cconjComplex64AVX2(dst[:n:n], a)
}

func cabsComplex64AVX2Guarded(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CAbs64(dst, a)
		return
	}
	cabsComplex64AVX2(dst[:n:n], a)
}

func crealComplex64AVX2Guarded(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CReal64(dst, a)
		return
	}
	crealComplex64AVX2(dst[:n:n], a)
}

func cimagComplex64AVX2Guarded(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CImag64(dst, a)
		return
	}
	cimagComplex64AVX2(dst[:n:n], a)
}

func cscaleComplex64AVX2Guarded(dst []complex64, a []complex64, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CScale64(dst, a, s)
		return
	}
	cscaleComplex64AVX2(dst[:n:n], a, s)
}

func cfromPartsComplex64AVX2Guarded(dst []complex64, re []float32, im []float32) {
	n := min(len(dst), len(re), len(im))
	if n < 16 {
		ref.CFromParts64(dst, re, im)
		return
	}
	cfromPartsComplex64AVX2(dst[:n:n], re, im)
}

func caddComplex128AVX2Guarded(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CAdd(dst, a, b)
		return
	}
	caddComplex128AVX2(dst[:n:n], a, b)
}

func csubComplex128AVX2Guarded(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CSub(dst, a, b)
		return
	}
	csubComplex128AVX2(dst[:n:n], a, b)
}

func cmulComplex128AVX2Guarded(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CMul128(dst, a, b)
		return
	}
	cmulComplex128AVX2(dst[:n:n], a, b)
}

func cdivComplex128AVX2Guarded(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CDiv128(dst, a, b)
		return
	}
	cdivComplex128AVX2(dst[:n:n], a, b)
}

func cnegComplex128AVX2Guarded(dst []complex128, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CNeg(dst, a)
		return
	}
	cnegComplex128AVX2(dst[:n:n], a)
}

func cconjComplex128AVX2Guarded(dst []complex128, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CConj128(dst, a)
		return
	}
	cconjComplex128AVX2(dst[:n:n], a)
}

func cabsComplex128AVX2Guarded(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CAbs128(dst, a)
		return
	}
	cabsComplex128AVX2(dst[:n:n], a)
}

func crealComplex128AVX2Guarded(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CReal128(dst, a)
		return
	}
	crealComplex128AVX2(dst[:n:n], a)
}

func cimagComplex128AVX2Guarded(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CImag128(dst, a)
		return
	}
	cimagComplex128AVX2(dst[:n:n], a)
}

func cscaleComplex128AVX2Guarded(dst []complex128, a []complex128, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CScale128(dst, a, s)
		return
	}
	cscaleComplex128AVX2(dst[:n:n], a, s)
}

func cfromPartsComplex128AVX2Guarded(dst []complex128, re []float64, im []float64) {
	n := min(len(dst), len(re), len(im))
	if n < 16 {
		ref.CFromParts128(dst, re, im)
		return
	}
	cfromPartsComplex128AVX2(dst[:n:n], re, im)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("avx2")
	s.C64.Add = caddComplex64AVX2Guarded
	s.C64.Sub = csubComplex64AVX2Guarded
	s.C64.Mul = cmulComplex64AVX2Guarded
	s.C64.Div = cdivComplex64AVX2Guarded
	s.C64.Neg = cnegComplex64AVX2Guarded
	s.C64.Conj = cconjComplex64AVX2Guarded
	s.C64Parts.Abs = cabsComplex64AVX2Guarded
	s.C64Parts.Real = crealComplex64AVX2Guarded
	s.C64Parts.Imag = cimagComplex64AVX2Guarded
	s.C64Parts.Scale = cscaleComplex64AVX2Guarded
	s.C64Parts.FromParts = cfromPartsComplex64AVX2Guarded
	s.C128.Add = caddComplex128AVX2Guarded
	s.C128.Sub = csubComplex128AVX2Guarded
	s.C128.Mul = cmulComplex128AVX2Guarded
	s.C128.Div = cdivComplex128AVX2Guarded
	s.C128.Neg = cnegComplex128AVX2Guarded
	s.C128.Conj = cconjComplex128AVX2Guarded
	s.C128Parts.Abs = cabsComplex128AVX2Guarded
	s.C128Parts.Real = crealComplex128AVX2Guarded
	s.C128Parts.Imag = cimagComplex128AVX2Guarded
	s.C128Parts.Scale = cscaleComplex128AVX2Guarded
	s.C128Parts.FromParts = cfromPartsComplex128AVX2Guarded
}
