// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/compare.c
// Target: amd64/avx512

//go:build amd64 && !purego

package amd64

import "runtime"

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

//go:noescape
func eqFloat32MaskAVX512(dst []bool, a []float32, b []float32)

//go:noescape
func eqScalarFloat32MaskAVX512(dst []bool, a []float32, v float32)

//go:noescape
func neFloat32MaskAVX512(dst []bool, a []float32, b []float32)

//go:noescape
func neScalarFloat32MaskAVX512(dst []bool, a []float32, v float32)

//go:noescape
func ltFloat32MaskAVX512(dst []bool, a []float32, b []float32)

//go:noescape
func ltScalarFloat32MaskAVX512(dst []bool, a []float32, v float32)

//go:noescape
func leFloat32MaskAVX512(dst []bool, a []float32, b []float32)

//go:noescape
func leScalarFloat32MaskAVX512(dst []bool, a []float32, v float32)

//go:noescape
func gtFloat32MaskAVX512(dst []bool, a []float32, b []float32)

//go:noescape
func gtScalarFloat32MaskAVX512(dst []bool, a []float32, v float32)

//go:noescape
func geFloat32MaskAVX512(dst []bool, a []float32, b []float32)

//go:noescape
func geScalarFloat32MaskAVX512(dst []bool, a []float32, v float32)

//go:noescape
func selectFloat32AVX512(dst []float32, mask []bool, yes []float32, no []float32)

//go:noescape
func eqFloat64MaskAVX512(dst []bool, a []float64, b []float64)

//go:noescape
func eqScalarFloat64MaskAVX512(dst []bool, a []float64, v float64)

//go:noescape
func neFloat64MaskAVX512(dst []bool, a []float64, b []float64)

//go:noescape
func neScalarFloat64MaskAVX512(dst []bool, a []float64, v float64)

//go:noescape
func ltFloat64MaskAVX512(dst []bool, a []float64, b []float64)

//go:noescape
func ltScalarFloat64MaskAVX512(dst []bool, a []float64, v float64)

//go:noescape
func leFloat64MaskAVX512(dst []bool, a []float64, b []float64)

//go:noescape
func leScalarFloat64MaskAVX512(dst []bool, a []float64, v float64)

//go:noescape
func gtFloat64MaskAVX512(dst []bool, a []float64, b []float64)

//go:noescape
func gtScalarFloat64MaskAVX512(dst []bool, a []float64, v float64)

//go:noescape
func geFloat64MaskAVX512(dst []bool, a []float64, b []float64)

//go:noescape
func geScalarFloat64MaskAVX512(dst []bool, a []float64, v float64)

//go:noescape
func selectFloat64AVX512(dst []float64, mask []bool, yes []float64, no []float64)

//go:noescape
func eqInt32MaskAVX512(dst []bool, a []int32, b []int32)

//go:noescape
func eqScalarInt32MaskAVX512(dst []bool, a []int32, v int32)

//go:noescape
func neInt32MaskAVX512(dst []bool, a []int32, b []int32)

//go:noescape
func neScalarInt32MaskAVX512(dst []bool, a []int32, v int32)

//go:noescape
func ltInt32MaskAVX512(dst []bool, a []int32, b []int32)

//go:noescape
func ltScalarInt32MaskAVX512(dst []bool, a []int32, v int32)

//go:noescape
func leInt32MaskAVX512(dst []bool, a []int32, b []int32)

//go:noescape
func leScalarInt32MaskAVX512(dst []bool, a []int32, v int32)

//go:noescape
func gtInt32MaskAVX512(dst []bool, a []int32, b []int32)

//go:noescape
func gtScalarInt32MaskAVX512(dst []bool, a []int32, v int32)

//go:noescape
func geInt32MaskAVX512(dst []bool, a []int32, b []int32)

//go:noescape
func geScalarInt32MaskAVX512(dst []bool, a []int32, v int32)

//go:noescape
func selectInt32AVX512(dst []int32, mask []bool, yes []int32, no []int32)

//go:noescape
func eqInt64MaskAVX512(dst []bool, a []int64, b []int64)

//go:noescape
func eqScalarInt64MaskAVX512(dst []bool, a []int64, v int64)

//go:noescape
func neInt64MaskAVX512(dst []bool, a []int64, b []int64)

//go:noescape
func neScalarInt64MaskAVX512(dst []bool, a []int64, v int64)

//go:noescape
func ltInt64MaskAVX512(dst []bool, a []int64, b []int64)

//go:noescape
func ltScalarInt64MaskAVX512(dst []bool, a []int64, v int64)

//go:noescape
func leInt64MaskAVX512(dst []bool, a []int64, b []int64)

//go:noescape
func leScalarInt64MaskAVX512(dst []bool, a []int64, v int64)

//go:noescape
func gtInt64MaskAVX512(dst []bool, a []int64, b []int64)

//go:noescape
func gtScalarInt64MaskAVX512(dst []bool, a []int64, v int64)

//go:noescape
func geInt64MaskAVX512(dst []bool, a []int64, b []int64)

//go:noescape
func geScalarInt64MaskAVX512(dst []bool, a []int64, v int64)

//go:noescape
func selectInt64AVX512(dst []int64, mask []bool, yes []int64, no []int64)

//go:noescape
func maskAllAVX512(m []bool) bool

//go:noescape
func maskAnyAVX512(m []bool) bool

//go:noescape
func maskCountAVX512(m []bool) int

//go:noescape
func maskAndAVX512(dst []bool, a []bool, b []bool)

//go:noescape
func maskOrAVX512(dst []bool, a []bool, b []bool)

//go:noescape
func maskXorAVX512(dst []bool, a []bool, b []bool)

//go:noescape
func maskNotAVX512(dst []bool, a []bool)
