// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/elementwise.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

//go:noescape
func addFloat32AVX2(dst []float32, a []float32, b []float32)

//go:noescape
func addFloat64AVX2(dst []float64, a []float64, b []float64)

//go:noescape
func subFloat32AVX2(dst []float32, a []float32, b []float32)

//go:noescape
func subFloat64AVX2(dst []float64, a []float64, b []float64)

//go:noescape
func mulFloat32AVX2(dst []float32, a []float32, b []float32)

//go:noescape
func mulFloat64AVX2(dst []float64, a []float64, b []float64)

//go:noescape
func addInt32AVX2(dst []int32, a []int32, b []int32)

//go:noescape
func addInt64AVX2(dst []int64, a []int64, b []int64)

//go:noescape
func scaleFloat32AVX2(dst []float32, a []float32, s float32)

//go:noescape
func scaleFloat64AVX2(dst []float64, a []float64, s float64)

//go:noescape
func addScaledFloat32AVX2(dst []float32, a []float32, b []float32, s float32)

//go:noescape
func addScaledFloat64AVX2(dst []float64, a []float64, b []float64, s float64)

//go:noescape
func sumFloat32AVX2(a []float32) float32

//go:noescape
func sumFloat64AVX2(a []float64) float64

//go:noescape
func dotFloat32AVX2(a []float32, b []float32) float32

//go:noescape
func dotFloat64AVX2(a []float64, b []float64) float64
