// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/fastmath.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func fastExpFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Exp(dst, a)
		return
	}
	fastExpFloat32AVX2(dst[:n:n], a)
}

func fastExp2Float32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Exp2(dst, a)
		return
	}
	fastExp2Float32AVX2(dst[:n:n], a)
}

func fastExpm1Float32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Expm1(dst, a)
		return
	}
	fastExpm1Float32AVX2(dst[:n:n], a)
}

func fastLogFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log(dst, a)
		return
	}
	fastLogFloat32AVX2(dst[:n:n], a)
}

func fastLog2Float32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log2(dst, a)
		return
	}
	fastLog2Float32AVX2(dst[:n:n], a)
}

func fastLog10Float32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log10(dst, a)
		return
	}
	fastLog10Float32AVX2(dst[:n:n], a)
}

func fastLog1pFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log1p(dst, a)
		return
	}
	fastLog1pFloat32AVX2(dst[:n:n], a)
}

func fastCbrtFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cbrt(dst, a)
		return
	}
	fastCbrtFloat32AVX2(dst[:n:n], a)
}

func fastSigmoidFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sigmoid(dst, a)
		return
	}
	fastSigmoidFloat32AVX2(dst[:n:n], a)
}

func fastSinFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sin(dst, a)
		return
	}
	fastSinFloat32AVX2(dst[:n:n], a)
}

func fastCosFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cos(dst, a)
		return
	}
	fastCosFloat32AVX2(dst[:n:n], a)
}

func fastTanFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Tan(dst, a)
		return
	}
	fastTanFloat32AVX2(dst[:n:n], a)
}

func fastAsinFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Asin(dst, a)
		return
	}
	fastAsinFloat32AVX2(dst[:n:n], a)
}

func fastAcosFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Acos(dst, a)
		return
	}
	fastAcosFloat32AVX2(dst[:n:n], a)
}

func fastAtanFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Atan(dst, a)
		return
	}
	fastAtanFloat32AVX2(dst[:n:n], a)
}

func fastSinhFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sinh(dst, a)
		return
	}
	fastSinhFloat32AVX2(dst[:n:n], a)
}

func fastCoshFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cosh(dst, a)
		return
	}
	fastCoshFloat32AVX2(dst[:n:n], a)
}

func fastTanhFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Tanh(dst, a)
		return
	}
	fastTanhFloat32AVX2(dst[:n:n], a)
}

func fastAsinhFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Asinh(dst, a)
		return
	}
	fastAsinhFloat32AVX2(dst[:n:n], a)
}

func fastAcoshFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Acosh(dst, a)
		return
	}
	fastAcoshFloat32AVX2(dst[:n:n], a)
}

func fastAtanhFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Atanh(dst, a)
		return
	}
	fastAtanhFloat32AVX2(dst[:n:n], a)
}

func fastErfFloat32AVX2Guarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Erf(dst, a)
		return
	}
	fastErfFloat32AVX2(dst[:n:n], a)
}

func fastPowFloat32AVX2Guarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Pow(dst, a, b)
		return
	}
	fastPowFloat32AVX2(dst[:n:n], a, b)
}

func fastAtan2Float32AVX2Guarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Atan2(dst, a, b)
		return
	}
	fastAtan2Float32AVX2(dst[:n:n], a, b)
}

func fastHypotFloat32AVX2Guarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Hypot(dst, a, b)
		return
	}
	fastHypotFloat32AVX2(dst[:n:n], a, b)
}

func fastExpFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Exp(dst, a)
		return
	}
	fastExpFloat64AVX2(dst[:n:n], a)
}

func fastExp2Float64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Exp2(dst, a)
		return
	}
	fastExp2Float64AVX2(dst[:n:n], a)
}

func fastExpm1Float64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Expm1(dst, a)
		return
	}
	fastExpm1Float64AVX2(dst[:n:n], a)
}

func fastLogFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log(dst, a)
		return
	}
	fastLogFloat64AVX2(dst[:n:n], a)
}

func fastLog2Float64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log2(dst, a)
		return
	}
	fastLog2Float64AVX2(dst[:n:n], a)
}

func fastLog10Float64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log10(dst, a)
		return
	}
	fastLog10Float64AVX2(dst[:n:n], a)
}

func fastLog1pFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Log1p(dst, a)
		return
	}
	fastLog1pFloat64AVX2(dst[:n:n], a)
}

func fastCbrtFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cbrt(dst, a)
		return
	}
	fastCbrtFloat64AVX2(dst[:n:n], a)
}

func fastSigmoidFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sigmoid(dst, a)
		return
	}
	fastSigmoidFloat64AVX2(dst[:n:n], a)
}

func fastSinFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sin(dst, a)
		return
	}
	fastSinFloat64AVX2(dst[:n:n], a)
}

func fastCosFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cos(dst, a)
		return
	}
	fastCosFloat64AVX2(dst[:n:n], a)
}

func fastTanFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Tan(dst, a)
		return
	}
	fastTanFloat64AVX2(dst[:n:n], a)
}

func fastAsinFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Asin(dst, a)
		return
	}
	fastAsinFloat64AVX2(dst[:n:n], a)
}

func fastAcosFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Acos(dst, a)
		return
	}
	fastAcosFloat64AVX2(dst[:n:n], a)
}

func fastAtanFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Atan(dst, a)
		return
	}
	fastAtanFloat64AVX2(dst[:n:n], a)
}

func fastSinhFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Sinh(dst, a)
		return
	}
	fastSinhFloat64AVX2(dst[:n:n], a)
}

func fastCoshFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Cosh(dst, a)
		return
	}
	fastCoshFloat64AVX2(dst[:n:n], a)
}

func fastTanhFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Tanh(dst, a)
		return
	}
	fastTanhFloat64AVX2(dst[:n:n], a)
}

func fastAsinhFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Asinh(dst, a)
		return
	}
	fastAsinhFloat64AVX2(dst[:n:n], a)
}

func fastAcoshFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Acosh(dst, a)
		return
	}
	fastAcoshFloat64AVX2(dst[:n:n], a)
}

func fastAtanhFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Atanh(dst, a)
		return
	}
	fastAtanhFloat64AVX2(dst[:n:n], a)
}

func fastErfFloat64AVX2Guarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 4 {
		ref.Erf(dst, a)
		return
	}
	fastErfFloat64AVX2(dst[:n:n], a)
}

func fastPowFloat64AVX2Guarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Pow(dst, a, b)
		return
	}
	fastPowFloat64AVX2(dst[:n:n], a, b)
}

func fastAtan2Float64AVX2Guarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Atan2(dst, a, b)
		return
	}
	fastAtan2Float64AVX2(dst[:n:n], a, b)
}

func fastHypotFloat64AVX2Guarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Hypot(dst, a, b)
		return
	}
	fastHypotFloat64AVX2(dst[:n:n], a, b)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("avx2")
	s.F32.FastExp = fastExpFloat32AVX2Guarded
	s.F32.FastExp2 = fastExp2Float32AVX2Guarded
	s.F32.FastExpm1 = fastExpm1Float32AVX2Guarded
	s.F32.FastLog = fastLogFloat32AVX2Guarded
	s.F32.FastLog2 = fastLog2Float32AVX2Guarded
	s.F32.FastLog10 = fastLog10Float32AVX2Guarded
	s.F32.FastLog1p = fastLog1pFloat32AVX2Guarded
	s.F32.FastCbrt = fastCbrtFloat32AVX2Guarded
	s.F32.FastSigmoid = fastSigmoidFloat32AVX2Guarded
	s.F32.FastSin = fastSinFloat32AVX2Guarded
	s.F32.FastCos = fastCosFloat32AVX2Guarded
	s.F32.FastTan = fastTanFloat32AVX2Guarded
	s.F32.FastAsin = fastAsinFloat32AVX2Guarded
	s.F32.FastAcos = fastAcosFloat32AVX2Guarded
	s.F32.FastAtan = fastAtanFloat32AVX2Guarded
	s.F32.FastSinh = fastSinhFloat32AVX2Guarded
	s.F32.FastCosh = fastCoshFloat32AVX2Guarded
	s.F32.FastTanh = fastTanhFloat32AVX2Guarded
	s.F32.FastAsinh = fastAsinhFloat32AVX2Guarded
	s.F32.FastAcosh = fastAcoshFloat32AVX2Guarded
	s.F32.FastAtanh = fastAtanhFloat32AVX2Guarded
	s.F32.FastErf = fastErfFloat32AVX2Guarded
	s.F32.FastPow = fastPowFloat32AVX2Guarded
	s.F32.FastAtan2 = fastAtan2Float32AVX2Guarded
	s.F32.FastHypot = fastHypotFloat32AVX2Guarded
	s.F64.FastExp = fastExpFloat64AVX2Guarded
	s.F64.FastExp2 = fastExp2Float64AVX2Guarded
	s.F64.FastExpm1 = fastExpm1Float64AVX2Guarded
	s.F64.FastLog = fastLogFloat64AVX2Guarded
	s.F64.FastLog2 = fastLog2Float64AVX2Guarded
	s.F64.FastLog10 = fastLog10Float64AVX2Guarded
	s.F64.FastLog1p = fastLog1pFloat64AVX2Guarded
	s.F64.FastCbrt = fastCbrtFloat64AVX2Guarded
	s.F64.FastSigmoid = fastSigmoidFloat64AVX2Guarded
	s.F64.FastSin = fastSinFloat64AVX2Guarded
	s.F64.FastCos = fastCosFloat64AVX2Guarded
	s.F64.FastTan = fastTanFloat64AVX2Guarded
	s.F64.FastAsin = fastAsinFloat64AVX2Guarded
	s.F64.FastAcos = fastAcosFloat64AVX2Guarded
	s.F64.FastAtan = fastAtanFloat64AVX2Guarded
	s.F64.FastSinh = fastSinhFloat64AVX2Guarded
	s.F64.FastCosh = fastCoshFloat64AVX2Guarded
	s.F64.FastTanh = fastTanhFloat64AVX2Guarded
	s.F64.FastAsinh = fastAsinhFloat64AVX2Guarded
	s.F64.FastAcosh = fastAcoshFloat64AVX2Guarded
	s.F64.FastAtanh = fastAtanhFloat64AVX2Guarded
	s.F64.FastErf = fastErfFloat64AVX2Guarded
	s.F64.FastPow = fastPowFloat64AVX2Guarded
	s.F64.FastAtan2 = fastAtan2Float64AVX2Guarded
	s.F64.FastHypot = fastHypotFloat64AVX2Guarded
}
