// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/lz4.c
// Target: amd64/avx512

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func Lz4BlockDecodeAVX512(dst []byte, src []byte) int {
	if len(dst) < 0 || len(src) == 0 {
		return ref.LZ4BlockDecode(dst, src)
	}
	return lz4BlockDecodeAVX512(dst, src)
}

func registerLz4AVX512(s *kernel.Set) {
	s.Bytes.LZ4BlockDecode = Lz4BlockDecodeAVX512
}
