// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/numeric.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func normFloat32AVX2Guarded(a []float32) float32 {
	if len(a) < 0 {
		return ref.NormFloat(a)
	}
	return normFloat32AVX2(a)
}

func polyEvalFloat32AVX2Guarded(dst []float32, x []float32, coeffs []float32) {
	if len(dst) < 16 {
		ref.PolyEval(dst, x, coeffs)
		return
	}
	polyEvalFloat32AVX2(dst, x, coeffs)
}

func convolveFloat32AVX2Guarded(dst []float32, sig []float32, ker []float32) {
	if len(dst) < 16 {
		ref.Convolve(dst, sig, ker)
		return
	}
	convolveFloat32AVX2(dst, sig, ker)
}

func correlateFloat32AVX2Guarded(dst []float32, sig []float32, ker []float32) {
	if len(dst) < 16 {
		ref.Correlate(dst, sig, ker)
		return
	}
	correlateFloat32AVX2(dst, sig, ker)
}

func normFloat64AVX2Guarded(a []float64) float64 {
	if len(a) < 0 {
		return ref.NormFloat(a)
	}
	return normFloat64AVX2(a)
}

func polyEvalFloat64AVX2Guarded(dst []float64, x []float64, coeffs []float64) {
	if len(dst) < 16 {
		ref.PolyEval(dst, x, coeffs)
		return
	}
	polyEvalFloat64AVX2(dst, x, coeffs)
}

func convolveFloat64AVX2Guarded(dst []float64, sig []float64, ker []float64) {
	if len(dst) < 16 {
		ref.Convolve(dst, sig, ker)
		return
	}
	convolveFloat64AVX2(dst, sig, ker)
}

func correlateFloat64AVX2Guarded(dst []float64, sig []float64, ker []float64) {
	if len(dst) < 16 {
		ref.Correlate(dst, sig, ker)
		return
	}
	correlateFloat64AVX2(dst, sig, ker)
}

func tileFloat32AVX2Guarded(dst []float32, pattern []float32) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileFloat32AVX2(dst, pattern)
}

func gatherFloat32AVX2Guarded(dst []float32, src []float32, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherFloat32AVX2(dst, src, idx)
}

func tileFloat64AVX2Guarded(dst []float64, pattern []float64) {
	if len(dst) < 16 {
		ref.Tile(dst, pattern)
		return
	}
	tileFloat64AVX2(dst, pattern)
}

func gatherFloat64AVX2Guarded(dst []float64, src []float64, idx []int32) {
	if len(dst) < 16 {
		ref.Gather(dst, src, idx)
		return
	}
	gatherFloat64AVX2(dst, src, idx)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("avx2")
	s.F32.Norm = normFloat32AVX2Guarded
	s.F32.PolyEval = polyEvalFloat32AVX2Guarded
	s.F32.Convolve = convolveFloat32AVX2Guarded
	s.F32.Correlate = correlateFloat32AVX2Guarded
	s.F64.Norm = normFloat64AVX2Guarded
	s.F64.PolyEval = polyEvalFloat64AVX2Guarded
	s.F64.Convolve = convolveFloat64AVX2Guarded
	s.F64.Correlate = correlateFloat64AVX2Guarded
	s.F32.Tile = tileFloat32AVX2Guarded
	s.F32.Gather = gatherFloat32AVX2Guarded
	s.F64.Tile = tileFloat64AVX2Guarded
	s.F64.Gather = gatherFloat64AVX2Guarded
}
