// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/reduce.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import "runtime"

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

//go:noescape
func minrFloat32AVX2(a []float32) float32

//go:noescape
func maxrFloat32AVX2(a []float32) float32

//go:noescape
func sumsqFloat32AVX2(a []float32) float32

//go:noescape
func sumsqdevFloat32AVX2(a []float32, c float32) float32

//go:noescape
func sumsqdiffFloat32AVX2(a []float32, b []float32) float32

//go:noescape
func diffFloat32AVX2(dst []float32, a []float32)

//go:noescape
func minrFloat64AVX2(a []float64) float64

//go:noescape
func maxrFloat64AVX2(a []float64) float64

//go:noescape
func sumsqFloat64AVX2(a []float64) float64

//go:noescape
func sumsqdevFloat64AVX2(a []float64, c float64) float64

//go:noescape
func sumsqdiffFloat64AVX2(a []float64, b []float64) float64

//go:noescape
func diffFloat64AVX2(dst []float64, a []float64)

//go:noescape
func minrInt32AVX2(a []int32) int32

//go:noescape
func maxrInt32AVX2(a []int32) int32

//go:noescape
func sumsqInt32AVX2(a []int32) int32

//go:noescape
func sumsqdevInt32AVX2(a []int32, c int32) int32

//go:noescape
func sumsqdiffInt32AVX2(a []int32, b []int32) int32

//go:noescape
func diffInt32AVX2(dst []int32, a []int32)

//go:noescape
func minrInt64AVX2(a []int64) int64

//go:noescape
func maxrInt64AVX2(a []int64) int64

//go:noescape
func sumsqInt64AVX2(a []int64) int64

//go:noescape
func sumsqdevInt64AVX2(a []int64, c int64) int64

//go:noescape
func sumsqdiffInt64AVX2(a []int64, b []int64) int64

//go:noescape
func diffInt64AVX2(dst []int64, a []int64)

//go:noescape
func minrInt8AVX2(a []int8) int8

//go:noescape
func maxrInt8AVX2(a []int8) int8

//go:noescape
func sumsqInt8AVX2(a []int8) int8

//go:noescape
func sumsqdevInt8AVX2(a []int8, c int8) int8

//go:noescape
func sumsqdiffInt8AVX2(a []int8, b []int8) int8

//go:noescape
func diffInt8AVX2(dst []int8, a []int8)

//go:noescape
func minrInt16AVX2(a []int16) int16

//go:noescape
func maxrInt16AVX2(a []int16) int16

//go:noescape
func sumsqInt16AVX2(a []int16) int16

//go:noescape
func sumsqdevInt16AVX2(a []int16, c int16) int16

//go:noescape
func sumsqdiffInt16AVX2(a []int16, b []int16) int16

//go:noescape
func diffInt16AVX2(dst []int16, a []int16)

//go:noescape
func minrUint8AVX2(a []byte) byte

//go:noescape
func maxrUint8AVX2(a []byte) byte

//go:noescape
func sumsqUint8AVX2(a []byte) byte

//go:noescape
func sumsqdevUint8AVX2(a []byte, c byte) byte

//go:noescape
func sumsqdiffUint8AVX2(a []byte, b []byte) byte

//go:noescape
func diffUint8AVX2(dst []byte, a []byte)

//go:noescape
func minrUint16AVX2(a []uint16) uint16

//go:noescape
func maxrUint16AVX2(a []uint16) uint16

//go:noescape
func sumsqUint16AVX2(a []uint16) uint16

//go:noescape
func sumsqdevUint16AVX2(a []uint16, c uint16) uint16

//go:noescape
func sumsqdiffUint16AVX2(a []uint16, b []uint16) uint16

//go:noescape
func diffUint16AVX2(dst []uint16, a []uint16)

//go:noescape
func minrUint32AVX2(a []uint32) uint32

//go:noescape
func maxrUint32AVX2(a []uint32) uint32

//go:noescape
func sumsqUint32AVX2(a []uint32) uint32

//go:noescape
func sumsqdevUint32AVX2(a []uint32, c uint32) uint32

//go:noescape
func sumsqdiffUint32AVX2(a []uint32, b []uint32) uint32

//go:noescape
func diffUint32AVX2(dst []uint32, a []uint32)

//go:noescape
func minrUint64AVX2(a []uint64) uint64

//go:noescape
func maxrUint64AVX2(a []uint64) uint64

//go:noescape
func sumsqUint64AVX2(a []uint64) uint64

//go:noescape
func sumsqdevUint64AVX2(a []uint64, c uint64) uint64

//go:noescape
func sumsqdiffUint64AVX2(a []uint64, b []uint64) uint64

//go:noescape
func diffUint64AVX2(dst []uint64, a []uint64)

//go:noescape
func sumFloat32AVX2(a []float32) float32

//go:noescape
func dotFloat32AVX2(a []float32, b []float32) float32

//go:noescape
func l1normFloat32AVX2(a []float32) float32

//go:noescape
func l1diffFloat32AVX2(a []float32, b []float32) float32

//go:noescape
func sumFloat64AVX2(a []float64) float64

//go:noescape
func dotFloat64AVX2(a []float64, b []float64) float64

//go:noescape
func l1normFloat64AVX2(a []float64) float64

//go:noescape
func l1diffFloat64AVX2(a []float64, b []float64) float64

//go:noescape
func sumInt32AVX2(a []int32) int32

//go:noescape
func prodInt32AVX2(a []int32) int32

//go:noescape
func dotInt32AVX2(a []int32, b []int32) int32

//go:noescape
func l1normInt32AVX2(a []int32) int32

//go:noescape
func l1diffInt32AVX2(a []int32, b []int32) int32

//go:noescape
func sumInt64AVX2(a []int64) int64

//go:noescape
func prodInt64AVX2(a []int64) int64

//go:noescape
func dotInt64AVX2(a []int64, b []int64) int64

//go:noescape
func l1normInt64AVX2(a []int64) int64

//go:noescape
func l1diffInt64AVX2(a []int64, b []int64) int64

//go:noescape
func sumInt8AVX2(a []int8) int8

//go:noescape
func prodInt8AVX2(a []int8) int8

//go:noescape
func dotInt8AVX2(a []int8, b []int8) int8

//go:noescape
func l1normInt8AVX2(a []int8) int8

//go:noescape
func l1diffInt8AVX2(a []int8, b []int8) int8

//go:noescape
func sumInt16AVX2(a []int16) int16

//go:noescape
func prodInt16AVX2(a []int16) int16

//go:noescape
func dotInt16AVX2(a []int16, b []int16) int16

//go:noescape
func l1normInt16AVX2(a []int16) int16

//go:noescape
func l1diffInt16AVX2(a []int16, b []int16) int16

//go:noescape
func sumUint8AVX2(a []byte) byte

//go:noescape
func prodUint8AVX2(a []byte) byte

//go:noescape
func dotUint8AVX2(a []byte, b []byte) byte

//go:noescape
func l1normUint8AVX2(a []byte) byte

//go:noescape
func l1diffUint8AVX2(a []byte, b []byte) byte

//go:noescape
func sumUint16AVX2(a []uint16) uint16

//go:noescape
func prodUint16AVX2(a []uint16) uint16

//go:noescape
func dotUint16AVX2(a []uint16, b []uint16) uint16

//go:noescape
func l1normUint16AVX2(a []uint16) uint16

//go:noescape
func l1diffUint16AVX2(a []uint16, b []uint16) uint16

//go:noescape
func sumUint32AVX2(a []uint32) uint32

//go:noescape
func prodUint32AVX2(a []uint32) uint32

//go:noescape
func dotUint32AVX2(a []uint32, b []uint32) uint32

//go:noescape
func l1normUint32AVX2(a []uint32) uint32

//go:noescape
func l1diffUint32AVX2(a []uint32, b []uint32) uint32

//go:noescape
func sumUint64AVX2(a []uint64) uint64

//go:noescape
func prodUint64AVX2(a []uint64) uint64

//go:noescape
func dotUint64AVX2(a []uint64, b []uint64) uint64

//go:noescape
func l1normUint64AVX2(a []uint64) uint64

//go:noescape
func l1diffUint64AVX2(a []uint64, b []uint64) uint64
