// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/reduce.c
// Target: amd64/sse2

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func MinrFloat32SSE2(a []float32) float32 {
	if len(a) < 1 {
		return ref.MinReduceFloat(a)
	}
	return minrFloat32SSE2(a)
}

func MaxrFloat32SSE2(a []float32) float32 {
	if len(a) < 1 {
		return ref.MaxReduceFloat(a)
	}
	return maxrFloat32SSE2(a)
}

func SumsqFloat32SSE2(a []float32) float32 {
	if len(a) < 0 {
		return ref.SumSquaresFloat(a)
	}
	return sumsqFloat32SSE2(a)
}

func SumsqdevFloat32SSE2(a []float32, c float32) float32 {
	if len(a) < 0 {
		return ref.SumSqDevFloat(a, c)
	}
	return sumsqdevFloat32SSE2(a, c)
}

func SumsqdiffFloat32SSE2(a []float32, b []float32) float32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffFloat(a, b)
	}
	return sumsqdiffFloat32SSE2(a[:n:n], b)
}

func DiffFloat32SSE2(dst []float32, a []float32) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffFloat32SSE2(dst, a)
}

func MinrFloat64SSE2(a []float64) float64 {
	if len(a) < 1 {
		return ref.MinReduceFloat(a)
	}
	return minrFloat64SSE2(a)
}

func MaxrFloat64SSE2(a []float64) float64 {
	if len(a) < 1 {
		return ref.MaxReduceFloat(a)
	}
	return maxrFloat64SSE2(a)
}

func SumsqFloat64SSE2(a []float64) float64 {
	if len(a) < 0 {
		return ref.SumSquaresFloat(a)
	}
	return sumsqFloat64SSE2(a)
}

func SumsqdevFloat64SSE2(a []float64, c float64) float64 {
	if len(a) < 0 {
		return ref.SumSqDevFloat(a, c)
	}
	return sumsqdevFloat64SSE2(a, c)
}

func SumsqdiffFloat64SSE2(a []float64, b []float64) float64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffFloat(a, b)
	}
	return sumsqdiffFloat64SSE2(a[:n:n], b)
}

func DiffFloat64SSE2(dst []float64, a []float64) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffFloat64SSE2(dst, a)
}

func MinrInt32SSE2(a []int32) int32 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrInt32SSE2(a)
}

func MaxrInt32SSE2(a []int32) int32 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt32SSE2(a)
}

func SumsqInt32SSE2(a []int32) int32 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqInt32SSE2(a)
}

func SumsqdevInt32SSE2(a []int32, c int32) int32 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevInt32SSE2(a, c)
}

func SumsqdiffInt32SSE2(a []int32, b []int32) int32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffInt32SSE2(a[:n:n], b)
}

func DiffInt32SSE2(dst []int32, a []int32) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt32SSE2(dst, a)
}

func MinrInt64SSE2(a []int64) int64 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrInt64SSE2(a)
}

func MaxrInt64SSE2(a []int64) int64 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt64SSE2(a)
}

func SumsqInt64SSE2(a []int64) int64 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqInt64SSE2(a)
}

func SumsqdevInt64SSE2(a []int64, c int64) int64 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevInt64SSE2(a, c)
}

func SumsqdiffInt64SSE2(a []int64, b []int64) int64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffInt64SSE2(a[:n:n], b)
}

func DiffInt64SSE2(dst []int64, a []int64) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt64SSE2(dst, a)
}

func MinrInt8SSE2(a []int8) int8 {
	if len(a) < 24 {
		return ref.MinReduceInt(a)
	}
	return minrInt8SSE2(a)
}

func MaxrInt8SSE2(a []int8) int8 {
	if len(a) < 24 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt8SSE2(a)
}

func SumsqInt8SSE2(a []int8) int8 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqInt8SSE2(a)
}

func SumsqdevInt8SSE2(a []int8, c int8) int8 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevInt8SSE2(a, c)
}

func SumsqdiffInt8SSE2(a []int8, b []int8) int8 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffInt8SSE2(a[:n:n], b)
}

func DiffInt8SSE2(dst []int8, a []int8) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt8SSE2(dst, a)
}

func MinrInt16SSE2(a []int16) int16 {
	if len(a) < 16 {
		return ref.MinReduceInt(a)
	}
	return minrInt16SSE2(a)
}

func MaxrInt16SSE2(a []int16) int16 {
	if len(a) < 16 {
		return ref.MaxReduceInt(a)
	}
	return maxrInt16SSE2(a)
}

func SumsqInt16SSE2(a []int16) int16 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqInt16SSE2(a)
}

func SumsqdevInt16SSE2(a []int16, c int16) int16 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevInt16SSE2(a, c)
}

func SumsqdiffInt16SSE2(a []int16, b []int16) int16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffInt16SSE2(a[:n:n], b)
}

func DiffInt16SSE2(dst []int16, a []int16) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffInt16SSE2(dst, a)
}

func MinrUint8SSE2(a []byte) byte {
	if len(a) < 24 {
		return ref.MinReduceInt(a)
	}
	return minrUint8SSE2(a)
}

func MaxrUint8SSE2(a []byte) byte {
	if len(a) < 24 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint8SSE2(a)
}

func SumsqUint8SSE2(a []byte) byte {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqUint8SSE2(a)
}

func SumsqdevUint8SSE2(a []byte, c byte) byte {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevUint8SSE2(a, c)
}

func SumsqdiffUint8SSE2(a []byte, b []byte) byte {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffUint8SSE2(a[:n:n], b)
}

func DiffUint8SSE2(dst []byte, a []byte) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint8SSE2(dst, a)
}

func MinrUint16SSE2(a []uint16) uint16 {
	if len(a) < 16 {
		return ref.MinReduceInt(a)
	}
	return minrUint16SSE2(a)
}

func MaxrUint16SSE2(a []uint16) uint16 {
	if len(a) < 16 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint16SSE2(a)
}

func SumsqUint16SSE2(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqUint16SSE2(a)
}

func SumsqdevUint16SSE2(a []uint16, c uint16) uint16 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevUint16SSE2(a, c)
}

func SumsqdiffUint16SSE2(a []uint16, b []uint16) uint16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffUint16SSE2(a[:n:n], b)
}

func DiffUint16SSE2(dst []uint16, a []uint16) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint16SSE2(dst, a)
}

func MinrUint32SSE2(a []uint32) uint32 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrUint32SSE2(a)
}

func MaxrUint32SSE2(a []uint32) uint32 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint32SSE2(a)
}

func SumsqUint32SSE2(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqUint32SSE2(a)
}

func SumsqdevUint32SSE2(a []uint32, c uint32) uint32 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevUint32SSE2(a, c)
}

func SumsqdiffUint32SSE2(a []uint32, b []uint32) uint32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffUint32SSE2(a[:n:n], b)
}

func DiffUint32SSE2(dst []uint32, a []uint32) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint32SSE2(dst, a)
}

func MinrUint64SSE2(a []uint64) uint64 {
	if len(a) < 1 {
		return ref.MinReduceInt(a)
	}
	return minrUint64SSE2(a)
}

func MaxrUint64SSE2(a []uint64) uint64 {
	if len(a) < 1 {
		return ref.MaxReduceInt(a)
	}
	return maxrUint64SSE2(a)
}

func SumsqUint64SSE2(a []uint64) uint64 {
	if len(a) < 0 {
		return ref.SumSquaresInt(a)
	}
	return sumsqUint64SSE2(a)
}

func SumsqdevUint64SSE2(a []uint64, c uint64) uint64 {
	if len(a) < 0 {
		return ref.SumSqDevInt(a, c)
	}
	return sumsqdevUint64SSE2(a, c)
}

func SumsqdiffUint64SSE2(a []uint64, b []uint64) uint64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.SumSqDiffInt(a, b)
	}
	return sumsqdiffUint64SSE2(a[:n:n], b)
}

func DiffUint64SSE2(dst []uint64, a []uint64) {
	if len(dst) < 16 {
		ref.Diff(dst, a)
		return
	}
	diffUint64SSE2(dst, a)
}

func SumFloat32SSE2(a []float32) float32 {
	if len(a) < 0 {
		return ref.SumFloat(a)
	}
	return sumFloat32SSE2(a)
}

func DotFloat32SSE2(a []float32, b []float32) float32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotFloat(a, b)
	}
	return dotFloat32SSE2(a[:n:n], b)
}

func L1normFloat32SSE2(a []float32) float32 {
	if len(a) < 0 {
		return ref.L1NormFloat(a)
	}
	return l1normFloat32SSE2(a)
}

func L1diffFloat32SSE2(a []float32, b []float32) float32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffFloat(a, b)
	}
	return l1diffFloat32SSE2(a[:n:n], b)
}

func SumLanesFloat32SSE2(dst []float32, a []float32) {
	if len(a) < 0 {
		ref.SumLanesFloat(dst, a)
		return
	}
	sumLanesFloat32SSE2(dst, a)
}

func SparseDotFloat32SSE2(v []float32, idx []int32, x []float32) float32 {
	if len(x) < 0 {
		return ref.SparseDotFloat(v, idx, x)
	}
	return sparseDotFloat32SSE2(v, idx, x)
}

func SumFloat64SSE2(a []float64) float64 {
	if len(a) < 0 {
		return ref.SumFloat(a)
	}
	return sumFloat64SSE2(a)
}

func DotFloat64SSE2(a []float64, b []float64) float64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotFloat(a, b)
	}
	return dotFloat64SSE2(a[:n:n], b)
}

func L1normFloat64SSE2(a []float64) float64 {
	if len(a) < 0 {
		return ref.L1NormFloat(a)
	}
	return l1normFloat64SSE2(a)
}

func L1diffFloat64SSE2(a []float64, b []float64) float64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffFloat(a, b)
	}
	return l1diffFloat64SSE2(a[:n:n], b)
}

func SumLanesFloat64SSE2(dst []float64, a []float64) {
	if len(a) < 0 {
		ref.SumLanesFloat(dst, a)
		return
	}
	sumLanesFloat64SSE2(dst, a)
}

func SparseDotFloat64SSE2(v []float64, idx []int32, x []float64) float64 {
	if len(x) < 0 {
		return ref.SparseDotFloat(v, idx, x)
	}
	return sparseDotFloat64SSE2(v, idx, x)
}

func SumInt32SSE2(a []int32) int32 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt32SSE2(a)
}

func ProdInt32SSE2(a []int32) int32 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodInt32SSE2(a)
}

func DotInt32SSE2(a []int32, b []int32) int32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotInt32SSE2(a[:n:n], b)
}

func L1normInt32SSE2(a []int32) int32 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt32SSE2(a)
}

func L1diffInt32SSE2(a []int32, b []int32) int32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt32SSE2(a[:n:n], b)
}

func SumInt64SSE2(a []int64) int64 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt64SSE2(a)
}

func DotInt64SSE2(a []int64, b []int64) int64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotInt64SSE2(a[:n:n], b)
}

func L1normInt64SSE2(a []int64) int64 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt64SSE2(a)
}

func L1diffInt64SSE2(a []int64, b []int64) int64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt64SSE2(a[:n:n], b)
}

func SumInt8SSE2(a []int8) int8 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt8SSE2(a)
}

func ProdInt8SSE2(a []int8) int8 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodInt8SSE2(a)
}

func DotInt8SSE2(a []int8, b []int8) int8 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotInt8SSE2(a[:n:n], b)
}

func L1normInt8SSE2(a []int8) int8 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt8SSE2(a)
}

func L1diffInt8SSE2(a []int8, b []int8) int8 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt8SSE2(a[:n:n], b)
}

func SumInt16SSE2(a []int16) int16 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumInt16SSE2(a)
}

func ProdInt16SSE2(a []int16) int16 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodInt16SSE2(a)
}

func DotInt16SSE2(a []int16, b []int16) int16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotInt16SSE2(a[:n:n], b)
}

func L1normInt16SSE2(a []int16) int16 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normInt16SSE2(a)
}

func L1diffInt16SSE2(a []int16, b []int16) int16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffInt16SSE2(a[:n:n], b)
}

func SumUint8SSE2(a []byte) byte {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint8SSE2(a)
}

func ProdUint8SSE2(a []byte) byte {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodUint8SSE2(a)
}

func DotUint8SSE2(a []byte, b []byte) byte {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotUint8SSE2(a[:n:n], b)
}

func L1normUint8SSE2(a []byte) byte {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint8SSE2(a)
}

func L1diffUint8SSE2(a []byte, b []byte) byte {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint8SSE2(a[:n:n], b)
}

func SumUint16SSE2(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint16SSE2(a)
}

func ProdUint16SSE2(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodUint16SSE2(a)
}

func DotUint16SSE2(a []uint16, b []uint16) uint16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotUint16SSE2(a[:n:n], b)
}

func L1normUint16SSE2(a []uint16) uint16 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint16SSE2(a)
}

func L1diffUint16SSE2(a []uint16, b []uint16) uint16 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint16SSE2(a[:n:n], b)
}

func SumUint32SSE2(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint32SSE2(a)
}

func ProdUint32SSE2(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.ProdInt(a)
	}
	return prodUint32SSE2(a)
}

func DotUint32SSE2(a []uint32, b []uint32) uint32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotUint32SSE2(a[:n:n], b)
}

func L1normUint32SSE2(a []uint32) uint32 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint32SSE2(a)
}

func L1diffUint32SSE2(a []uint32, b []uint32) uint32 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint32SSE2(a[:n:n], b)
}

func SumUint64SSE2(a []uint64) uint64 {
	if len(a) < 0 {
		return ref.SumInt(a)
	}
	return sumUint64SSE2(a)
}

func DotUint64SSE2(a []uint64, b []uint64) uint64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.DotInt(a, b)
	}
	return dotUint64SSE2(a[:n:n], b)
}

func L1normUint64SSE2(a []uint64) uint64 {
	if len(a) < 0 {
		return ref.L1NormInt(a)
	}
	return l1normUint64SSE2(a)
}

func L1diffUint64SSE2(a []uint64, b []uint64) uint64 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.L1DiffInt(a, b)
	}
	return l1diffUint64SSE2(a[:n:n], b)
}

func registerReduceSSE2(s *kernel.Set) {
	s.F32.Min = MinrFloat32SSE2
	s.F32.Max = MaxrFloat32SSE2
	s.F32.SumSquares = SumsqFloat32SSE2
	s.F32.SumSqDev = SumsqdevFloat32SSE2
	s.F32.SumSqDiff = SumsqdiffFloat32SSE2
	s.F32.Diff = DiffFloat32SSE2
	s.F64.Min = MinrFloat64SSE2
	s.F64.Max = MaxrFloat64SSE2
	s.F64.SumSquares = SumsqFloat64SSE2
	s.F64.SumSqDev = SumsqdevFloat64SSE2
	s.F64.SumSqDiff = SumsqdiffFloat64SSE2
	s.F64.Diff = DiffFloat64SSE2
	s.I32.Min = MinrInt32SSE2
	s.I32.Max = MaxrInt32SSE2
	s.I32.SumSquares = SumsqInt32SSE2
	s.I32.SumSqDev = SumsqdevInt32SSE2
	s.I32.SumSqDiff = SumsqdiffInt32SSE2
	s.I32.Diff = DiffInt32SSE2
	s.I64.Min = MinrInt64SSE2
	s.I64.Max = MaxrInt64SSE2
	s.I64.SumSquares = SumsqInt64SSE2
	s.I64.SumSqDev = SumsqdevInt64SSE2
	s.I64.SumSqDiff = SumsqdiffInt64SSE2
	s.I64.Diff = DiffInt64SSE2
	s.I8.Min = MinrInt8SSE2
	s.I8.Max = MaxrInt8SSE2
	s.I8.SumSquares = SumsqInt8SSE2
	s.I8.SumSqDev = SumsqdevInt8SSE2
	s.I8.SumSqDiff = SumsqdiffInt8SSE2
	s.I8.Diff = DiffInt8SSE2
	s.I16.Min = MinrInt16SSE2
	s.I16.Max = MaxrInt16SSE2
	s.I16.SumSquares = SumsqInt16SSE2
	s.I16.SumSqDev = SumsqdevInt16SSE2
	s.I16.SumSqDiff = SumsqdiffInt16SSE2
	s.I16.Diff = DiffInt16SSE2
	s.U8.Min = MinrUint8SSE2
	s.U8.Max = MaxrUint8SSE2
	s.U8.SumSquares = SumsqUint8SSE2
	s.U8.SumSqDev = SumsqdevUint8SSE2
	s.U8.SumSqDiff = SumsqdiffUint8SSE2
	s.U8.Diff = DiffUint8SSE2
	s.U16.Min = MinrUint16SSE2
	s.U16.Max = MaxrUint16SSE2
	s.U16.SumSquares = SumsqUint16SSE2
	s.U16.SumSqDev = SumsqdevUint16SSE2
	s.U16.SumSqDiff = SumsqdiffUint16SSE2
	s.U16.Diff = DiffUint16SSE2
	s.U32.Min = MinrUint32SSE2
	s.U32.Max = MaxrUint32SSE2
	s.U32.SumSquares = SumsqUint32SSE2
	s.U32.SumSqDev = SumsqdevUint32SSE2
	s.U32.SumSqDiff = SumsqdiffUint32SSE2
	s.U32.Diff = DiffUint32SSE2
	s.U64.Min = MinrUint64SSE2
	s.U64.Max = MaxrUint64SSE2
	s.U64.SumSquares = SumsqUint64SSE2
	s.U64.SumSqDev = SumsqdevUint64SSE2
	s.U64.SumSqDiff = SumsqdiffUint64SSE2
	s.U64.Diff = DiffUint64SSE2
	s.F32.Sum = SumFloat32SSE2
	s.F32.Dot = DotFloat32SSE2
	s.F32.L1Norm = L1normFloat32SSE2
	s.F32.L1Diff = L1diffFloat32SSE2
	s.F32.SumLanes = SumLanesFloat32SSE2
	s.F32.SparseDot = SparseDotFloat32SSE2
	s.F64.Sum = SumFloat64SSE2
	s.F64.Dot = DotFloat64SSE2
	s.F64.L1Norm = L1normFloat64SSE2
	s.F64.L1Diff = L1diffFloat64SSE2
	s.F64.SumLanes = SumLanesFloat64SSE2
	s.F64.SparseDot = SparseDotFloat64SSE2
	s.I32.Sum = SumInt32SSE2
	s.I32.Prod = ProdInt32SSE2
	s.I32.Dot = DotInt32SSE2
	s.I32.L1Norm = L1normInt32SSE2
	s.I32.L1Diff = L1diffInt32SSE2
	s.I64.Sum = SumInt64SSE2
	s.I64.Dot = DotInt64SSE2
	s.I64.L1Norm = L1normInt64SSE2
	s.I64.L1Diff = L1diffInt64SSE2
	s.I8.Sum = SumInt8SSE2
	s.I8.Prod = ProdInt8SSE2
	s.I8.Dot = DotInt8SSE2
	s.I8.L1Norm = L1normInt8SSE2
	s.I8.L1Diff = L1diffInt8SSE2
	s.I16.Sum = SumInt16SSE2
	s.I16.Prod = ProdInt16SSE2
	s.I16.Dot = DotInt16SSE2
	s.I16.L1Norm = L1normInt16SSE2
	s.I16.L1Diff = L1diffInt16SSE2
	s.U8.Sum = SumUint8SSE2
	s.U8.Prod = ProdUint8SSE2
	s.U8.Dot = DotUint8SSE2
	s.U8.L1Norm = L1normUint8SSE2
	s.U8.L1Diff = L1diffUint8SSE2
	s.U16.Sum = SumUint16SSE2
	s.U16.Prod = ProdUint16SSE2
	s.U16.Dot = DotUint16SSE2
	s.U16.L1Norm = L1normUint16SSE2
	s.U16.L1Diff = L1diffUint16SSE2
	s.U32.Sum = SumUint32SSE2
	s.U32.Prod = ProdUint32SSE2
	s.U32.Dot = DotUint32SSE2
	s.U32.L1Norm = L1normUint32SSE2
	s.U32.L1Diff = L1diffUint32SSE2
	s.U64.Sum = SumUint64SSE2
	s.U64.Dot = DotUint64SSE2
	s.U64.L1Norm = L1normUint64SSE2
	s.U64.L1Diff = L1diffUint64SSE2
}
