// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/elementwise.c
// Target: amd64/avx2

//go:build amd64 && !purego

package amd64

import (
	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

func addFloat32AVX2Guarded(dst []float32, a []float32, b []float32) {
	if len(dst) < 16 {
		ref.Add(dst, a, b)
		return
	}
	addFloat32AVX2(dst, a, b)
}

func addFloat64AVX2Guarded(dst []float64, a []float64, b []float64) {
	if len(dst) < 16 {
		ref.Add(dst, a, b)
		return
	}
	addFloat64AVX2(dst, a, b)
}

func subFloat32AVX2Guarded(dst []float32, a []float32, b []float32) {
	if len(dst) < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subFloat32AVX2(dst, a, b)
}

func subFloat64AVX2Guarded(dst []float64, a []float64, b []float64) {
	if len(dst) < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subFloat64AVX2(dst, a, b)
}

func mulFloat32AVX2Guarded(dst []float32, a []float32, b []float32) {
	if len(dst) < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulFloat32AVX2(dst, a, b)
}

func mulFloat64AVX2Guarded(dst []float64, a []float64, b []float64) {
	if len(dst) < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulFloat64AVX2(dst, a, b)
}

func addInt32AVX2Guarded(dst []int32, a []int32, b []int32) {
	if len(dst) < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt32AVX2(dst, a, b)
}

func addInt64AVX2Guarded(dst []int64, a []int64, b []int64) {
	if len(dst) < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt64AVX2(dst, a, b)
}

func scaleFloat32AVX2Guarded(dst []float32, a []float32, s float32) {
	if len(dst) < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleFloat32AVX2(dst, a, s)
}

func scaleFloat64AVX2Guarded(dst []float64, a []float64, s float64) {
	if len(dst) < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleFloat64AVX2(dst, a, s)
}

func addScaledFloat32AVX2Guarded(dst []float32, a []float32, b []float32, s float32) {
	if len(dst) < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledFloat32AVX2(dst, a, b, s)
}

func addScaledFloat64AVX2Guarded(dst []float64, a []float64, b []float64, s float64) {
	if len(dst) < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledFloat64AVX2(dst, a, b, s)
}

func sumFloat32AVX2Guarded(a []float32) float32 {
	if len(a) < 0 {
		return ref.SumFloat(a)
	}
	return sumFloat32AVX2(a)
}

func sumFloat64AVX2Guarded(a []float64) float64 {
	if len(a) < 0 {
		return ref.SumFloat(a)
	}
	return sumFloat64AVX2(a)
}

func dotFloat32AVX2Guarded(a []float32, b []float32) float32 {
	if len(a) < 0 {
		return ref.DotFloat(a, b)
	}
	return dotFloat32AVX2(a, b)
}

func dotFloat64AVX2Guarded(a []float64, b []float64) float64 {
	if len(a) < 0 {
		return ref.DotFloat(a, b)
	}
	return dotFloat64AVX2(a, b)
}

func init() {
	s := backend.Base()
	s.Name = "avx2"
	s.F32.Add = addFloat32AVX2Guarded
	s.F64.Add = addFloat64AVX2Guarded
	s.F32.Sub = subFloat32AVX2Guarded
	s.F64.Sub = subFloat64AVX2Guarded
	s.F32.Mul = mulFloat32AVX2Guarded
	s.F64.Mul = mulFloat64AVX2Guarded
	s.I32.Add = addInt32AVX2Guarded
	s.I64.Add = addInt64AVX2Guarded
	s.F32.Scale = scaleFloat32AVX2Guarded
	s.F64.Scale = scaleFloat64AVX2Guarded
	s.F32.AddScaled = addScaledFloat32AVX2Guarded
	s.F64.AddScaled = addScaledFloat64AVX2Guarded
	s.F32.Sum = sumFloat32AVX2Guarded
	s.F64.Sum = sumFloat64AVX2Guarded
	s.F32.Dot = dotFloat32AVX2Guarded
	s.F64.Dot = dotFloat64AVX2Guarded
	backend.Register("avx2", s)
}
