// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/sets.c
// Target: amd64/sse2

//go:build amd64 && !purego

package amd64

import "runtime"

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

//go:noescape
func intersectInt32SSE2(dst []int32, a []int32, b []int32) int

//go:noescape
func differenceInt32SSE2(dst []int32, a []int32, b []int32) int

//go:noescape
func intersectUint32SSE2(dst []uint32, a []uint32, b []uint32) int

//go:noescape
func differenceUint32SSE2(dst []uint32, a []uint32, b []uint32) int
