// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/sets.c
// Target: amd64/avx512

//go:build amd64 && !purego

package amd64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for amd64. The build
// constraint above and the _amd64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "amd64": {}}

func IntersectInt32AVX512(dst []int32, a []int32, b []int32) int {
	if len(a) < 64 {
		return ref.IntersectInt(dst, a, b)
	}
	return intersectInt32AVX512(dst, a, b)
}

func DifferenceInt32AVX512(dst []int32, a []int32, b []int32) int {
	if len(a) < 64 {
		return ref.DifferenceInt(dst, a, b)
	}
	return differenceInt32AVX512(dst, a, b)
}

func IntersectInt64AVX512(dst []int64, a []int64, b []int64) int {
	if len(a) < 64 {
		return ref.IntersectInt(dst, a, b)
	}
	return intersectInt64AVX512(dst, a, b)
}

func DifferenceInt64AVX512(dst []int64, a []int64, b []int64) int {
	if len(a) < 64 {
		return ref.DifferenceInt(dst, a, b)
	}
	return differenceInt64AVX512(dst, a, b)
}

func IntersectUint32AVX512(dst []uint32, a []uint32, b []uint32) int {
	if len(a) < 64 {
		return ref.IntersectInt(dst, a, b)
	}
	return intersectUint32AVX512(dst, a, b)
}

func DifferenceUint32AVX512(dst []uint32, a []uint32, b []uint32) int {
	if len(a) < 64 {
		return ref.DifferenceInt(dst, a, b)
	}
	return differenceUint32AVX512(dst, a, b)
}

func IntersectUint64AVX512(dst []uint64, a []uint64, b []uint64) int {
	if len(a) < 64 {
		return ref.IntersectInt(dst, a, b)
	}
	return intersectUint64AVX512(dst, a, b)
}

func DifferenceUint64AVX512(dst []uint64, a []uint64, b []uint64) int {
	if len(a) < 64 {
		return ref.DifferenceInt(dst, a, b)
	}
	return differenceUint64AVX512(dst, a, b)
}

func registerSetsAVX512(s *kernel.Set) {
	s.I32.Intersect = IntersectInt32AVX512
	s.I32.Difference = DifferenceInt32AVX512
	s.I64.Intersect = IntersectInt64AVX512
	s.I64.Difference = DifferenceInt64AVX512
	s.U32.Intersect = IntersectUint32AVX512
	s.U32.Difference = DifferenceUint32AVX512
	s.U64.Intersect = IntersectUint64AVX512
	s.U64.Difference = DifferenceUint64AVX512
}
