// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/argreduce.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import "runtime"

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

//go:noescape
func minMaxInt32RVV(a []int32) (lo int32, hi int32)

//go:noescape
func minMaxInt64RVV(a []int64) (lo int64, hi int64)
