// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/compare.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import "runtime"

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

//go:noescape
func eqFloat32MaskRVV(dst []bool, a []float32, b []float32)

//go:noescape
func eqScalarFloat32MaskRVV(dst []bool, a []float32, v float32)

//go:noescape
func neFloat32MaskRVV(dst []bool, a []float32, b []float32)

//go:noescape
func neScalarFloat32MaskRVV(dst []bool, a []float32, v float32)

//go:noescape
func ltFloat32MaskRVV(dst []bool, a []float32, b []float32)

//go:noescape
func ltScalarFloat32MaskRVV(dst []bool, a []float32, v float32)

//go:noescape
func leFloat32MaskRVV(dst []bool, a []float32, b []float32)

//go:noescape
func leScalarFloat32MaskRVV(dst []bool, a []float32, v float32)

//go:noescape
func gtFloat32MaskRVV(dst []bool, a []float32, b []float32)

//go:noescape
func gtScalarFloat32MaskRVV(dst []bool, a []float32, v float32)

//go:noescape
func geFloat32MaskRVV(dst []bool, a []float32, b []float32)

//go:noescape
func geScalarFloat32MaskRVV(dst []bool, a []float32, v float32)

//go:noescape
func selectFloat32RVV(dst []float32, mask []bool, yes []float32, no []float32)

//go:noescape
func lowerBoundFloat32RVV(dst []int32, a []float32, q []float32)

//go:noescape
func eqFloat64MaskRVV(dst []bool, a []float64, b []float64)

//go:noescape
func eqScalarFloat64MaskRVV(dst []bool, a []float64, v float64)

//go:noescape
func neFloat64MaskRVV(dst []bool, a []float64, b []float64)

//go:noescape
func neScalarFloat64MaskRVV(dst []bool, a []float64, v float64)

//go:noescape
func ltFloat64MaskRVV(dst []bool, a []float64, b []float64)

//go:noescape
func ltScalarFloat64MaskRVV(dst []bool, a []float64, v float64)

//go:noescape
func leFloat64MaskRVV(dst []bool, a []float64, b []float64)

//go:noescape
func leScalarFloat64MaskRVV(dst []bool, a []float64, v float64)

//go:noescape
func gtFloat64MaskRVV(dst []bool, a []float64, b []float64)

//go:noescape
func gtScalarFloat64MaskRVV(dst []bool, a []float64, v float64)

//go:noescape
func geFloat64MaskRVV(dst []bool, a []float64, b []float64)

//go:noescape
func geScalarFloat64MaskRVV(dst []bool, a []float64, v float64)

//go:noescape
func selectFloat64RVV(dst []float64, mask []bool, yes []float64, no []float64)

//go:noescape
func lowerBoundFloat64RVV(dst []int32, a []float64, q []float64)

//go:noescape
func eqInt32MaskRVV(dst []bool, a []int32, b []int32)

//go:noescape
func eqScalarInt32MaskRVV(dst []bool, a []int32, v int32)

//go:noescape
func neInt32MaskRVV(dst []bool, a []int32, b []int32)

//go:noescape
func neScalarInt32MaskRVV(dst []bool, a []int32, v int32)

//go:noescape
func ltInt32MaskRVV(dst []bool, a []int32, b []int32)

//go:noescape
func ltScalarInt32MaskRVV(dst []bool, a []int32, v int32)

//go:noescape
func leInt32MaskRVV(dst []bool, a []int32, b []int32)

//go:noescape
func leScalarInt32MaskRVV(dst []bool, a []int32, v int32)

//go:noescape
func gtInt32MaskRVV(dst []bool, a []int32, b []int32)

//go:noescape
func gtScalarInt32MaskRVV(dst []bool, a []int32, v int32)

//go:noescape
func geInt32MaskRVV(dst []bool, a []int32, b []int32)

//go:noescape
func geScalarInt32MaskRVV(dst []bool, a []int32, v int32)

//go:noescape
func selectInt32RVV(dst []int32, mask []bool, yes []int32, no []int32)

//go:noescape
func lowerBoundInt32RVV(dst []int32, a []int32, q []int32)

//go:noescape
func eqInt64MaskRVV(dst []bool, a []int64, b []int64)

//go:noescape
func eqScalarInt64MaskRVV(dst []bool, a []int64, v int64)

//go:noescape
func neInt64MaskRVV(dst []bool, a []int64, b []int64)

//go:noescape
func neScalarInt64MaskRVV(dst []bool, a []int64, v int64)

//go:noescape
func ltInt64MaskRVV(dst []bool, a []int64, b []int64)

//go:noescape
func ltScalarInt64MaskRVV(dst []bool, a []int64, v int64)

//go:noescape
func leInt64MaskRVV(dst []bool, a []int64, b []int64)

//go:noescape
func leScalarInt64MaskRVV(dst []bool, a []int64, v int64)

//go:noescape
func gtInt64MaskRVV(dst []bool, a []int64, b []int64)

//go:noescape
func gtScalarInt64MaskRVV(dst []bool, a []int64, v int64)

//go:noescape
func geInt64MaskRVV(dst []bool, a []int64, b []int64)

//go:noescape
func geScalarInt64MaskRVV(dst []bool, a []int64, v int64)

//go:noescape
func selectInt64RVV(dst []int64, mask []bool, yes []int64, no []int64)

//go:noescape
func lowerBoundInt64RVV(dst []int32, a []int64, q []int64)

//go:noescape
func eqInt8MaskRVV(dst []bool, a []int8, b []int8)

//go:noescape
func eqScalarInt8MaskRVV(dst []bool, a []int8, v int8)

//go:noescape
func neInt8MaskRVV(dst []bool, a []int8, b []int8)

//go:noescape
func neScalarInt8MaskRVV(dst []bool, a []int8, v int8)

//go:noescape
func ltInt8MaskRVV(dst []bool, a []int8, b []int8)

//go:noescape
func ltScalarInt8MaskRVV(dst []bool, a []int8, v int8)

//go:noescape
func leInt8MaskRVV(dst []bool, a []int8, b []int8)

//go:noescape
func leScalarInt8MaskRVV(dst []bool, a []int8, v int8)

//go:noescape
func gtInt8MaskRVV(dst []bool, a []int8, b []int8)

//go:noescape
func gtScalarInt8MaskRVV(dst []bool, a []int8, v int8)

//go:noescape
func geInt8MaskRVV(dst []bool, a []int8, b []int8)

//go:noescape
func geScalarInt8MaskRVV(dst []bool, a []int8, v int8)

//go:noescape
func selectInt8RVV(dst []int8, mask []bool, yes []int8, no []int8)

//go:noescape
func lowerBoundInt8RVV(dst []int32, a []int8, q []int8)

//go:noescape
func eqInt16MaskRVV(dst []bool, a []int16, b []int16)

//go:noescape
func eqScalarInt16MaskRVV(dst []bool, a []int16, v int16)

//go:noescape
func neInt16MaskRVV(dst []bool, a []int16, b []int16)

//go:noescape
func neScalarInt16MaskRVV(dst []bool, a []int16, v int16)

//go:noescape
func ltInt16MaskRVV(dst []bool, a []int16, b []int16)

//go:noescape
func ltScalarInt16MaskRVV(dst []bool, a []int16, v int16)

//go:noescape
func leInt16MaskRVV(dst []bool, a []int16, b []int16)

//go:noescape
func leScalarInt16MaskRVV(dst []bool, a []int16, v int16)

//go:noescape
func gtInt16MaskRVV(dst []bool, a []int16, b []int16)

//go:noescape
func gtScalarInt16MaskRVV(dst []bool, a []int16, v int16)

//go:noescape
func geInt16MaskRVV(dst []bool, a []int16, b []int16)

//go:noescape
func geScalarInt16MaskRVV(dst []bool, a []int16, v int16)

//go:noescape
func selectInt16RVV(dst []int16, mask []bool, yes []int16, no []int16)

//go:noescape
func lowerBoundInt16RVV(dst []int32, a []int16, q []int16)

//go:noescape
func eqUint8MaskRVV(dst []bool, a []byte, b []byte)

//go:noescape
func eqScalarUint8MaskRVV(dst []bool, a []byte, v byte)

//go:noescape
func neUint8MaskRVV(dst []bool, a []byte, b []byte)

//go:noescape
func neScalarUint8MaskRVV(dst []bool, a []byte, v byte)

//go:noescape
func ltUint8MaskRVV(dst []bool, a []byte, b []byte)

//go:noescape
func ltScalarUint8MaskRVV(dst []bool, a []byte, v byte)

//go:noescape
func leUint8MaskRVV(dst []bool, a []byte, b []byte)

//go:noescape
func leScalarUint8MaskRVV(dst []bool, a []byte, v byte)

//go:noescape
func gtUint8MaskRVV(dst []bool, a []byte, b []byte)

//go:noescape
func gtScalarUint8MaskRVV(dst []bool, a []byte, v byte)

//go:noescape
func geUint8MaskRVV(dst []bool, a []byte, b []byte)

//go:noescape
func geScalarUint8MaskRVV(dst []bool, a []byte, v byte)

//go:noescape
func selectUint8RVV(dst []byte, mask []bool, yes []byte, no []byte)

//go:noescape
func lowerBoundUint8RVV(dst []int32, a []byte, q []byte)

//go:noescape
func eqUint16MaskRVV(dst []bool, a []uint16, b []uint16)

//go:noescape
func eqScalarUint16MaskRVV(dst []bool, a []uint16, v uint16)

//go:noescape
func neUint16MaskRVV(dst []bool, a []uint16, b []uint16)

//go:noescape
func neScalarUint16MaskRVV(dst []bool, a []uint16, v uint16)

//go:noescape
func ltUint16MaskRVV(dst []bool, a []uint16, b []uint16)

//go:noescape
func ltScalarUint16MaskRVV(dst []bool, a []uint16, v uint16)

//go:noescape
func leUint16MaskRVV(dst []bool, a []uint16, b []uint16)

//go:noescape
func leScalarUint16MaskRVV(dst []bool, a []uint16, v uint16)

//go:noescape
func gtUint16MaskRVV(dst []bool, a []uint16, b []uint16)

//go:noescape
func gtScalarUint16MaskRVV(dst []bool, a []uint16, v uint16)

//go:noescape
func geUint16MaskRVV(dst []bool, a []uint16, b []uint16)

//go:noescape
func geScalarUint16MaskRVV(dst []bool, a []uint16, v uint16)

//go:noescape
func selectUint16RVV(dst []uint16, mask []bool, yes []uint16, no []uint16)

//go:noescape
func lowerBoundUint16RVV(dst []int32, a []uint16, q []uint16)

//go:noescape
func eqUint32MaskRVV(dst []bool, a []uint32, b []uint32)

//go:noescape
func eqScalarUint32MaskRVV(dst []bool, a []uint32, v uint32)

//go:noescape
func neUint32MaskRVV(dst []bool, a []uint32, b []uint32)

//go:noescape
func neScalarUint32MaskRVV(dst []bool, a []uint32, v uint32)

//go:noescape
func ltUint32MaskRVV(dst []bool, a []uint32, b []uint32)

//go:noescape
func ltScalarUint32MaskRVV(dst []bool, a []uint32, v uint32)

//go:noescape
func leUint32MaskRVV(dst []bool, a []uint32, b []uint32)

//go:noescape
func leScalarUint32MaskRVV(dst []bool, a []uint32, v uint32)

//go:noescape
func gtUint32MaskRVV(dst []bool, a []uint32, b []uint32)

//go:noescape
func gtScalarUint32MaskRVV(dst []bool, a []uint32, v uint32)

//go:noescape
func geUint32MaskRVV(dst []bool, a []uint32, b []uint32)

//go:noescape
func geScalarUint32MaskRVV(dst []bool, a []uint32, v uint32)

//go:noescape
func selectUint32RVV(dst []uint32, mask []bool, yes []uint32, no []uint32)

//go:noescape
func lowerBoundUint32RVV(dst []int32, a []uint32, q []uint32)

//go:noescape
func eqUint64MaskRVV(dst []bool, a []uint64, b []uint64)

//go:noescape
func eqScalarUint64MaskRVV(dst []bool, a []uint64, v uint64)

//go:noescape
func neUint64MaskRVV(dst []bool, a []uint64, b []uint64)

//go:noescape
func neScalarUint64MaskRVV(dst []bool, a []uint64, v uint64)

//go:noescape
func ltUint64MaskRVV(dst []bool, a []uint64, b []uint64)

//go:noescape
func ltScalarUint64MaskRVV(dst []bool, a []uint64, v uint64)

//go:noescape
func leUint64MaskRVV(dst []bool, a []uint64, b []uint64)

//go:noescape
func leScalarUint64MaskRVV(dst []bool, a []uint64, v uint64)

//go:noescape
func gtUint64MaskRVV(dst []bool, a []uint64, b []uint64)

//go:noescape
func gtScalarUint64MaskRVV(dst []bool, a []uint64, v uint64)

//go:noescape
func geUint64MaskRVV(dst []bool, a []uint64, b []uint64)

//go:noescape
func geScalarUint64MaskRVV(dst []bool, a []uint64, v uint64)

//go:noescape
func selectUint64RVV(dst []uint64, mask []bool, yes []uint64, no []uint64)

//go:noescape
func lowerBoundUint64RVV(dst []int32, a []uint64, q []uint64)

//go:noescape
func maskAllRVV(m []bool) bool

//go:noescape
func maskAnyRVV(m []bool) bool

//go:noescape
func maskCountRVV(m []bool) int

//go:noescape
func maskAndRVV(dst []bool, a []bool, b []bool)

//go:noescape
func maskOrRVV(dst []bool, a []bool, b []bool)

//go:noescape
func maskXorRVV(dst []bool, a []bool, b []bool)

//go:noescape
func maskNotRVV(dst []bool, a []bool)
