// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/convert.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

func quantizeI8RVVGuarded(dst []int8, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeI8(dst, a, scale, zeroPoint)
		return
	}
	quantizeI8RVV(dst[:n:n], a, scale, zeroPoint)
}

func dequantizeI8RVVGuarded(dst []float32, a []int8, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeI8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeI8RVV(dst[:n:n], a, scale, zeroPoint)
}

func quantizeU8RVVGuarded(dst []byte, a []float32, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.QuantizeU8(dst, a, scale, zeroPoint)
		return
	}
	quantizeU8RVV(dst[:n:n], a, scale, zeroPoint)
}

func dequantizeU8RVVGuarded(dst []float32, a []byte, scale float32, zeroPoint int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DequantizeU8(dst, a, scale, zeroPoint)
		return
	}
	dequantizeU8RVV(dst[:n:n], a, scale, zeroPoint)
}

func bf16ToF32RVVGuarded(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.BF16ToF32(dst, a)
		return
	}
	bf16ToF32RVV(dst[:n:n], a)
}

func f32ToBF16RVVGuarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToBF16(dst, a)
		return
	}
	f32ToBF16RVV(dst[:n:n], a)
}

func f16ToF32RVVGuarded(dst []float32, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F16ToF32(dst, a)
		return
	}
	f16ToF32RVV(dst[:n:n], a)
}

func f32ToF16RVVGuarded(dst []uint16, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.F32ToF16(dst, a)
		return
	}
	f32ToF16RVV(dst[:n:n], a)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("rvv")
	s.Convert.QuantizeI8 = quantizeI8RVVGuarded
	s.Convert.DequantizeI8 = dequantizeI8RVVGuarded
	s.Convert.QuantizeU8 = quantizeU8RVVGuarded
	s.Convert.DequantizeU8 = dequantizeU8RVVGuarded
	s.Convert.BF16ToF32 = bf16ToF32RVVGuarded
	s.Convert.F32ToBF16 = f32ToBF16RVVGuarded
	s.Convert.F16ToF32 = f16ToF32RVVGuarded
	s.Convert.F32ToF16 = f32ToF16RVVGuarded
}
