// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/gemm.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import "runtime"

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

//go:noescape
func matMulFloat32RVV(dst []float32, a []float32, b []float32, m int, k int, n int)

//go:noescape
func gemvFloat32RVV(dst []float32, a []float32, x []float32, m int, k int)

//go:noescape
func matMulFloat64RVV(dst []float64, a []float64, b []float64, m int, k int, n int)

//go:noescape
func gemvFloat64RVV(dst []float64, a []float64, x []float64, m int, k int)

//go:noescape
func transposeFloat32RVV(dst []float32, a []float32, m int, n int)

//go:noescape
func transposeFloat64RVV(dst []float64, a []float64, m int, n int)

//go:noescape
func transposeInt32RVV(dst []int32, a []int32, m int, n int)

//go:noescape
func transposeInt64RVV(dst []int64, a []int64, m int, n int)
