// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/math.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import "runtime"

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

//go:noescape
func expFloat32RVV(dst []float32, a []float32)

//go:noescape
func exp2Float32RVV(dst []float32, a []float32)

//go:noescape
func expm1Float32RVV(dst []float32, a []float32)

//go:noescape
func logFloat32RVV(dst []float32, a []float32)

//go:noescape
func log2Float32RVV(dst []float32, a []float32)

//go:noescape
func log10Float32RVV(dst []float32, a []float32)

//go:noescape
func log1pFloat32RVV(dst []float32, a []float32)

//go:noescape
func cbrtFloat32RVV(dst []float32, a []float32)

//go:noescape
func sigmoidFloat32RVV(dst []float32, a []float32)

//go:noescape
func sinFloat32RVV(dst []float32, a []float32)

//go:noescape
func cosFloat32RVV(dst []float32, a []float32)

//go:noescape
func tanFloat32RVV(dst []float32, a []float32)

//go:noescape
func asinFloat32RVV(dst []float32, a []float32)

//go:noescape
func acosFloat32RVV(dst []float32, a []float32)

//go:noescape
func atanFloat32RVV(dst []float32, a []float32)

//go:noescape
func sinhFloat32RVV(dst []float32, a []float32)

//go:noescape
func coshFloat32RVV(dst []float32, a []float32)

//go:noescape
func tanhFloat32RVV(dst []float32, a []float32)

//go:noescape
func asinhFloat32RVV(dst []float32, a []float32)

//go:noescape
func acoshFloat32RVV(dst []float32, a []float32)

//go:noescape
func atanhFloat32RVV(dst []float32, a []float32)

//go:noescape
func erfFloat32RVV(dst []float32, a []float32)

//go:noescape
func powFloat32RVV(dst []float32, a []float32, b []float32)

//go:noescape
func atan2Float32RVV(dst []float32, a []float32, b []float32)

//go:noescape
func hypotFloat32RVV(dst []float32, a []float32, b []float32)

//go:noescape
func expFloat64RVV(dst []float64, a []float64)

//go:noescape
func exp2Float64RVV(dst []float64, a []float64)

//go:noescape
func expm1Float64RVV(dst []float64, a []float64)

//go:noescape
func logFloat64RVV(dst []float64, a []float64)

//go:noescape
func log2Float64RVV(dst []float64, a []float64)

//go:noescape
func log10Float64RVV(dst []float64, a []float64)

//go:noescape
func log1pFloat64RVV(dst []float64, a []float64)

//go:noescape
func cbrtFloat64RVV(dst []float64, a []float64)

//go:noescape
func sigmoidFloat64RVV(dst []float64, a []float64)

//go:noescape
func sinFloat64RVV(dst []float64, a []float64)

//go:noescape
func cosFloat64RVV(dst []float64, a []float64)

//go:noescape
func tanFloat64RVV(dst []float64, a []float64)

//go:noescape
func asinFloat64RVV(dst []float64, a []float64)

//go:noescape
func acosFloat64RVV(dst []float64, a []float64)

//go:noescape
func atanFloat64RVV(dst []float64, a []float64)

//go:noescape
func sinhFloat64RVV(dst []float64, a []float64)

//go:noescape
func coshFloat64RVV(dst []float64, a []float64)

//go:noescape
func tanhFloat64RVV(dst []float64, a []float64)

//go:noescape
func asinhFloat64RVV(dst []float64, a []float64)

//go:noescape
func acoshFloat64RVV(dst []float64, a []float64)

//go:noescape
func atanhFloat64RVV(dst []float64, a []float64)

//go:noescape
func erfFloat64RVV(dst []float64, a []float64)

//go:noescape
func powFloat64RVV(dst []float64, a []float64, b []float64)

//go:noescape
func atan2Float64RVV(dst []float64, a []float64, b []float64)

//go:noescape
func hypotFloat64RVV(dst []float64, a []float64, b []float64)
