// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/random.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

func RandFillU64RVV(dst []uint64, seed uint64) {
	if len(dst) < 0 {
		ref.RandFillU64(dst, seed)
		return
	}
	randFillU64RVV(dst, seed)
}

func registerRandomRVV(s *kernel.Set) {
	s.Bytes.RandFillU64 = RandFillU64RVV
}
