// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/reduce.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import "runtime"

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

//go:noescape
func minrFloat32RVV(a []float32) float32

//go:noescape
func maxrFloat32RVV(a []float32) float32

//go:noescape
func sumsqFloat32RVV(a []float32) float32

//go:noescape
func sumsqdevFloat32RVV(a []float32, c float32) float32

//go:noescape
func sumsqdiffFloat32RVV(a []float32, b []float32) float32

//go:noescape
func diffFloat32RVV(dst []float32, a []float32)

//go:noescape
func minrFloat64RVV(a []float64) float64

//go:noescape
func maxrFloat64RVV(a []float64) float64

//go:noescape
func sumsqFloat64RVV(a []float64) float64

//go:noescape
func sumsqdevFloat64RVV(a []float64, c float64) float64

//go:noescape
func sumsqdiffFloat64RVV(a []float64, b []float64) float64

//go:noescape
func diffFloat64RVV(dst []float64, a []float64)

//go:noescape
func minrInt32RVV(a []int32) int32

//go:noescape
func maxrInt32RVV(a []int32) int32

//go:noescape
func sumsqInt32RVV(a []int32) int32

//go:noescape
func sumsqdevInt32RVV(a []int32, c int32) int32

//go:noescape
func sumsqdiffInt32RVV(a []int32, b []int32) int32

//go:noescape
func diffInt32RVV(dst []int32, a []int32)

//go:noescape
func minrInt64RVV(a []int64) int64

//go:noescape
func maxrInt64RVV(a []int64) int64

//go:noescape
func sumsqInt64RVV(a []int64) int64

//go:noescape
func sumsqdevInt64RVV(a []int64, c int64) int64

//go:noescape
func sumsqdiffInt64RVV(a []int64, b []int64) int64

//go:noescape
func diffInt64RVV(dst []int64, a []int64)

//go:noescape
func minrInt8RVV(a []int8) int8

//go:noescape
func maxrInt8RVV(a []int8) int8

//go:noescape
func sumsqInt8RVV(a []int8) int8

//go:noescape
func sumsqdevInt8RVV(a []int8, c int8) int8

//go:noescape
func sumsqdiffInt8RVV(a []int8, b []int8) int8

//go:noescape
func diffInt8RVV(dst []int8, a []int8)

//go:noescape
func minrInt16RVV(a []int16) int16

//go:noescape
func maxrInt16RVV(a []int16) int16

//go:noescape
func sumsqInt16RVV(a []int16) int16

//go:noescape
func sumsqdevInt16RVV(a []int16, c int16) int16

//go:noescape
func sumsqdiffInt16RVV(a []int16, b []int16) int16

//go:noescape
func diffInt16RVV(dst []int16, a []int16)

//go:noescape
func minrUint8RVV(a []byte) byte

//go:noescape
func maxrUint8RVV(a []byte) byte

//go:noescape
func sumsqUint8RVV(a []byte) byte

//go:noescape
func sumsqdevUint8RVV(a []byte, c byte) byte

//go:noescape
func sumsqdiffUint8RVV(a []byte, b []byte) byte

//go:noescape
func diffUint8RVV(dst []byte, a []byte)

//go:noescape
func minrUint16RVV(a []uint16) uint16

//go:noescape
func maxrUint16RVV(a []uint16) uint16

//go:noescape
func sumsqUint16RVV(a []uint16) uint16

//go:noescape
func sumsqdevUint16RVV(a []uint16, c uint16) uint16

//go:noescape
func sumsqdiffUint16RVV(a []uint16, b []uint16) uint16

//go:noescape
func diffUint16RVV(dst []uint16, a []uint16)

//go:noescape
func minrUint32RVV(a []uint32) uint32

//go:noescape
func maxrUint32RVV(a []uint32) uint32

//go:noescape
func sumsqUint32RVV(a []uint32) uint32

//go:noescape
func sumsqdevUint32RVV(a []uint32, c uint32) uint32

//go:noescape
func sumsqdiffUint32RVV(a []uint32, b []uint32) uint32

//go:noescape
func diffUint32RVV(dst []uint32, a []uint32)

//go:noescape
func minrUint64RVV(a []uint64) uint64

//go:noescape
func maxrUint64RVV(a []uint64) uint64

//go:noescape
func sumsqUint64RVV(a []uint64) uint64

//go:noescape
func sumsqdevUint64RVV(a []uint64, c uint64) uint64

//go:noescape
func sumsqdiffUint64RVV(a []uint64, b []uint64) uint64

//go:noescape
func diffUint64RVV(dst []uint64, a []uint64)

//go:noescape
func sumFloat32RVV(a []float32) float32

//go:noescape
func dotFloat32RVV(a []float32, b []float32) float32

//go:noescape
func l1normFloat32RVV(a []float32) float32

//go:noescape
func l1diffFloat32RVV(a []float32, b []float32) float32

//go:noescape
func sumLanesFloat32RVV(dst []float32, a []float32)

//go:noescape
func sparseDotFloat32RVV(v []float32, idx []int32, x []float32) float32

//go:noescape
func sumFloat64RVV(a []float64) float64

//go:noescape
func dotFloat64RVV(a []float64, b []float64) float64

//go:noescape
func l1normFloat64RVV(a []float64) float64

//go:noescape
func l1diffFloat64RVV(a []float64, b []float64) float64

//go:noescape
func sumLanesFloat64RVV(dst []float64, a []float64)

//go:noescape
func sparseDotFloat64RVV(v []float64, idx []int32, x []float64) float64

//go:noescape
func sumInt32RVV(a []int32) int32

//go:noescape
func prodInt32RVV(a []int32) int32

//go:noescape
func dotInt32RVV(a []int32, b []int32) int32

//go:noescape
func l1normInt32RVV(a []int32) int32

//go:noescape
func l1diffInt32RVV(a []int32, b []int32) int32

//go:noescape
func sumInt64RVV(a []int64) int64

//go:noescape
func prodInt64RVV(a []int64) int64

//go:noescape
func dotInt64RVV(a []int64, b []int64) int64

//go:noescape
func l1normInt64RVV(a []int64) int64

//go:noescape
func l1diffInt64RVV(a []int64, b []int64) int64

//go:noescape
func sumInt8RVV(a []int8) int8

//go:noescape
func prodInt8RVV(a []int8) int8

//go:noescape
func dotInt8RVV(a []int8, b []int8) int8

//go:noescape
func l1normInt8RVV(a []int8) int8

//go:noescape
func l1diffInt8RVV(a []int8, b []int8) int8

//go:noescape
func sumInt16RVV(a []int16) int16

//go:noescape
func prodInt16RVV(a []int16) int16

//go:noescape
func dotInt16RVV(a []int16, b []int16) int16

//go:noescape
func l1normInt16RVV(a []int16) int16

//go:noescape
func l1diffInt16RVV(a []int16, b []int16) int16

//go:noescape
func sumUint8RVV(a []byte) byte

//go:noescape
func prodUint8RVV(a []byte) byte

//go:noescape
func dotUint8RVV(a []byte, b []byte) byte

//go:noescape
func l1normUint8RVV(a []byte) byte

//go:noescape
func l1diffUint8RVV(a []byte, b []byte) byte

//go:noescape
func sumUint16RVV(a []uint16) uint16

//go:noescape
func prodUint16RVV(a []uint16) uint16

//go:noescape
func dotUint16RVV(a []uint16, b []uint16) uint16

//go:noescape
func l1normUint16RVV(a []uint16) uint16

//go:noescape
func l1diffUint16RVV(a []uint16, b []uint16) uint16

//go:noescape
func sumUint32RVV(a []uint32) uint32

//go:noescape
func prodUint32RVV(a []uint32) uint32

//go:noescape
func dotUint32RVV(a []uint32, b []uint32) uint32

//go:noescape
func l1normUint32RVV(a []uint32) uint32

//go:noescape
func l1diffUint32RVV(a []uint32, b []uint32) uint32

//go:noescape
func sumUint64RVV(a []uint64) uint64

//go:noescape
func prodUint64RVV(a []uint64) uint64

//go:noescape
func dotUint64RVV(a []uint64, b []uint64) uint64

//go:noescape
func l1normUint64RVV(a []uint64) uint64

//go:noescape
func l1diffUint64RVV(a []uint64, b []uint64) uint64
