// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/scan.c
// Target: riscv64/rvv

//go:build riscv64 && !purego

package riscv64

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for riscv64. The build
// constraint above and the _riscv64 filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "riscv64": {}}

func RollingMinFloat32RVV(dst []float32, a []float32, window int) {
	if len(dst) < 16 {
		ref.RollingMinFloat(dst, a, window)
		return
	}
	rollingMinFloat32RVV(dst, a, window)
}

func RollingMaxFloat32RVV(dst []float32, a []float32, window int) {
	if len(dst) < 16 {
		ref.RollingMaxFloat(dst, a, window)
		return
	}
	rollingMaxFloat32RVV(dst, a, window)
}

func FastCumProdFloat32RVV(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.FastCumProdFloat(dst, a)
		return
	}
	fastCumProdFloat32RVV(dst[:n:n], a)
}

func FastCumSumFloat32RVV(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.FastCumSumFloat(dst, a)
		return
	}
	fastCumSumFloat32RVV(dst[:n:n], a)
}

func RollingMinFloat64RVV(dst []float64, a []float64, window int) {
	if len(dst) < 16 {
		ref.RollingMinFloat(dst, a, window)
		return
	}
	rollingMinFloat64RVV(dst, a, window)
}

func RollingMaxFloat64RVV(dst []float64, a []float64, window int) {
	if len(dst) < 16 {
		ref.RollingMaxFloat(dst, a, window)
		return
	}
	rollingMaxFloat64RVV(dst, a, window)
}

func FastCumProdFloat64RVV(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.FastCumProdFloat(dst, a)
		return
	}
	fastCumProdFloat64RVV(dst[:n:n], a)
}

func RollingMinInt32RVV(dst []int32, a []int32, window int) {
	if len(dst) < 16 {
		ref.RollingMinInt(dst, a, window)
		return
	}
	rollingMinInt32RVV(dst, a, window)
}

func RollingMaxInt32RVV(dst []int32, a []int32, window int) {
	if len(dst) < 16 {
		ref.RollingMaxInt(dst, a, window)
		return
	}
	rollingMaxInt32RVV(dst, a, window)
}

func CumMinInt32RVV(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMinInt(dst, a)
		return
	}
	cumMinInt32RVV(dst[:n:n], a)
}

func CumMaxInt32RVV(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMaxInt(dst, a)
		return
	}
	cumMaxInt32RVV(dst[:n:n], a)
}

func CumProdInt32RVV(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumProdInt(dst, a)
		return
	}
	cumProdInt32RVV(dst[:n:n], a)
}

func RollingMinInt64RVV(dst []int64, a []int64, window int) {
	if len(dst) < 16 {
		ref.RollingMinInt(dst, a, window)
		return
	}
	rollingMinInt64RVV(dst, a, window)
}

func RollingMaxInt64RVV(dst []int64, a []int64, window int) {
	if len(dst) < 16 {
		ref.RollingMaxInt(dst, a, window)
		return
	}
	rollingMaxInt64RVV(dst, a, window)
}

func CumMinInt64RVV(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMinInt(dst, a)
		return
	}
	cumMinInt64RVV(dst[:n:n], a)
}

func CumMaxInt64RVV(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CumMaxInt(dst, a)
		return
	}
	cumMaxInt64RVV(dst[:n:n], a)
}

func RleDecodeI32RVV(dst []int32, values []int32, counts []int32) int {
	if len(dst) < 0 || len(values) != len(counts) {
		return ref.RLEDecodeInt32(dst, values, counts)
	}
	return rleDecodeI32RVV(dst, values, counts)
}

func registerScanRVV(s *kernel.Set) {
	s.F32.RollingMin = RollingMinFloat32RVV
	s.F32.RollingMax = RollingMaxFloat32RVV
	s.F32.FastCumProd = FastCumProdFloat32RVV
	s.F32.FastCumSum = FastCumSumFloat32RVV
	s.F64.RollingMin = RollingMinFloat64RVV
	s.F64.RollingMax = RollingMaxFloat64RVV
	s.F64.FastCumProd = FastCumProdFloat64RVV
	s.I32.RollingMin = RollingMinInt32RVV
	s.I32.RollingMax = RollingMaxInt32RVV
	s.I32.CumMin = CumMinInt32RVV
	s.I32.CumMax = CumMaxInt32RVV
	s.I32.CumProd = CumProdInt32RVV
	s.I64.RollingMin = RollingMinInt64RVV
	s.I64.RollingMax = RollingMaxInt64RVV
	s.I64.CumMin = CumMinInt64RVV
	s.I64.CumMax = CumMaxInt64RVV
	s.Bytes.RLEDecodeInt32 = RleDecodeI32RVV
}
