// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/argreduce.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

func MinMaxFloat32VX(a []float32) (lo float32, hi float32) {
	if len(a) < 1 {
		return ref.MinMaxFloat(a)
	}
	return minMaxFloat32VX(a)
}

func MinMaxFloat64VX(a []float64) (lo float64, hi float64) {
	if len(a) < 1 {
		return ref.MinMaxFloat(a)
	}
	return minMaxFloat64VX(a)
}

func registerArgreduceVX(s *kernel.Set) {
	s.F32.MinMax = MinMaxFloat32VX
	s.F64.MinMax = MinMaxFloat64VX
}
