// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/arith.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

func addFloat32VXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addFloat32VX(dst[:n:n], a, b)
}

func subFloat32VXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subFloat32VX(dst[:n:n], a, b)
}

func mulFloat32VXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulFloat32VX(dst[:n:n], a, b)
}

func minimumFloat32VXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumFloat(dst, a, b)
		return
	}
	minimumFloat32VX(dst[:n:n], a, b)
}

func maximumFloat32VXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumFloat(dst, a, b)
		return
	}
	maximumFloat32VX(dst[:n:n], a, b)
}

func absFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsFloat(dst, a)
		return
	}
	absFloat32VX(dst[:n:n], a)
}

func negFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegFloat(dst, a)
		return
	}
	negFloat32VX(dst[:n:n], a)
}

func scaleFloat32VXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleFloat32VX(dst[:n:n], a, s)
}

func addScalarFloat32VXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarFloat32VX(dst[:n:n], a, s)
}

func subScalarFloat32VXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarFloat32VX(dst[:n:n], a, s)
}

func clampFloat32VXGuarded(dst []float32, a []float32, lo float32, hi float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampFloat(dst, a, lo, hi)
		return
	}
	clampFloat32VX(dst[:n:n], a, lo, hi)
}

func fillFloat32VXGuarded(dst []float32, v float32) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillFloat32VX(dst, v)
}

func lerpFloat32VXGuarded(dst []float32, a []float32, b []float32, t float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpFloat32VX(dst[:n:n], a, b, t)
}

func addScaledFloat32VXGuarded(dst []float32, a []float32, b []float32, s float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledFloat32VX(dst[:n:n], a, b, s)
}

func addFloat64VXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addFloat64VX(dst[:n:n], a, b)
}

func subFloat64VXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subFloat64VX(dst[:n:n], a, b)
}

func mulFloat64VXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulFloat64VX(dst[:n:n], a, b)
}

func minimumFloat64VXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumFloat(dst, a, b)
		return
	}
	minimumFloat64VX(dst[:n:n], a, b)
}

func maximumFloat64VXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumFloat(dst, a, b)
		return
	}
	maximumFloat64VX(dst[:n:n], a, b)
}

func absFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsFloat(dst, a)
		return
	}
	absFloat64VX(dst[:n:n], a)
}

func negFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegFloat(dst, a)
		return
	}
	negFloat64VX(dst[:n:n], a)
}

func scaleFloat64VXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleFloat64VX(dst[:n:n], a, s)
}

func addScalarFloat64VXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarFloat64VX(dst[:n:n], a, s)
}

func subScalarFloat64VXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarFloat64VX(dst[:n:n], a, s)
}

func clampFloat64VXGuarded(dst []float64, a []float64, lo float64, hi float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampFloat(dst, a, lo, hi)
		return
	}
	clampFloat64VX(dst[:n:n], a, lo, hi)
}

func fillFloat64VXGuarded(dst []float64, v float64) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillFloat64VX(dst, v)
}

func lerpFloat64VXGuarded(dst []float64, a []float64, b []float64, t float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpFloat64VX(dst[:n:n], a, b, t)
}

func addScaledFloat64VXGuarded(dst []float64, a []float64, b []float64, s float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledFloat64VX(dst[:n:n], a, b, s)
}

func rampFloat64VXGuarded(dst []float64, start float64, step float64) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampFloat64VX(dst, start, step)
}

func addInt32VXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt32VX(dst[:n:n], a, b)
}

func subInt32VXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt32VX(dst[:n:n], a, b)
}

func mulInt32VXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulInt32VX(dst[:n:n], a, b)
}

func minimumInt32VXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt32VX(dst[:n:n], a, b)
}

func maximumInt32VXGuarded(dst []int32, a []int32, b []int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt32VX(dst[:n:n], a, b)
}

func absInt32VXGuarded(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt32VX(dst[:n:n], a)
}

func negInt32VXGuarded(dst []int32, a []int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt32VX(dst[:n:n], a)
}

func scaleInt32VXGuarded(dst []int32, a []int32, s int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleInt32VX(dst[:n:n], a, s)
}

func addScalarInt32VXGuarded(dst []int32, a []int32, s int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt32VX(dst[:n:n], a, s)
}

func subScalarInt32VXGuarded(dst []int32, a []int32, s int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt32VX(dst[:n:n], a, s)
}

func clampInt32VXGuarded(dst []int32, a []int32, lo int32, hi int32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt32VX(dst[:n:n], a, lo, hi)
}

func fillInt32VXGuarded(dst []int32, v int32) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt32VX(dst, v)
}

func lerpInt32VXGuarded(dst []int32, a []int32, b []int32, t int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpInt32VX(dst[:n:n], a, b, t)
}

func addScaledInt32VXGuarded(dst []int32, a []int32, b []int32, s int32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledInt32VX(dst[:n:n], a, b, s)
}

func rampInt32VXGuarded(dst []int32, start int32, step int32) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampInt32VX(dst, start, step)
}

func addInt64VXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt64VX(dst[:n:n], a, b)
}

func subInt64VXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt64VX(dst[:n:n], a, b)
}

func minimumInt64VXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt64VX(dst[:n:n], a, b)
}

func maximumInt64VXGuarded(dst []int64, a []int64, b []int64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt64VX(dst[:n:n], a, b)
}

func absInt64VXGuarded(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt64VX(dst[:n:n], a)
}

func negInt64VXGuarded(dst []int64, a []int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt64VX(dst[:n:n], a)
}

func addScalarInt64VXGuarded(dst []int64, a []int64, s int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt64VX(dst[:n:n], a, s)
}

func subScalarInt64VXGuarded(dst []int64, a []int64, s int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt64VX(dst[:n:n], a, s)
}

func clampInt64VXGuarded(dst []int64, a []int64, lo int64, hi int64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt64VX(dst[:n:n], a, lo, hi)
}

func fillInt64VXGuarded(dst []int64, v int64) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt64VX(dst, v)
}

func addInt8VXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt8VX(dst[:n:n], a, b)
}

func subInt8VXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt8VX(dst[:n:n], a, b)
}

func mulInt8VXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulInt8VX(dst[:n:n], a, b)
}

func minimumInt8VXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt8VX(dst[:n:n], a, b)
}

func maximumInt8VXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt8VX(dst[:n:n], a, b)
}

func absInt8VXGuarded(dst []int8, a []int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt8VX(dst[:n:n], a)
}

func negInt8VXGuarded(dst []int8, a []int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt8VX(dst[:n:n], a)
}

func scaleInt8VXGuarded(dst []int8, a []int8, s int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleInt8VX(dst[:n:n], a, s)
}

func addScalarInt8VXGuarded(dst []int8, a []int8, s int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt8VX(dst[:n:n], a, s)
}

func subScalarInt8VXGuarded(dst []int8, a []int8, s int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt8VX(dst[:n:n], a, s)
}

func clampInt8VXGuarded(dst []int8, a []int8, lo int8, hi int8) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt8VX(dst[:n:n], a, lo, hi)
}

func fillInt8VXGuarded(dst []int8, v int8) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt8VX(dst, v)
}

func lerpInt8VXGuarded(dst []int8, a []int8, b []int8, t int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpInt8VX(dst[:n:n], a, b, t)
}

func addScaledInt8VXGuarded(dst []int8, a []int8, b []int8, s int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledInt8VX(dst[:n:n], a, b, s)
}

func rampInt8VXGuarded(dst []int8, start int8, step int8) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampInt8VX(dst, start, step)
}

func addInt16VXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addInt16VX(dst[:n:n], a, b)
}

func subInt16VXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subInt16VX(dst[:n:n], a, b)
}

func mulInt16VXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulInt16VX(dst[:n:n], a, b)
}

func minimumInt16VXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumInt16VX(dst[:n:n], a, b)
}

func maximumInt16VXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumInt16VX(dst[:n:n], a, b)
}

func absInt16VXGuarded(dst []int16, a []int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absInt16VX(dst[:n:n], a)
}

func negInt16VXGuarded(dst []int16, a []int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negInt16VX(dst[:n:n], a)
}

func scaleInt16VXGuarded(dst []int16, a []int16, s int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleInt16VX(dst[:n:n], a, s)
}

func addScalarInt16VXGuarded(dst []int16, a []int16, s int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarInt16VX(dst[:n:n], a, s)
}

func subScalarInt16VXGuarded(dst []int16, a []int16, s int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarInt16VX(dst[:n:n], a, s)
}

func clampInt16VXGuarded(dst []int16, a []int16, lo int16, hi int16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampInt16VX(dst[:n:n], a, lo, hi)
}

func fillInt16VXGuarded(dst []int16, v int16) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillInt16VX(dst, v)
}

func lerpInt16VXGuarded(dst []int16, a []int16, b []int16, t int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpInt16VX(dst[:n:n], a, b, t)
}

func addScaledInt16VXGuarded(dst []int16, a []int16, b []int16, s int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledInt16VX(dst[:n:n], a, b, s)
}

func rampInt16VXGuarded(dst []int16, start int16, step int16) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampInt16VX(dst, start, step)
}

func addUint8VXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint8VX(dst[:n:n], a, b)
}

func subUint8VXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint8VX(dst[:n:n], a, b)
}

func mulUint8VXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulUint8VX(dst[:n:n], a, b)
}

func minimumUint8VXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint8VX(dst[:n:n], a, b)
}

func maximumUint8VXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint8VX(dst[:n:n], a, b)
}

func absUint8VXGuarded(dst []byte, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint8VX(dst[:n:n], a)
}

func negUint8VXGuarded(dst []byte, a []byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint8VX(dst[:n:n], a)
}

func scaleUint8VXGuarded(dst []byte, a []byte, s byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleUint8VX(dst[:n:n], a, s)
}

func addScalarUint8VXGuarded(dst []byte, a []byte, s byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint8VX(dst[:n:n], a, s)
}

func subScalarUint8VXGuarded(dst []byte, a []byte, s byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint8VX(dst[:n:n], a, s)
}

func clampUint8VXGuarded(dst []byte, a []byte, lo byte, hi byte) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint8VX(dst[:n:n], a, lo, hi)
}

func fillUint8VXGuarded(dst []byte, v byte) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint8VX(dst, v)
}

func lerpUint8VXGuarded(dst []byte, a []byte, b []byte, t byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpUint8VX(dst[:n:n], a, b, t)
}

func addScaledUint8VXGuarded(dst []byte, a []byte, b []byte, s byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledUint8VX(dst[:n:n], a, b, s)
}

func rampUint8VXGuarded(dst []byte, start byte, step byte) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampUint8VX(dst, start, step)
}

func addUint16VXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint16VX(dst[:n:n], a, b)
}

func subUint16VXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint16VX(dst[:n:n], a, b)
}

func mulUint16VXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulUint16VX(dst[:n:n], a, b)
}

func minimumUint16VXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint16VX(dst[:n:n], a, b)
}

func maximumUint16VXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint16VX(dst[:n:n], a, b)
}

func absUint16VXGuarded(dst []uint16, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint16VX(dst[:n:n], a)
}

func negUint16VXGuarded(dst []uint16, a []uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint16VX(dst[:n:n], a)
}

func scaleUint16VXGuarded(dst []uint16, a []uint16, s uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleUint16VX(dst[:n:n], a, s)
}

func addScalarUint16VXGuarded(dst []uint16, a []uint16, s uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint16VX(dst[:n:n], a, s)
}

func subScalarUint16VXGuarded(dst []uint16, a []uint16, s uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint16VX(dst[:n:n], a, s)
}

func clampUint16VXGuarded(dst []uint16, a []uint16, lo uint16, hi uint16) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint16VX(dst[:n:n], a, lo, hi)
}

func fillUint16VXGuarded(dst []uint16, v uint16) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint16VX(dst, v)
}

func lerpUint16VXGuarded(dst []uint16, a []uint16, b []uint16, t uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpUint16VX(dst[:n:n], a, b, t)
}

func addScaledUint16VXGuarded(dst []uint16, a []uint16, b []uint16, s uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledUint16VX(dst[:n:n], a, b, s)
}

func rampUint16VXGuarded(dst []uint16, start uint16, step uint16) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampUint16VX(dst, start, step)
}

func addUint32VXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint32VX(dst[:n:n], a, b)
}

func subUint32VXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint32VX(dst[:n:n], a, b)
}

func mulUint32VXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Mul(dst, a, b)
		return
	}
	mulUint32VX(dst[:n:n], a, b)
}

func minimumUint32VXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint32VX(dst[:n:n], a, b)
}

func maximumUint32VXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint32VX(dst[:n:n], a, b)
}

func absUint32VXGuarded(dst []uint32, a []uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint32VX(dst[:n:n], a)
}

func negUint32VXGuarded(dst []uint32, a []uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint32VX(dst[:n:n], a)
}

func scaleUint32VXGuarded(dst []uint32, a []uint32, s uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Scale(dst, a, s)
		return
	}
	scaleUint32VX(dst[:n:n], a, s)
}

func addScalarUint32VXGuarded(dst []uint32, a []uint32, s uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint32VX(dst[:n:n], a, s)
}

func subScalarUint32VXGuarded(dst []uint32, a []uint32, s uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint32VX(dst[:n:n], a, s)
}

func clampUint32VXGuarded(dst []uint32, a []uint32, lo uint32, hi uint32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint32VX(dst[:n:n], a, lo, hi)
}

func fillUint32VXGuarded(dst []uint32, v uint32) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint32VX(dst, v)
}

func lerpUint32VXGuarded(dst []uint32, a []uint32, b []uint32, t uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Lerp(dst, a, b, t)
		return
	}
	lerpUint32VX(dst[:n:n], a, b, t)
}

func addScaledUint32VXGuarded(dst []uint32, a []uint32, b []uint32, s uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.AddScaled(dst, a, b, s)
		return
	}
	addScaledUint32VX(dst[:n:n], a, b, s)
}

func rampUint32VXGuarded(dst []uint32, start uint32, step uint32) {
	if len(dst) < 16 {
		ref.Ramp(dst, start, step)
		return
	}
	rampUint32VX(dst, start, step)
}

func addUint64VXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Add(dst, a, b)
		return
	}
	addUint64VX(dst[:n:n], a, b)
}

func subUint64VXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Sub(dst, a, b)
		return
	}
	subUint64VX(dst[:n:n], a, b)
}

func minimumUint64VXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MinimumInt(dst, a, b)
		return
	}
	minimumUint64VX(dst[:n:n], a, b)
}

func maximumUint64VXGuarded(dst []uint64, a []uint64, b []uint64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.MaximumInt(dst, a, b)
		return
	}
	maximumUint64VX(dst[:n:n], a, b)
}

func absUint64VXGuarded(dst []uint64, a []uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AbsInt(dst, a)
		return
	}
	absUint64VX(dst[:n:n], a)
}

func negUint64VXGuarded(dst []uint64, a []uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.NegInt(dst, a)
		return
	}
	negUint64VX(dst[:n:n], a)
}

func addScalarUint64VXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.AddScalar(dst, a, s)
		return
	}
	addScalarUint64VX(dst[:n:n], a, s)
}

func subScalarUint64VXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.SubScalar(dst, a, s)
		return
	}
	subScalarUint64VX(dst[:n:n], a, s)
}

func clampUint64VXGuarded(dst []uint64, a []uint64, lo uint64, hi uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.ClampInt(dst, a, lo, hi)
		return
	}
	clampUint64VX(dst[:n:n], a, lo, hi)
}

func fillUint64VXGuarded(dst []uint64, v uint64) {
	if len(dst) < 16 {
		ref.Fill(dst, v)
		return
	}
	fillUint64VX(dst, v)
}

func shlInt32VXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlInt32VX(dst[:n:n], a, s)
}

func shrInt32VXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt32VX(dst[:n:n], a, s)
}

func rotlInt32VXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlInt32VX(dst[:n:n], a, s)
}

func rotrInt32VXGuarded(dst []int32, a []int32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrInt32VX(dst[:n:n], a, s)
}

func shlInt64VXGuarded(dst []int64, a []int64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlInt64VX(dst[:n:n], a, s)
}

func shrInt64VXGuarded(dst []int64, a []int64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt64VX(dst[:n:n], a, s)
}

func shrInt8VXGuarded(dst []int8, a []int8, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt8VX(dst[:n:n], a, s)
}

func shlInt16VXGuarded(dst []int16, a []int16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlInt16VX(dst[:n:n], a, s)
}

func shrInt16VXGuarded(dst []int16, a []int16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrInt16VX(dst[:n:n], a, s)
}

func shrUint8VXGuarded(dst []byte, a []byte, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint8VX(dst[:n:n], a, s)
}

func shlUint16VXGuarded(dst []uint16, a []uint16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlUint16VX(dst[:n:n], a, s)
}

func shrUint16VXGuarded(dst []uint16, a []uint16, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint16VX(dst[:n:n], a, s)
}

func shlUint32VXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlUint32VX(dst[:n:n], a, s)
}

func shrUint32VXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint32VX(dst[:n:n], a, s)
}

func rotlUint32VXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotl(dst, a, s)
		return
	}
	rotlUint32VX(dst[:n:n], a, s)
}

func rotrUint32VXGuarded(dst []uint32, a []uint32, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Rotr(dst, a, s)
		return
	}
	rotrUint32VX(dst[:n:n], a, s)
}

func shlUint64VXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shl(dst, a, s)
		return
	}
	shlUint64VX(dst[:n:n], a, s)
}

func shrUint64VXGuarded(dst []uint64, a []uint64, s uint64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Shr(dst, a, s)
		return
	}
	shrUint64VX(dst[:n:n], a, s)
}

func divFloat32VXGuarded(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Div(dst, a, b)
		return
	}
	divFloat32VX(dst[:n:n], a, b)
}

func divScalarFloat32VXGuarded(dst []float32, a []float32, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DivScalar(dst, a, s)
		return
	}
	divScalarFloat32VX(dst[:n:n], a, s)
}

func sqrtFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Sqrt(dst, a)
		return
	}
	sqrtFloat32VX(dst[:n:n], a)
}

func reciprocalFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Reciprocal(dst, a)
		return
	}
	reciprocalFloat32VX(dst[:n:n], a)
}

func floorFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Floor(dst, a)
		return
	}
	floorFloat32VX(dst[:n:n], a)
}

func ceilFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Ceil(dst, a)
		return
	}
	ceilFloat32VX(dst[:n:n], a)
}

func truncFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Trunc(dst, a)
		return
	}
	truncFloat32VX(dst[:n:n], a)
}

func roundFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Round(dst, a)
		return
	}
	roundFloat32VX(dst[:n:n], a)
}

func roundToEvenFloat32VXGuarded(dst []float32, a []float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.RoundToEven(dst, a)
		return
	}
	roundToEvenFloat32VX(dst[:n:n], a)
}

func divFloat64VXGuarded(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.Div(dst, a, b)
		return
	}
	divFloat64VX(dst[:n:n], a, b)
}

func divScalarFloat64VXGuarded(dst []float64, a []float64, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.DivScalar(dst, a, s)
		return
	}
	divScalarFloat64VX(dst[:n:n], a, s)
}

func sqrtFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Sqrt(dst, a)
		return
	}
	sqrtFloat64VX(dst[:n:n], a)
}

func reciprocalFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Reciprocal(dst, a)
		return
	}
	reciprocalFloat64VX(dst[:n:n], a)
}

func floorFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Floor(dst, a)
		return
	}
	floorFloat64VX(dst[:n:n], a)
}

func ceilFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Ceil(dst, a)
		return
	}
	ceilFloat64VX(dst[:n:n], a)
}

func truncFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Trunc(dst, a)
		return
	}
	truncFloat64VX(dst[:n:n], a)
}

func roundFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.Round(dst, a)
		return
	}
	roundFloat64VX(dst[:n:n], a)
}

func roundToEvenFloat64VXGuarded(dst []float64, a []float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.RoundToEven(dst, a)
		return
	}
	roundToEvenFloat64VX(dst[:n:n], a)
}

func satAddInt8VXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddInt8VX(dst[:n:n], a, b)
}

func satSubInt8VXGuarded(dst []int8, a []int8, b []int8) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubInt8VX(dst[:n:n], a, b)
}

func satAddInt16VXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddInt16VX(dst[:n:n], a, b)
}

func satSubInt16VXGuarded(dst []int16, a []int16, b []int16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubInt16VX(dst[:n:n], a, b)
}

func satAddUint8VXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddUint8VX(dst[:n:n], a, b)
}

func satSubUint8VXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubUint8VX(dst[:n:n], a, b)
}

func satSubUint16VXGuarded(dst []uint16, a []uint16, b []uint16) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubUint16VX(dst[:n:n], a, b)
}

func satAddUint32VXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatAdd(dst, a, b)
		return
	}
	satAddUint32VX(dst[:n:n], a, b)
}

func satSubUint32VXGuarded(dst []uint32, a []uint32, b []uint32) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.SatSub(dst, a, b)
		return
	}
	satSubUint32VX(dst[:n:n], a, b)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("vx")
	s.F32.Add = addFloat32VXGuarded
	s.F32.Sub = subFloat32VXGuarded
	s.F32.Mul = mulFloat32VXGuarded
	s.F32.Minimum = minimumFloat32VXGuarded
	s.F32.Maximum = maximumFloat32VXGuarded
	s.F32.Abs = absFloat32VXGuarded
	s.F32.Neg = negFloat32VXGuarded
	s.F32.Scale = scaleFloat32VXGuarded
	s.F32.AddScalar = addScalarFloat32VXGuarded
	s.F32.SubScalar = subScalarFloat32VXGuarded
	s.F32.Clamp = clampFloat32VXGuarded
	s.F32.Fill = fillFloat32VXGuarded
	s.F32.Lerp = lerpFloat32VXGuarded
	s.F32.AddScaled = addScaledFloat32VXGuarded
	s.F64.Add = addFloat64VXGuarded
	s.F64.Sub = subFloat64VXGuarded
	s.F64.Mul = mulFloat64VXGuarded
	s.F64.Minimum = minimumFloat64VXGuarded
	s.F64.Maximum = maximumFloat64VXGuarded
	s.F64.Abs = absFloat64VXGuarded
	s.F64.Neg = negFloat64VXGuarded
	s.F64.Scale = scaleFloat64VXGuarded
	s.F64.AddScalar = addScalarFloat64VXGuarded
	s.F64.SubScalar = subScalarFloat64VXGuarded
	s.F64.Clamp = clampFloat64VXGuarded
	s.F64.Fill = fillFloat64VXGuarded
	s.F64.Lerp = lerpFloat64VXGuarded
	s.F64.AddScaled = addScaledFloat64VXGuarded
	s.F64.Ramp = rampFloat64VXGuarded
	s.I32.Add = addInt32VXGuarded
	s.I32.Sub = subInt32VXGuarded
	s.I32.Mul = mulInt32VXGuarded
	s.I32.Minimum = minimumInt32VXGuarded
	s.I32.Maximum = maximumInt32VXGuarded
	s.I32.Abs = absInt32VXGuarded
	s.I32.Neg = negInt32VXGuarded
	s.I32.Scale = scaleInt32VXGuarded
	s.I32.AddScalar = addScalarInt32VXGuarded
	s.I32.SubScalar = subScalarInt32VXGuarded
	s.I32.Clamp = clampInt32VXGuarded
	s.I32.Fill = fillInt32VXGuarded
	s.I32.Lerp = lerpInt32VXGuarded
	s.I32.AddScaled = addScaledInt32VXGuarded
	s.I32.Ramp = rampInt32VXGuarded
	s.I64.Add = addInt64VXGuarded
	s.I64.Sub = subInt64VXGuarded
	s.I64.Minimum = minimumInt64VXGuarded
	s.I64.Maximum = maximumInt64VXGuarded
	s.I64.Abs = absInt64VXGuarded
	s.I64.Neg = negInt64VXGuarded
	s.I64.AddScalar = addScalarInt64VXGuarded
	s.I64.SubScalar = subScalarInt64VXGuarded
	s.I64.Clamp = clampInt64VXGuarded
	s.I64.Fill = fillInt64VXGuarded
	s.I8.Add = addInt8VXGuarded
	s.I8.Sub = subInt8VXGuarded
	s.I8.Mul = mulInt8VXGuarded
	s.I8.Minimum = minimumInt8VXGuarded
	s.I8.Maximum = maximumInt8VXGuarded
	s.I8.Abs = absInt8VXGuarded
	s.I8.Neg = negInt8VXGuarded
	s.I8.Scale = scaleInt8VXGuarded
	s.I8.AddScalar = addScalarInt8VXGuarded
	s.I8.SubScalar = subScalarInt8VXGuarded
	s.I8.Clamp = clampInt8VXGuarded
	s.I8.Fill = fillInt8VXGuarded
	s.I8.Lerp = lerpInt8VXGuarded
	s.I8.AddScaled = addScaledInt8VXGuarded
	s.I8.Ramp = rampInt8VXGuarded
	s.I16.Add = addInt16VXGuarded
	s.I16.Sub = subInt16VXGuarded
	s.I16.Mul = mulInt16VXGuarded
	s.I16.Minimum = minimumInt16VXGuarded
	s.I16.Maximum = maximumInt16VXGuarded
	s.I16.Abs = absInt16VXGuarded
	s.I16.Neg = negInt16VXGuarded
	s.I16.Scale = scaleInt16VXGuarded
	s.I16.AddScalar = addScalarInt16VXGuarded
	s.I16.SubScalar = subScalarInt16VXGuarded
	s.I16.Clamp = clampInt16VXGuarded
	s.I16.Fill = fillInt16VXGuarded
	s.I16.Lerp = lerpInt16VXGuarded
	s.I16.AddScaled = addScaledInt16VXGuarded
	s.I16.Ramp = rampInt16VXGuarded
	s.U8.Add = addUint8VXGuarded
	s.U8.Sub = subUint8VXGuarded
	s.U8.Mul = mulUint8VXGuarded
	s.U8.Minimum = minimumUint8VXGuarded
	s.U8.Maximum = maximumUint8VXGuarded
	s.U8.Abs = absUint8VXGuarded
	s.U8.Neg = negUint8VXGuarded
	s.U8.Scale = scaleUint8VXGuarded
	s.U8.AddScalar = addScalarUint8VXGuarded
	s.U8.SubScalar = subScalarUint8VXGuarded
	s.U8.Clamp = clampUint8VXGuarded
	s.U8.Fill = fillUint8VXGuarded
	s.U8.Lerp = lerpUint8VXGuarded
	s.U8.AddScaled = addScaledUint8VXGuarded
	s.U8.Ramp = rampUint8VXGuarded
	s.U16.Add = addUint16VXGuarded
	s.U16.Sub = subUint16VXGuarded
	s.U16.Mul = mulUint16VXGuarded
	s.U16.Minimum = minimumUint16VXGuarded
	s.U16.Maximum = maximumUint16VXGuarded
	s.U16.Abs = absUint16VXGuarded
	s.U16.Neg = negUint16VXGuarded
	s.U16.Scale = scaleUint16VXGuarded
	s.U16.AddScalar = addScalarUint16VXGuarded
	s.U16.SubScalar = subScalarUint16VXGuarded
	s.U16.Clamp = clampUint16VXGuarded
	s.U16.Fill = fillUint16VXGuarded
	s.U16.Lerp = lerpUint16VXGuarded
	s.U16.AddScaled = addScaledUint16VXGuarded
	s.U16.Ramp = rampUint16VXGuarded
	s.U32.Add = addUint32VXGuarded
	s.U32.Sub = subUint32VXGuarded
	s.U32.Mul = mulUint32VXGuarded
	s.U32.Minimum = minimumUint32VXGuarded
	s.U32.Maximum = maximumUint32VXGuarded
	s.U32.Abs = absUint32VXGuarded
	s.U32.Neg = negUint32VXGuarded
	s.U32.Scale = scaleUint32VXGuarded
	s.U32.AddScalar = addScalarUint32VXGuarded
	s.U32.SubScalar = subScalarUint32VXGuarded
	s.U32.Clamp = clampUint32VXGuarded
	s.U32.Fill = fillUint32VXGuarded
	s.U32.Lerp = lerpUint32VXGuarded
	s.U32.AddScaled = addScaledUint32VXGuarded
	s.U32.Ramp = rampUint32VXGuarded
	s.U64.Add = addUint64VXGuarded
	s.U64.Sub = subUint64VXGuarded
	s.U64.Minimum = minimumUint64VXGuarded
	s.U64.Maximum = maximumUint64VXGuarded
	s.U64.Abs = absUint64VXGuarded
	s.U64.Neg = negUint64VXGuarded
	s.U64.AddScalar = addScalarUint64VXGuarded
	s.U64.SubScalar = subScalarUint64VXGuarded
	s.U64.Clamp = clampUint64VXGuarded
	s.U64.Fill = fillUint64VXGuarded
	s.I32.Shl = shlInt32VXGuarded
	s.I32.Shr = shrInt32VXGuarded
	s.I32.Rotl = rotlInt32VXGuarded
	s.I32.Rotr = rotrInt32VXGuarded
	s.I64.Shl = shlInt64VXGuarded
	s.I64.Shr = shrInt64VXGuarded
	s.I8.Shr = shrInt8VXGuarded
	s.I16.Shl = shlInt16VXGuarded
	s.I16.Shr = shrInt16VXGuarded
	s.U8.Shr = shrUint8VXGuarded
	s.U16.Shl = shlUint16VXGuarded
	s.U16.Shr = shrUint16VXGuarded
	s.U32.Shl = shlUint32VXGuarded
	s.U32.Shr = shrUint32VXGuarded
	s.U32.Rotl = rotlUint32VXGuarded
	s.U32.Rotr = rotrUint32VXGuarded
	s.U64.Shl = shlUint64VXGuarded
	s.U64.Shr = shrUint64VXGuarded
	s.F32.Div = divFloat32VXGuarded
	s.F32.DivScalar = divScalarFloat32VXGuarded
	s.F32.Sqrt = sqrtFloat32VXGuarded
	s.F32.Reciprocal = reciprocalFloat32VXGuarded
	s.F32.Floor = floorFloat32VXGuarded
	s.F32.Ceil = ceilFloat32VXGuarded
	s.F32.Trunc = truncFloat32VXGuarded
	s.F32.Round = roundFloat32VXGuarded
	s.F32.RoundToEven = roundToEvenFloat32VXGuarded
	s.F64.Div = divFloat64VXGuarded
	s.F64.DivScalar = divScalarFloat64VXGuarded
	s.F64.Sqrt = sqrtFloat64VXGuarded
	s.F64.Reciprocal = reciprocalFloat64VXGuarded
	s.F64.Floor = floorFloat64VXGuarded
	s.F64.Ceil = ceilFloat64VXGuarded
	s.F64.Trunc = truncFloat64VXGuarded
	s.F64.Round = roundFloat64VXGuarded
	s.F64.RoundToEven = roundToEvenFloat64VXGuarded
	s.I8.SatAdd = satAddInt8VXGuarded
	s.I8.SatSub = satSubInt8VXGuarded
	s.I16.SatAdd = satAddInt16VXGuarded
	s.I16.SatSub = satSubInt16VXGuarded
	s.U8.SatAdd = satAddUint8VXGuarded
	s.U8.SatSub = satSubUint8VXGuarded
	s.U16.SatSub = satSubUint16VXGuarded
	s.U32.SatAdd = satAddUint32VXGuarded
	s.U32.SatSub = satSubUint32VXGuarded
}
