// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/bytes.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import (
	"runtime"

	"github.com/sebishogun/simd/internal/backend"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

func lastIndexByteVXGuarded(b []byte, c byte) int {
	if len(b) < 64 {
		return ref.LastIndexByte(b, c)
	}
	return lastIndexByteVX(b, c)
}

func popCountVXGuarded(b []byte) int {
	if len(b) < 64 {
		return ref.PopCount(b)
	}
	return popCountVX(b)
}

func isASCIIVXGuarded(b []byte) bool {
	if len(b) < 64 {
		return ref.IsASCII(b)
	}
	return isASCIIVX(b)
}

func equalBytesVXGuarded(a []byte, b []byte) bool {
	n := min(len(a), len(b))
	if n < 1073741824 || len(a) != len(b) {
		return ref.EqualBytes(a, b)
	}
	return equalBytesVX(a[:n:n], b)
}

func bitAndVXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAnd(dst, a, b)
		return
	}
	bitAndVX(dst[:n:n], a, b)
}

func bitOrVXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitOr(dst, a, b)
		return
	}
	bitOrVX(dst[:n:n], a, b)
}

func bitXorVXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitXor(dst, a, b)
		return
	}
	bitXorVX(dst[:n:n], a, b)
}

func bitAndNotVXGuarded(dst []byte, a []byte, b []byte) {
	n := min(len(dst), len(a), len(b))
	if n < 32 {
		ref.BitAndNot(dst, a, b)
		return
	}
	bitAndNotVX(dst[:n:n], a, b)
}

func bitNotVXGuarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.BitNot(dst, b)
		return
	}
	bitNotVX(dst[:n:n], b)
}

func fillBytesVXGuarded(dst []byte, v byte) {
	if len(dst) < 32 {
		ref.FillBytes(dst, v)
		return
	}
	fillBytesVX(dst, v)
}

func hexEncodeVXGuarded(dst []byte, b []byte) int {
	if len(dst) < 32 {
		return ref.HexEncode(dst, b)
	}
	return hexEncodeVX(dst, b)
}

func toUpperASCIIVXGuarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToUpperASCII(dst, b)
		return
	}
	toUpperASCIIVX(dst[:n:n], b)
}

func toLowerASCIIVXGuarded(dst []byte, b []byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ToLowerASCII(dst, b)
		return
	}
	toLowerASCIIVX(dst[:n:n], b)
}

func replaceByteVXGuarded(dst []byte, b []byte, old byte, with byte) {
	n := min(len(dst), len(b))
	if n < 32 {
		ref.ReplaceByte(dst, b, old, with)
		return
	}
	replaceByteVX(dst[:n:n], b, old, with)
}

func init() {
	// Add to the tier's set rather than installing a whole one: other
	// generated files contribute their own kernels to the same tier.
	s := backend.For("vx")
	s.Bytes.LastIndexByte = lastIndexByteVXGuarded
	s.Bytes.PopCount = popCountVXGuarded
	s.Bytes.IsASCII = isASCIIVXGuarded
	s.Bytes.Equal = equalBytesVXGuarded
	s.Bytes.And = bitAndVXGuarded
	s.Bytes.Or = bitOrVXGuarded
	s.Bytes.Xor = bitXorVXGuarded
	s.Bytes.AndNot = bitAndNotVXGuarded
	s.Bytes.Not = bitNotVXGuarded
	s.Bytes.Fill = fillBytesVXGuarded
	s.Bytes.HexEncode = hexEncodeVXGuarded
	s.Bytes.ToUpperASCII = toUpperASCIIVXGuarded
	s.Bytes.ToLowerASCII = toLowerASCIIVXGuarded
	s.Bytes.ReplaceByte = replaceByteVXGuarded
}
