// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/complex.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

func CaddComplex64VX(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CAdd(dst, a, b)
		return
	}
	caddComplex64VX(dst[:n:n], a, b)
}

func CsubComplex64VX(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CSub(dst, a, b)
		return
	}
	csubComplex64VX(dst[:n:n], a, b)
}

func CmulComplex64VX(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CMul64(dst, a, b)
		return
	}
	cmulComplex64VX(dst[:n:n], a, b)
}

func CdivComplex64VX(dst []complex64, a []complex64, b []complex64) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CDiv64(dst, a, b)
		return
	}
	cdivComplex64VX(dst[:n:n], a, b)
}

func CnegComplex64VX(dst []complex64, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CNeg(dst, a)
		return
	}
	cnegComplex64VX(dst[:n:n], a)
}

func CconjComplex64VX(dst []complex64, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CConj64(dst, a)
		return
	}
	cconjComplex64VX(dst[:n:n], a)
}

func CabsComplex64VX(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CAbs64(dst, a)
		return
	}
	cabsComplex64VX(dst[:n:n], a)
}

func CrealComplex64VX(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CReal64(dst, a)
		return
	}
	crealComplex64VX(dst[:n:n], a)
}

func CimagComplex64VX(dst []float32, a []complex64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CImag64(dst, a)
		return
	}
	cimagComplex64VX(dst[:n:n], a)
}

func CscaleComplex64VX(dst []complex64, a []complex64, s float32) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CScale64(dst, a, s)
		return
	}
	cscaleComplex64VX(dst[:n:n], a, s)
}

func CsumComplex64VX(a []complex64) complex64 {
	if len(a) < 0 {
		return ref.CSum64(a)
	}
	return csumComplex64VX(a)
}

func CaddComplex128VX(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CAdd(dst, a, b)
		return
	}
	caddComplex128VX(dst[:n:n], a, b)
}

func CsubComplex128VX(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CSub(dst, a, b)
		return
	}
	csubComplex128VX(dst[:n:n], a, b)
}

func CmulComplex128VX(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CMul128(dst, a, b)
		return
	}
	cmulComplex128VX(dst[:n:n], a, b)
}

func CdivComplex128VX(dst []complex128, a []complex128, b []complex128) {
	n := min(len(dst), len(a), len(b))
	if n < 16 {
		ref.CDiv128(dst, a, b)
		return
	}
	cdivComplex128VX(dst[:n:n], a, b)
}

func CnegComplex128VX(dst []complex128, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CNeg(dst, a)
		return
	}
	cnegComplex128VX(dst[:n:n], a)
}

func CabsComplex128VX(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CAbs128(dst, a)
		return
	}
	cabsComplex128VX(dst[:n:n], a)
}

func CrealComplex128VX(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CReal128(dst, a)
		return
	}
	crealComplex128VX(dst[:n:n], a)
}

func CimagComplex128VX(dst []float64, a []complex128) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CImag128(dst, a)
		return
	}
	cimagComplex128VX(dst[:n:n], a)
}

func CscaleComplex128VX(dst []complex128, a []complex128, s float64) {
	n := min(len(dst), len(a))
	if n < 16 {
		ref.CScale128(dst, a, s)
		return
	}
	cscaleComplex128VX(dst[:n:n], a, s)
}

func CsumComplex128VX(a []complex128) complex128 {
	if len(a) < 0 {
		return ref.CSum128(a)
	}
	return csumComplex128VX(a)
}

func CdotComplex128VX(a []complex128, b []complex128) complex128 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.CDot128(a, b)
	}
	return cdotComplex128VX(a[:n:n], b)
}

func CdotconjComplex128VX(a []complex128, b []complex128) complex128 {
	n := min(len(a), len(b))
	if n < 0 {
		return ref.CDotConj128(a, b)
	}
	return cdotconjComplex128VX(a[:n:n], b)
}

func registerComplexVX(s *kernel.Set) {
	s.C64.Add = CaddComplex64VX
	s.C64.Sub = CsubComplex64VX
	s.C64.Mul = CmulComplex64VX
	s.C64.Div = CdivComplex64VX
	s.C64.Neg = CnegComplex64VX
	s.C64.Conj = CconjComplex64VX
	s.C64Parts.Abs = CabsComplex64VX
	s.C64Parts.Real = CrealComplex64VX
	s.C64Parts.Imag = CimagComplex64VX
	s.C64Parts.Scale = CscaleComplex64VX
	s.C64.Sum = CsumComplex64VX
	s.C128.Add = CaddComplex128VX
	s.C128.Sub = CsubComplex128VX
	s.C128.Mul = CmulComplex128VX
	s.C128.Div = CdivComplex128VX
	s.C128.Neg = CnegComplex128VX
	s.C128Parts.Abs = CabsComplex128VX
	s.C128Parts.Real = CrealComplex128VX
	s.C128Parts.Imag = CimagComplex128VX
	s.C128Parts.Scale = CscaleComplex128VX
	s.C128.Sum = CsumComplex128VX
	s.C128.Dot = CdotComplex128VX
	s.C128.DotConj = CdotconjComplex128VX
}
