// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/math.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

func HypotFloat32VX(dst []float32, a []float32, b []float32) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Hypot(dst, a, b)
		return
	}
	hypotFloat32VX(dst[:n:n], a, b)
}

func HypotFloat64VX(dst []float64, a []float64, b []float64) {
	n := min(len(dst), len(a), len(b))
	if n < 4 {
		ref.Hypot(dst, a, b)
		return
	}
	hypotFloat64VX(dst[:n:n], a, b)
}

func registerMathVX(s *kernel.Set) {
	s.F32.Hypot = HypotFloat32VX
	s.F64.Hypot = HypotFloat64VX
}
