// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/nary.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import (
	"runtime"

	"github.com/sebishogun/simd/internal/kernel"
	"github.com/sebishogun/simd/internal/ref"
)

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

func Add3Float32VX(dst []float32, a []float32, b []float32, c []float32) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Float32VX(dst[:n:n], a, b, c)
}

func Mul3Float32VX(dst []float32, a []float32, b []float32, c []float32) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Float32VX(dst[:n:n], a, b, c)
}

func Add3Float64VX(dst []float64, a []float64, b []float64, c []float64) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Float64VX(dst[:n:n], a, b, c)
}

func Mul3Float64VX(dst []float64, a []float64, b []float64, c []float64) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Float64VX(dst[:n:n], a, b, c)
}

func Add3Int32VX(dst []int32, a []int32, b []int32, c []int32) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Int32VX(dst[:n:n], a, b, c)
}

func Mul3Int32VX(dst []int32, a []int32, b []int32, c []int32) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Int32VX(dst[:n:n], a, b, c)
}

func Add3Int64VX(dst []int64, a []int64, b []int64, c []int64) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Int64VX(dst[:n:n], a, b, c)
}

func Add3Int8VX(dst []int8, a []int8, b []int8, c []int8) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Int8VX(dst[:n:n], a, b, c)
}

func Mul3Int8VX(dst []int8, a []int8, b []int8, c []int8) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Int8VX(dst[:n:n], a, b, c)
}

func Add3Int16VX(dst []int16, a []int16, b []int16, c []int16) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Int16VX(dst[:n:n], a, b, c)
}

func Mul3Int16VX(dst []int16, a []int16, b []int16, c []int16) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Int16VX(dst[:n:n], a, b, c)
}

func Add3Uint8VX(dst []byte, a []byte, b []byte, c []byte) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Uint8VX(dst[:n:n], a, b, c)
}

func Mul3Uint8VX(dst []byte, a []byte, b []byte, c []byte) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Uint8VX(dst[:n:n], a, b, c)
}

func Add3Uint16VX(dst []uint16, a []uint16, b []uint16, c []uint16) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Uint16VX(dst[:n:n], a, b, c)
}

func Mul3Uint16VX(dst []uint16, a []uint16, b []uint16, c []uint16) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Uint16VX(dst[:n:n], a, b, c)
}

func Add3Uint32VX(dst []uint32, a []uint32, b []uint32, c []uint32) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Uint32VX(dst[:n:n], a, b, c)
}

func Mul3Uint32VX(dst []uint32, a []uint32, b []uint32, c []uint32) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Mul3(dst, a, b, c)
		return
	}
	mul3Uint32VX(dst[:n:n], a, b, c)
}

func Add3Uint64VX(dst []uint64, a []uint64, b []uint64, c []uint64) {
	n := min(len(dst), len(a), len(b), len(c))
	if n < 256 {
		ref.Add3(dst, a, b, c)
		return
	}
	add3Uint64VX(dst[:n:n], a, b, c)
}

func registerNaryVX(s *kernel.Set) {
	s.F32.Add3 = Add3Float32VX
	s.F32.Mul3 = Mul3Float32VX
	s.F64.Add3 = Add3Float64VX
	s.F64.Mul3 = Mul3Float64VX
	s.I32.Add3 = Add3Int32VX
	s.I32.Mul3 = Mul3Int32VX
	s.I64.Add3 = Add3Int64VX
	s.I8.Add3 = Add3Int8VX
	s.I8.Mul3 = Mul3Int8VX
	s.I16.Add3 = Add3Int16VX
	s.I16.Mul3 = Mul3Int16VX
	s.U8.Add3 = Add3Uint8VX
	s.U8.Mul3 = Mul3Uint8VX
	s.U16.Add3 = Add3Uint16VX
	s.U16.Mul3 = Mul3Uint16VX
	s.U32.Add3 = Add3Uint32VX
	s.U32.Mul3 = Mul3Uint32VX
	s.U64.Add3 = Add3Uint64VX
}
