// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/nary.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import "runtime"

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

//go:noescape
func add3Float32VX(dst []float32, a []float32, b []float32, c []float32)

//go:noescape
func mul3Float32VX(dst []float32, a []float32, b []float32, c []float32)

//go:noescape
func add3Float64VX(dst []float64, a []float64, b []float64, c []float64)

//go:noescape
func mul3Float64VX(dst []float64, a []float64, b []float64, c []float64)

//go:noescape
func add3Int32VX(dst []int32, a []int32, b []int32, c []int32)

//go:noescape
func mul3Int32VX(dst []int32, a []int32, b []int32, c []int32)

//go:noescape
func add3Int64VX(dst []int64, a []int64, b []int64, c []int64)

//go:noescape
func add3Int8VX(dst []int8, a []int8, b []int8, c []int8)

//go:noescape
func mul3Int8VX(dst []int8, a []int8, b []int8, c []int8)

//go:noescape
func add3Int16VX(dst []int16, a []int16, b []int16, c []int16)

//go:noescape
func mul3Int16VX(dst []int16, a []int16, b []int16, c []int16)

//go:noescape
func add3Uint8VX(dst []byte, a []byte, b []byte, c []byte)

//go:noescape
func mul3Uint8VX(dst []byte, a []byte, b []byte, c []byte)

//go:noescape
func add3Uint16VX(dst []uint16, a []uint16, b []uint16, c []uint16)

//go:noescape
func mul3Uint16VX(dst []uint16, a []uint16, b []uint16, c []uint16)

//go:noescape
func add3Uint32VX(dst []uint32, a []uint32, b []uint32, c []uint32)

//go:noescape
func mul3Uint32VX(dst []uint32, a []uint32, b []uint32, c []uint32)

//go:noescape
func add3Uint64VX(dst []uint64, a []uint64, b []uint64, c []uint64)
