// Code generated by simdgen. DO NOT EDIT.
//
// Source: csrc/reduce.c
// Target: s390x/vx

//go:build s390x && !purego

package s390x

import "runtime"

// Compile-time check that this file is only ever built for s390x. The build
// constraint above and the _s390x filename suffix should both already ensure
// it; if either were wrong this map literal would have a duplicate false key,
// which is a compile error rather than a SIGILL on someone else's machine.
var _ = map[bool]struct{}{false: {}, runtime.GOARCH == "s390x": {}}

//go:noescape
func sumFloat32VX(a []float32) float32

//go:noescape
func dotFloat32VX(a []float32, b []float32) float32

//go:noescape
func sumFloat64VX(a []float64) float64

//go:noescape
func dotFloat64VX(a []float64, b []float64) float64
